window.HAN09 = {
  id: "han-09",
  dynasty: "Han",
  order: 9,
  title: "Ten Thousand Changes",
  subtitle: "Chang'an and the New, 8 CE to 23 CE",
  readMinutes: 8,
  hook: "A poor relation of the imperial in-laws, who had starved his reputation into fame, took the empire's seals in the last month of 8 CE and put the state back into the shapes of the Zhou ritual books — land, coin, office, the titles of kings beyond the frontier — and found a realm that could not read what had been written for it.",
  heroAlt: "A single figure in yellow ceremonial robe and a cap of king's jade standing on the steps of a vast rammed-earth hall at dawn while scribes kneel in rows copying name-boards and a line of envoys with yellow-tipped staffs carries new seals out through the gate, 9 CE",
  people: [
    { name: "Wang Mang", role: "Regent, then the one emperor of the New. Poor in a house of nine marquisates, famous for his own frugality, he governed an empire the way he had read a classic: by correcting the words." },
    { name: "Grand Empress Dowager Wang", role: "The Han's great-grandmother and the Wang family's own root. She held the transmission seal, threw it down at her nephew's man, and told his brothers they would be clan-exterminated." },
    { name: "Liu Xin", role: "The age's greatest scholar of texts and the New's Teaching Master of the State, the man who wrote its ceremonies. An open indictment named him as the one who had inverted the Five Classics; he took his own life after a plot." },
    { name: "Ai Zhang", role: "A man of Zitong studying in the capital, recorded as fond of large talk. He cast the bronze casket, wrote the eleven names inside it, added his own, and became a duke." },
    { name: "Ou Bo", role: "A middle-rank palace officer. One memorial of his — the well-field has been dead a thousand years, not even Yao and Shun could revive it in a hundred — reversed the dynasty's central law." },
    { name: "Yan You", role: "The one commander who argued against every frontier at once, and against encircling Kunyang. He got the king's head he said he would not hunt, and lost his rank for putting the bandits first." },
    { name: "Wang Yi", role: "Commander-in-chief of the New and Marquis of Chengdu. He led the mobilisation of a million, refused good advice twice under Kunyang, and rode back to Luoyang with a few thousand men." }
  ],
  panels: [
    {
      art: "panels/han09/00-cover.png", ratio: 1.75, size: "wide",
      caption: "For fourteen years one emperor tried to run the largest state in the world out of the ritual classics of a dynasty seven hundred years dead, and his own history keeps the failure as a column of figures: how many kinds of money, how many names, how many dead, and in which month each law was withdrawn.",
      sima: { text: "This episode is told out of the Book of the Han: the three-part biography of Wang Mang, juan 99 upper, middle and lower; the Treatise on Food and Money for the coinage and the taxes; the lower biography of the Xiongnu and the memoir of the Western Regions for the frontier; and the biographies of the women of the house for the emperor's own family. The Book of the Later Han supplies the rising of the Red Eyebrows and the battle of Kunyang, and where its figures differ the note says so. The Ming and Qing romances of the restoration, which have a great deal to say about these years, are used nowhere and only named when a story needs to be taken back out.", source: "On our sources", tag: "note" }
    },
    {
      art: "panels/han09/02-nine-marquises.png", ratio: 1.75, size: "wide",
      caption: "The Wang house had nine marquisates and five Grand Marshalships in the two reigns before his, and five of the emperor's uncles were enfeoffed on a single day. One branch got no marquisate, because its head died early: out of that gap came a student of the ritual classics who tasted his dying uncle's medicine for months with his hair unwashed and his belt unloosened, was made Marquis of Xindu with fifteen hundred households in 16 BCE, and gave away his carriages, his horses and his fur coats to his guests until his house had nothing left.",
      sima: { text: "His cousins were the sons of generals and marquises and competed in carriages, horses, music and pretty faces; he alone was poor, and, in Ban Gu's phrase, broke himself on purpose to be modest. The book does not let any of it simply work: it says he dared startling, self-thresholding acts and went through them without embarrassment, and that when his nephew grew up he sent him to a doctor's school, then visited the teacher in person with his chariot and his wine, so that the students came out to stare and the old men sighed — while at the same table a woman he had bought as a slave was being hidden away. His own sentence on that scene is the argument of this episode: it was how he concealed what he felt and courted a name.", source: "Hanshu, juan 99 upper, Biography of Wang Mang; juan 98, Biography of the Empress Dowager Yuan", tag: "history" }
    },
    {
      art: "panels/han09/03-the-oath-keeper.png", ratio: 0.8, size: "std",
      caption: "The one man in the capital whose refusal could not be bought was a noble of Chu called Kong Xiu. Wang Mang pressed a jade-hilted sword on him, saying he had seen a scar on his face and that fine jade will take a scar away; Kong Xiu pleaded illness and would not take it. Mang said: you think it too dear — then he smashed the sword with a mallet, wrapped the pieces in his own hands and sent them, and Kong Xiu accepted them.",
      sima: { text: "The anecdote is placed where it is for a reason: the same pages say that Mang's fame by then had crossed over all his father's generation. The jade he broke was a sword he had been allowed to carry as regent, an object whose value could not be increased by keeping it; the refusal had to be converted into a gift, and then into a sacrifice. This is the technique the rest of the episode runs on — a thing made useless so that its name can work.", source: "Hanshu, juan 99 upper", tag: "commentary" }
    },
    {
      art: "panels/han09/04-the-regency.png", ratio: 0.8, size: "std",
      caption: "Emperor Cheng died on the wu-horse night of the sixth month of 1 BCE; Wang Mang was Grand Marshal two days later, and the favourite who had held the emperor's ear killed himself that same day. He made a child emperor whose mother's family he could keep out, took the title Duke Who Settles the Han in the first month of 1 CE, then the Steward-Balance above the Three Excellencies, then the nine bestowments in 5 CE, and shut the regency's law with fifty new articles whose punishment was transportation to the Western Sea: the transported ran to thousands and tens of thousands, and the people began to resent him.",
      sima: { text: "The titles are fixed by his own resume, recited in 1 CE: Marquis of Xindu, Duke Who Settles the Han, Steward-Balance, Grand Tutor and Grand Marshal — one person wearing five great favours. When he observed that the Steward-Balance had no seal of office and was therefore a name whose substance did not answer it, the Imperial Secretary was ordered to cut one. Ban Gu states the mechanism flatly: when Mang wanted something he let a little of his colour show, his party then drew up a memorial in their own names and presented it, and he bowed his head, wept and refused with every show of firmness — above, to dazzle the Empress Dowager; below, to display good faith to the crowd. Then the limit: his eldest son Yu objected to a Wei granddaughter being married up into the imperial line, and was told by his teacher that Wang Mang could not be remonstrated with but loved ghosts and spirits, so that a prodigy might frighten him; Yu went out at night and threw blood on his gate. Mang killed his son, and Ban Gu's comment is that the way he coerced superiors and inferiors was always of this type.", source: "Hanshu, juan 99 upper", tag: "history" }
    },
    {
      art: "panels/han09/05-the-copper-casket.png", ratio: 1.75, size: "wide",
      caption: "The casket was bronze with two sealed labels. One read: the Heavenly Emperor's travelling seal, the gold cabinet's chart. The other read: the Red Emperor's travelling seal, handed over to the Yellow Emperor's metal book of mandate — and the Red Emperor was the Han's founding lord, named in the text by his given name. Inside was a list of eleven assistants for the new emperor: eight were Wang Mang's actual ministers, two were men looked up in the registers because their names sounded auspicious, and the eleventh was the man who had made the casket.",
      sima: { text: "On a wu-chen day in the last month of 8 CE he went to the Han's own High Temple, received the box, put on the king's cap and sat in the front hall of Weiyang. He declared the dynasty the New, moved the New Year back to the twelfth-month new moon, took yellow for the colour of the age and white for the sacrificial animals, and had every envoy's staff tipped with yellow; the day's numbering is quoted in his own edict, and the same edict puts his enthronement at a new moon in the twelfth month, which is why the last year of the Han and the first year of the New are the same twelve months. Ban Gu's summary of the mandate literature is the flattest sentence in the book: its wording was elegant and borrowed from the classics, all of it manufactured argument, and its drift was that Mang should replace the Han and hold the empire. The eleven names were real appointments: one man had been a clerk at a city gate, one had sold cakes in the market, and Ai Zhang, who had written the whole thing, was made a duke.", source: "Hanshu, juan 99 upper and middle", tag: "history" }
    },
    {
      art: "panels/han09/06-the-old-widow.png", ratio: 0.8, size: "std",
      caption: "To take the throne he had to have the Han's transmission seal, and it was with the one person in his family who had out-vetoed him twice: his aunt, the great-grandmother of the emperor he had deposed. Her own nephew came to ask. She answered that a new dynasty should cut its own seal and hand it down for ten thousand generations, and that she would not use the unlucky seal of a state that had lost the mandate; then she threw it on the floor at Wang Shun's feet and told him and his brothers they would be clan-exterminated. Wang Mang was delighted, and gave a banquet in her honour on the terrace in the middle of the Weiyang lake.",
      bubbles: [
        { who: "grandempressdowagerwang", name: "The Grand Empress Dowager Wang", side: "left", text: "I am the Han's old widow, and I die this morning or tonight. I mean to be buried with this seal. You will not get it." }
      ],
      sima: { text: "Ban Gu keeps the weeping in the room — the women of the bedchamber all crying — and Wang Shun's answer is the sentence that finishes the discussion: we have nothing left to say; if Mang must have the transmitting seal, can you at the last keep refusing him? What came after was the same kindness in another key. A man named Zhang Yong produced a copper mandate saying that she should be styled the Ritual Mother of the New House; it was examined by everyone, and the report came back that the characters were neither carved nor painted but had grown so by their own nature. She gave up her seal of the Grand Empress Dowager, and Zhang Yong was enfeoffed. She died in 13 CE and was buried alongside Emperor Yuan with a ditch cut between their graves, so that they were joined and separated at once; he wore three years of mourning for her. He was still holding a feast for her on that terrace when she gave him the seal.", source: "Hanshu, juan 98, Biography of the Empress Dowager Yuan; juan 99 middle", tag: "history" }
    },
    {
      art: "panels/han09/07-kings-fields.png", ratio: 1.75, size: "wide",
      caption: "His first great law named the fields and the human beings. All land under heaven became the king's fields and all slaves became private retainers, and neither might be bought or sold; a household with fewer than eight male mouths holding more than one well-field — nine hundred mu — had to hand its surplus to its nine kindreds, its neighbours and its hamlet. Anyone who argued that the well-field was not a sage's institution, and so misled the crowd, was to be thrown to the four frontiers to fend off the monsters.",
      sima: { text: "The edict is a quotation, and says so. It begins with Qin: the First Emperor broke the old field system and made the tracks, so that the strong marked out fields by the thousand and the weak had not a spot to stand an awl, and the slave market put human beings in the same pen as oxen and horses. It then argues that the Han's own famous light tax — one in thirty — was in truth five in ten, because of the corvee and the strong households' private exactions, so that a father and son and wife working the year round could not keep themselves alive. Nothing in the law confiscated the land of a house with eight or fewer male mouths, which is why it is much nearer a ban on the traffic than a redistribution. Ban Gu's note on the man's temper belongs beside it: he could not rest from doing things, and every institution he raised he wanted to find a line of scripture for first. The sentencing is the other half of the record: from the marquis down to the commoner, those condemned for buying or selling fields, houses, slaves or coin were past counting.", source: "Hanshu, juan 99 middle; juan 24, Treatise on Food and Money", tag: "history" }
    },
    {
      art: "panels/han09/08-oubo.png", ratio: 0.8, size: "std",
      caption: "The law held three years and was reversed by a middle-rank palace officer named Ou Bo, who told the emperor that the well-field was a sage's law but had been abolished for a very long time, that Qin had read the people's hearts and got the greatest profit from it, and that the whole realm had still not wearied of the harm Qin left behind. To go back against the hearts of the people now, he said, and chase a track cut off a thousand years ago, was something that even Yao and Shun risen again could not do in a hundred years.",
      bubbles: [
        { who: "oubo", name: "Ou Bo", side: "left", text: "The empire has only just been settled and the ten thousand peoples are newly attached. This is not the time to do it." }
      ],
      sima: { text: "Ban Gu reports the reversal in two clauses, and the first is the whole story of the reign: Mang knew the people's resentment, and so he wrote an order. All who hold named king's fields may sell them, and no law shall restrain them; and those who have committed the private buying and selling of ordinary persons shall for the present not be prosecuted. The slave traffic was not legalised — it was left unpursued, which is what a repeal looks like when nobody is willing to say the word. He did not stop the king's-fields law because he had changed his reading of the classics; he stopped it because the empire would not read it.", source: "Hanshu, juan 99 middle", tag: "history" }
    },
    {
      art: "panels/han09/09-twenty-eight-coins.png", ratio: 1.75, size: "wide",
      caption: "In the years from 7 CE he changed the money again and again. First he made a big piece worth fifty of the old coins, a knife worth five hundred and an inlaid knife worth five thousand, running alongside the Han's familiar five-zhu piece; then, because he worked out that the character for the Liu surname contains the words for gold and for knife, he abolished the knives and the five-zhu together and issued a table of twenty-eight denominations in five materials — gold, silver, tortoise-shell, cowries, copper and cloth.",
      sima: { text: "The twenty-eight were a piece of textual criticism performed in copper: the classics supplied the categories, and the treatise supplies the summary — five materials, six names, twenty-eight items. The public answer is one line and a half: the people found the Han's five-zhu convenient, found two sizes of coin hard to tell apart, and did not trust a money that kept changing, so they traded with the old coin privately and spread the word that the big piece was going to be withdrawn. He forbade holding the five-zhu and forbade saying it would be withdrawn, ranking the offence with denying the well-field, punishable by the four frontiers. In 14 CE he cut the table back to two pieces, a cloth-money worth twenty-five and a round coin worth one; and the treatise totals the cost of the revisions in his own administration's words: every time the money changed, the people's business broke and they fell heavily into the law. When private casting could not be stopped, one household casting coin implicated five neighbours, and they were confiscated as slaves.", source: "Hanshu, juan 24, Treatise on Food and Money; juan 99 middle", tag: "history" }
    },
    {
      art: "panels/han09/10-the-river.png", ratio: 0.8, size: "std",
      caption: "In the third year of the New, 11 CE, the Yellow River broke its bank at Wei commandery and ran over Qinghe and the commanderies east of it, and locusts came up in the commanderies along the water. Before this he had been afraid the flooding would reach the ancestral tombs at Yuancheng; when the river went away to the east, Yuancheng had nothing to fear from the water, and so, in his biography's own words, he did not close the breach.",
      sima: { text: "The reason is in the biography and not in a commentator's addition, and it sits there between two portents: at Chiyang in the same year some little men appeared, a foot or so tall, some in chariots and some on foot; they went on for three days and then stopped. Ban Gu records them and links them to nothing. The river is also not, in this book, the cause of the fall: the breach is entered in 11 CE and the first great risings in 17 CE, and the sentences between them are about taxes, about the money, and about a man who would not spend the labour to shut the gap because his own graves were out of the way.", source: "Hanshu, juan 99 middle", tag: "history" }
    },
    {
      art: "panels/han09/11-the-smashed-seal.png", ratio: 1.75, size: "wide",
      caption: "The New's Twelve Generals of the Five Powers went out from the capital with the New's seals and gathered the Han's in. Everywhere they reached the same instruction ran: the kings of the Western Regions were all degraded to marquises, three hundred and seventy-six of their officers off their Han seals; the king of Gouting was made a marquis, resented it, and was tricked to death by a commandery governor taking his hint; the chief of Goguryeo was lured out and beheaded so that his people's title could be cut short into below Goguryeo; and at the chanyu's court the envoy brought a new impression for the same jade — the Han's had read Seal of the Chanyu of the Xiongnu, the New's read Tally of the Chanyu of the New Xiongnu.",
      bubbles: [
        { who: "chanyu", name: "The Chanyu", side: "right", text: "The seal the Han gave said the word for imperial seal and did not carry the word Han. This one drops the first and adds the second: it puts me with your subject officers. Give me back the old seal." }
      ],
      sima: { text: "The old seal was smashed before it was surrendered, on the argument that cutting it would cut the root of the trouble, and when the chanyu asked for it back the envoys showed him the pieces. He had been warned twice by one of his own nobles, who said the new text had not been seen and the old seal should not be given yet; the chanyu answered that a seal's text could not possibly have changed, handed his over without looking at it, and then feasted the envoys until night. Ban Gu's one-line result for the whole operation: the chanyu was furious, and Gouting and the Western Regions in the end all revolted because of this. In 10 CE he renamed the chanyu the slave who submits to punishment, announced that the Xiongnu would be divided into fifteen and fifteen chanyus set up out of one house's descendants, and ordered a march out of ten routes with three hundred thousand men raised from the empire's prisoners, adult males and garrison soldiers, and provisions for three hundred days carried from the seaboard and the lower Yangtze. The men who got there first sat on the frontier waiting for everyone to arrive at once, and the border was left empty behind them.", source: "Hanshu, juan 94 lower, Biography of the Xiongnu; juan 99 middle; juan 96 lower, Biography of the Western Regions", tag: "history" }
    },
    {
      art: "panels/han09/12-the-naming.png", ratio: 0.8, size: "std",
      caption: "In 12 CE the titles of the empire's Eleven Dukes were revised: the character for new was replaced by the character for heart, and the character for heart was then replaced by the character for good faith — one sound, three writings, no change of referent. The commandery governors were renamed Great Instructors, Chang'an became Ever-Safe, Luoyang was proclaimed the eastern capital, and the provinces were redone as twelve out of the Documents and nine out of the Tribute of Yu, because the two classics disagreed and the emperor's edict said that dynasties change each other's arrangements and each has its reasons.",
      sima: { text: "The arithmetic of the settlement was carried out with the same care: seven hundred and ninety-six men had been enfeoffed as dukes, marquises, earls, barons and the lowest rank, and because the maps and registers were not finished, none of them received a fief. They drew a stipend of some thousands of cash a month from the metropolitan treasury, and the enfeoffed nobles were so poor, the book says, that some of them hired themselves out as labourers. He believed that once the institutions were settled the empire would be at peace of itself, so he set his mind on geography, on making the rites and the music, and on fitting the six classics together. The last of these arguments is the one the record cannot get away from. In one of those later years, in the seventh month, a great wind wrecked the hall of the royal road, broke the tiles and snapped the trees, and the edict answering it is his own: he had thought hard about why the rain and wind come out of season, why the drought and the locusts keep coming, why the people starve and the bandits gather, and the fault, he decided, lies in names not being correct — ming bu zheng, ze yan bu shun, the line he quotes out of Confucius: if names are not correct, words are not in accord, and then punishments miss the mark, and the people do not know where to put their hands or feet. His remedy was another renaming.", source: "Hanshu, juan 99 middle and lower", tag: "history" }
    },
    {
      art: "panels/han09/13-six-grips.png", ratio: 0.8, size: "std",
      caption: "The monopolies were his own idea and the classics' words: the state sold the wine, the salt and the iron tools, cast the coin, taxed every taking from the named mountains and marshes, bought in the markets when things were cheap and sold when they were dear, and lent to the people at three in the hundred a month. The penalty for breaking the grips was death. When the governor of Jingzhou told him that the state had stretched its six grips over the mountains and the marshes and that the people were bandits because of the taxes, he lost his office.",
      sima: { text: "He named his authorities himself: the Rites of Zhou has the deferred loan and the Yueyu the five levels of price, so he was opening the loans, stretching the levels and setting the grips, to even out the masses and cut off appropriation. By 17 CE he levied, on top of everything else, an exaction on everyone from the Highest Duke down who held slaves: thirty-six hundred cash a head. Then the record lets the empire answer. Envoys sent out to proclaim an amnesty to the bandits came back and reported that the bands had dispersed and then come together again, and that asking why, they all said the same thing: the prohibitions are so many that a man cannot lift his hand, a day's work does not cover the imposts, and shutting your door on yourself is still a crime if a neighbour casts coin. Mang was furious and dismissed them; those who said instead that the people were arrogant and should be killed, or that it was the turn of the age and the bandits would perish shortly, were pleased with and promoted. The one frank inventory in the book is made by an old general, Gongsun Lu: the Teaching Master of the State who had inverted the Five Classics and made the scholars unsure, the two men who built the land law and set the empire off the plough, the setter of the six grips who squeezed the artisans and the traders, the flatterer who kept the people's case from the throne — execute these few, he said, and comfort the empire; and the New's trouble is not on the steppe but inside its own borders. Mang was furious, had him led out, and then took part of what he said: the man who set up the grips was demoted to a frontier garrison, and the chapter gives its own reason — the people were resenting the monopolies, the monopolies were not that one man's work, and the emperor meant to shift the blame he was sitting under.", source: "Hanshu, juan 99 lower", tag: "history" }
    },
    {
      art: "panels/han09/14-red-eyebrows.png", ratio: 0.8, size: "std",
      caption: "The first rising of the famine years was started by a woman. Her son was a clerk of Haiqu and the county magistrate killed him for a small offence, so she broke up her family's wealth, sold wine, bought knives and crossbows with the money, got a hundred and odd poor young men behind her, took the county, killed the magistrate and offered his head on her son's grave; the bravest of them called themselves the Fierce Tigers. Some years later the starving of Qing and Xu brought out the man history remembers: Fan Chong raised a hundred and odd men and reached ten thousand inside a year, and the armies sent against him could not beat them.",
      bubbles: [
        { who: "shizhe", name: "The envoys sent to pardon the bandits", side: "left", text: "We asked them why they had come together again, and they all said the same thing: the prohibitions are so many that a man cannot lift his hand." }
      ],
      sima: { text: "The Book of the Later Han's notice on Fan Chong's band is the refutation of everything later ages put on top of it: they were bandits because they were desperate, and had no plan for taking cities or holding ground; when their numbers grew they made themselves one rule, that whoever kills a man dies and whoever wounds a man pays for the wound, kept by spoken word, with no documents, no banners, no formations and no orders of battle; the senior title among them was the village one, Third Elder. They painted their eyebrows red only because they were afraid of telling their own men apart from Wang Mang's in a battle, and that is the sole reason for their name. When the Grand Tutor Wang Kuang and the Renewing General Lian Dan were sent east against them, it rained at the farewell outside the gate until their clothes were soaked through, and the old men watching said: this is called weeping over an army. Their armies plundered wherever they went, and the people of the east made a rhyme about them: rather meet the Red Eyebrows than the Grand Tutor; the Grand Tutor is still bearable, the Renewing General kills us.", source: "Hou Han shu, juan 11, memoirs of Liu Xuan and Liu Penzi", tag: "history" }
    },
    {
      art: "panels/han09/15-the-empty-treasury.png", ratio: 0.8, size: "std",
      caption: "He answered the collapse with numbers and with names. The calendar was rebuilt on a cycle of thirty-six thousand years, so that the era was to be changed every sixth year, and the Renewal-of-Year general officer was re-created to match the mandate-texts, because, as the book says, it was meant to dazzle the common people and dissolve the bandits — and the crowd laughed. He set up five supreme commander offices and a paper order of battle of thirteen and a half million men, and the postal envoys criss-crossed the commanderies ten a day with no stored grain to issue them, so that horses were taken off the road out of the peasants. And he pulled down ten-odd imperial parks to fire their tiles for a nine-temple complex whose main hall was forty zhang on each side and seventeen zhang high; the labourers who died were counted in tens of thousands.",
      sima: { text: "The famine policy works on the same principle as the coin. Grain was dear, so he built a great granary and named it, hoping to press the price down by the name and the presence; tens of thousands of refugees came west into the pass, the officers appointed to feed them and the clerks stole the ration, so that seven or eight in every ten of them died. When a man sent out to buy grain came back with a bowl of rice and lamb soup from the market and answered the emperor's question about the people's condition by saying that the townspeople's food was all like this, the book's four-word ending is: Mang believed it. He dyed his beard and hair black, and in the same season took a new empress at a bride-price of thirty thousand catties of gold; that same day a great wind tore the roofs off and snapped the trees, and the ministers came forward and proved that the wind was an omen of the empress's virtue. When at last he sent nine generals east with the northern army's best men, there were still sixty chests of ten thousand catties of gold apiece standing in the palace, and the book's point is that he clung the tighter to it: he gave each man of the Nine Tigers four thousand cash and took their wives into the palace as hostages, and the soldiers were resentful and had no will to fight. And the scholar who had written his ceremonies, his own Teaching Master of the State, took his life with a general of the guard after a plot against him; Mang hated the scandal of an inner quarrel and hid the manner of their deaths.", source: "Hanshu, juan 99 lower", tag: "history" }
    },
    {
      art: "panels/han09/16-kunyang.png", ratio: 0.571, size: "full",
      caption: "The army raised to crush the east mustered at Luoyang in the summer of 23 CE: the Book of the Han calls it a million under arms and four hundred and twenty thousand arrived, the treasury emptied to send it out with jewellery and fierce beasts along, so that the eastern provinces would see how rich the state was and be frightened. Inside Kunyang there were eight or nine thousand men; the relieving column Liu Xiu led out counted a thousand and odd horse and foot, and three thousand chosen men were pushed in beside the water. The siege was several tens of layers deep, and the city's offer of surrender was refused.",
      bubbles: [
        { who: "wangyi", name: "Wang Yi", side: "right", text: "An army of a million, wherever it passes, should wipe everything out. Now we take this city, march on through blood, singing ahead and singing behind — is that not pleasant?" }
      ],
      sima: { text: "The two books disagree about the odds and agree about the weather. The Book of the Han has the court call up a million, recruit sixty-three schools of writers on military method as staff, and muster four hundred and twenty thousand at Luoyang; the Book of the Later Han keeps those figures, gives the city at eight or nine thousand, the attack force at a thousand and odd and the storming party at three thousand, and adds that when Mang's troops reached the walls they numbered nearly a hundred thousand and Liu Xiu very nearly did not get out. Neither book says a million were beaten by a handful, and both put the breaking in the same place, in the order. Wang Yi refused Yan You's advice twice — first to hurry on the pretender's capital at Wan and let the cities fall by themselves, then to leave one side of the ring open so that the besieged could run, the military classic's rule, ku bi wu zhui, bei wei kai men: do not press a cornered foe, open a way out for a city under encirclement. The field commander rode out with ten thousand and odd to meet the relief, ordered every other camp to stay where it was and not move, lost the fight, and the mass was not allowed to help each other. Then the sky-wind came: the Book of the Han has the rain fall like water poured and the great host break and scream; the Book of the Later Han has the thunder-wind tear the tiles off, the Zhi river rise, and the drowned counted in tens of thousands until the water would not run.", source: "Hanshu, juan 99 lower; Hou Han shu, juan 1 upper, Annals of Emperor Guangwu", tag: "debated" }
    },
    {
      art: "panels/han09/17-the-terrace.png", ratio: 0.571, size: "full",
      caption: "In the tenth month of 23 CE the troops came in by the Xuanping gate, the way the people called the gate of partings; a crowd of young men of the city set fire to the workshop gate and shouted at the tyrant to come down and surrender, and the fire ran into the consorts' quarters — where the woman who lived there was his daughter, the Han's empress, who had been given a new title under the New and had refused to wear it. He went out to the terrace in the palace lake with his mandate documents and his bronze Dipper still hugged in his arms, with a thousand and odd of his officers following, meaning to make a stand behind the water. A palace woman told the soldiers where he was.",
      bubbles: [
        { who: "wangmang", name: "Wang Mang", side: "left", text: "Heaven produced the virtue that is in me. What can the troops of Han do to me?" }
      ],
      sima: { text: "The book stages the last day exactly. He wore his dark-blue ceremonial robe, had the seal and the tassel at his belt and the dagger of the emperor Yu in his hand, while an astronomer pressed his divinator's board in front of him and turned with the hours; he turned his seat about so as to follow the handle of the Dipper, and said the line out of the Analects, and Ban Gu adds the plain fact underneath the quotation: by then he was not eating, his breath was short and he was spent. The arrows gave out, then they came to each other with short blades; when the soldiers reached the platform a merchant of the city took the seal-tassel off the body and a commandant of Donghai cut off the head. The soldiers took the body apart at the joints and cut up the flesh, and killed each other over the pieces. The day before, on the flatterer's advice that a state in calamity should weep to turn it aside, he had taken his ministers to the southern suburb, recited the whole history of his mandates to Heaven, asked why the rebels were not destroyed and whether, if he were not the right man, the thunder would not strike him; then he beat his own chest and wept until his breath gave out, and wrote a document to Heaven of more than a thousand words telling out his own services. The students and small people were assembled to weep at dawn and dusk and were given porridge: whoever was mournful enough, or could recite the document, was made a page, and there were more than five thousand of them. The head went south to the market at Wan and hung there, and the people took it up and struck it, and some cut out the tongue and ate it. The common people dug up the graves of his wife and his sons and his fathers, and burned his coffins and the nine temples — the nine temples his own labourers had built.", source: "Hanshu, juan 99 lower; juan 97 lower, Biography of the Empress of Ping", tag: "history" }
    },
    {
      art: "panels/han09/18-the-verdict.png", ratio: 1.75, size: "wide",
      caption: "Ban Gu wrote the life a generation after the man died, out of the court's papers, and his verdict is the one this page is built on: Qin burned the Odes and the Documents in order to set up its own opinions; Wang Mang recited the Six Arts in order to embroider his wicked words; they came to the same end by the same road, and both to destruction. The Treatise on Food and Money gives the arithmetic underneath it — before Mang was killed, the empire's households and mouths were halved — and closes the business with a date-stamp: four years after the levy of the Pig-Rushing Band the Han troops killed Mang, and two years after that the restored dynasty washed away the vexing and the harsh, struck the five-zhu coin again, and began afresh with the world.",
      sima: { text: "Two things the record does not say. It does not say that he poisoned the child emperor Ping: that the Han's troops were saying so at the end is entered in his biography as what the other side claimed. And it does not pretend the man was hated from the beginning, or that he was a simple monster: Ban Gu explains the rise as the four regents' inherited power plus the Han's middling fortune, three breaks in the succession, and an empress-dowager who lived long enough to be the family's own head, and closes that this was the turn of the times and not a thing got by human effort. The treatise adds the same thing about the fall in six words: with the institutions out of the middle, officials and people were both exhausted. What fell was not a tyrant but an edited state: the eleven dukes renamed three times in ten years, the seven hundred and ninety-six enfeoffed with no fiefs, the officers with no salaries, the money changed five times in eight years, and a court that spent its last year on paper, in sorcery, in weeping, and in the correct spelling of its own titles. The men who came after him did not debate the reform. They put the old coin back.", source: "Hanshu, juan 99 lower, Ban Gu's eulogy; juan 24, Treatise on Food and Money", tag: "commentary" }
    }
  ],
  myths: [
    {
      myth: "Wang Mang was a Chinese socialist a thousand years early: state land, state monopolies, price control and planned credit.",
      truth: "This is a twentieth-century reading — Hu Shi made it explicitly in the 1930s — and the laws name their own model, which is not a ministry of planning but the Rites of Zhou: the well-field of Yu, the Zhou officer who bought up unsold goods, the five levels of price in the Yueyu, the loan against interest for funerals and sacrifices. Ban Gu's character note is decisive: he could not start a single thing without first finding a line of scripture to authorise it. And a coin table that prices a tortoise at two thousand one hundred and sixty cash against gold at ten thousand cash a catty is a ritual ordering of precious things, not a budget. It was not egalitarian either: the land law took nothing from a household of eight or fewer male mouths, and its author withdrew it in the fourth year after one officer's memorial.",
      source: "Hanshu, juan 99 middle; juan 24, Treatise on Food and Money"
    },
    {
      myth: "He was a plain tyrant of the stock type: a monster whose frugality was an obvious lie and whose family life was the usual massacre.",
      truth: "The severity fell on his own house first and the record keeps it. His second son Huo killed a slave, and Wang Mang reproached him and made him kill himself for it, at the marquisate, while he was himself under a sentence of political dismissal; his wife met the wives of the marquises in a cloth knee-cover and a skirt that did not drag, and the guests took her for a servant; by the end his wife had gone blind weeping because he kept killing his sons, a son was given poison and stabbed himself rather than drink it, and four funerals passed through the palace inside a month and ten days. Ban Gu credits him with none of this — his verdict is that the man hid what he felt in order to get a name — but the frugality was real and the empire was still starved, which is the harder thing the record is willing to say.",
      source: "Hanshu, juan 99 upper and lower; juan 97 lower"
    },
    {
      myth: "The Yellow River changed its course and the New dynasty drowned in it.",
      truth: "The breach at Wei commandery in 11 CE is in the biography, together with the emperor's reason for not closing it: his ancestral tombs were at Yuancheng, he had dreaded the water reaching them, and when the river went east away from the graves he let it run. But the book's order of events is the opposite of the environmental reading. The breach comes in 11 CE and the first mass risings in 17 CE; between them sit the money changes, the slave and land law, the six grips at the mountains and marshes, and the thirty-six hundred cash a head on households holding slaves. When the emperor's own envoys came back and reported why the bands kept re-forming, they quoted the bandits and not the river: the prohibitions were so many that a man could not lift his hand, and shutting the door on yourself was still a crime if your neighbour cast coin.",
      source: "Hanshu, juan 99 middle and lower; juan 24, Treatise on Food and Money"
    },
    {
      myth: "The Red Eyebrows were a programmed peasant army, with a manifesto, a banner and a theory of the state.",
      truth: "The memoir says the reverse in as many words. They were bandits because they were desperate and had no plan to take cities or hold ground; their entire code was two clauses — a killer dies, a wounder pays for the wound — held by spoken word, with no documents, no banners, no formations and no commands; their senior title was the village title Third Elder; and the red paint on their eyebrows was adopted on the eve of a battle so that they could tell their own men from Wang Mang's soldiers, which is the only reason they have a name at all. They grew because the famine and the law made them grow, ten thousand and odd in a year. The first band of the famine years was raised by a woman who sold wine to buy crossbows so that she could kill the magistrate who had executed her son.",
      source: "Hou Han shu, juan 11, memoirs of Liu Xuan and Liu Penzi; Hanshu, juan 99 lower"
    },
    {
      myth: "Guangwu took Kunyang with ten thousand and smashed a million by a genius's surprise attack, with heaven visibly on his side.",
      truth: "The odds are the historians' own and they do not match. The Book of the Han calls the mobilisation a million and reports four hundred and twenty thousand mustered at Luoyang; the Book of the Later Han keeps both figures, gives eight or nine thousand in the city, a thousand and odd in the relieving column and three thousand at the water — and then adds the meteorite in the camp, the cloud that fell and scattered a foot above the ground, and the drowned tens of thousands that stopped the river running. No early text has ten thousand against a million, and the romances of the restoration, which supply the chivalric pursuit-and-flight version everybody knows, are Ming and Qing books and not evidence. What the records credit is a strike on a stationary ring: the besiegers were ordered not to move from their camps while their commander fought with ten thousand, they could not help one another, and a mass of conscripts held together by the army-marshal's law broke in the rain.",
      source: "Hou Han shu, juan 1 upper, Annals of Emperor Guangwu; Hanshu, juan 99 lower"
    }
  ],
  sources: [
    { title: "Book of the Han (Hanshu)", author: "Ban Gu, finished by Ban Zhao", date: "1st c. CE", detail: "juan 99 upper: the nine marquisates and five Grand Marshalships, the poor relation's reputation, Kong Xiu's broken sword, the son who killed a slave, the regency's titles and his own resume of five favours, the blood thrown on his own gate, the copper casket and the accession. juan 99 middle: the king's fields and private retainers, Ou Bo and the repeal, the twenty-eight coin denominations, the Eleven Dukes renamed three times, the Xiongnu expedition and the four-tenths confiscation. juan 99 lower: the six grips and the thirty-six hundred cash a head, the paper order of battle of thirteen and a half million, Gongsun Lu's indictment, the Nine Tigers and the chests of gold, Kunyang, the terrace, the head at Wan, and Ban Gu's judgment on the man who recited the Six Arts." },
    { title: "Book of the Han (Hanshu), Treatise on Food and Money", author: "Ban Gu", date: "1st c. CE", detail: "juan 24: the coin table of five materials, six names and twenty-eight items, the graphological argument that the Liu character contains gold and knife, the ban on holding the five-zhu, the cloth money worth twenty-five and the round coin worth one, the five-household implication for private casting, the cage-carts sent to the treasury at Zhongguan with six or seven in ten dying of grief, the total of over two thousand eight hundred million five-zhu pieces struck since 118 BCE, and the two sentences this episode turns on: every change of money broke people's livelihoods, and the empire's households and mouths were halved before Mang was killed." },
    { title: "Book of the Han (Hanshu), frontier and imperial-women biographies", author: "Ban Gu", date: "1st c. CE", detail: "juan 94 lower, Biography of the Xiongnu: the seal re-cut from the word for imperial seal to the word for tally, the old seal broken with an axe, the chanyu's connoisseur's protest, and the fifteen chanyus that were never delivered. juan 96 lower, Biography of the Western Regions: the three hundred and seventy-six officers wearing Han seals, the killed protector, the destroyed column, and the cutting-off of the Regions. juan 98: the Grand Empress Dowager, the throwing of the transmission seal, and the Ritual Mother. juan 97 lower: his daughter, the title she refused, and the fire she went into." },
    { title: "Book of the Later Han (Hou Han shu)", author: "Fan Ye", date: "5th c. CE", detail: "juan 1 upper, Annals of Emperor Guangwu: Kunyang's figures, the city's eight or nine thousand, the thousand and odd and the three thousand, the thunder-wind and the Zhi river, and the marvels filed after the victory. juan 11: the memoirs of the secessionist pretenders, for Mother Lü's revenge at Haiqu and the Fierce Tigers, for Fan Chong's rule of two clauses and the absence of documents and banners, and for the painted eyebrows. juan 87, Memoir of the Western Qiang: how the Western Sea commandery was got out of the Qiang through their interpreters, and recovered by them after the New fell." },
    { title: "The Cambridge History of China, Vol. 1: The Ch'in and Han Empires, 221 BC–AD 220; and Light against Darkness: The Beginnings of the Later Han Dynasty", author: "ed. Denis Twitchett and Michael Loewe; Rafe de Crespigny", date: "1986; 1981", detail: "Modern English-language work, used for the chronology of the regency years and the dating of the 8 CE versus 9 CE accession question, for the administrative machinery the edicts had to run through, and for the years 23 to 36 CE, when the record of the restoration has to be read against the announcements it was written to justify." }
  ]
};
