window.HAN04 = {
  id: "han-04",
  dynasty: "Han",
  order: 4,
  title: "The Road Bored Open",
  subtitle: "Longxi to the Oxus, 138 BCE",
  readMinutes: 7,
  hook: "A palace officer volunteered for a mission to a people no Han man had reached, was held by the Xiongnu for more than ten of the thirteen years he was gone, reached the Oxus and failed to get an alliance there at all — and the geography he brought back turned the empire's west into a road.",
  heroAlt: "A small party of riders and pack animals crossing a wide dune sea at the foot of a low mountain range, one man in the centre holding upright a long staff with three bundled tufts at its head, the morning light flat and pale, deep indigo ridges on the far horizon and no wall, no camp and no road anywhere in the frame",
  people: [
    { name: "Zhang Qian", role: "An imperial attendant of Hanzhong who answered an advertisement for a man who could get there. Captured on the way out and again on the way back, gone thirteen years in all and more than ten of them in Xiongnu hands, he reached Ferghana, the Yuezhi, Bactria and Kangju and brought back the west as information." },
    { name: "Tangyi Fu", role: "A Xiongnu-born slave of the Tangyi household who went with him as guide and bowman and kept the party fed by shooting game when the rations gave out. One of the two men, out of over a hundred, who came back." },
    { name: "Emperor Wu", role: "Liu Che, emperor of Han: not yet twenty when the mission went out, and still on the throne when the road it opened had taken two armies and most of the men in them. He asked the questions Zhang Qian answered, believed the answers, and spent the treasury on them." },
    { name: "Junchen", role: "Chanyu of the Xiongnu, who caught the envoy at the frontier and saw no reason at all to let him through — and who kept him for over a decade, gave him a wife, and never got the Han staff out of the envoy's own hand." },
    { name: "Kunmo", role: "Kunmi of the Wusun, the horse-lords of the Ili valley whom the second mission was sent to move east. He was old, his kingdom was split three ways, and his ministers were afraid of the Xiongnu; he took the gifts and did not move." }
  ],
  panels: [
    {
      art: "panels/han04/00-cover.png", ratio: 1.75, size: "wide",
      caption: "138 BCE, by the reckoning. Out of Longxi, a hundred-odd men and a staff with three tufts on it, walking into a steppe held by the one power the empire could not fight.",
      sima: { text: "This line is told only from the official histories: the memoir of the peoples of the west in the Records of the Grand Historian, the Book of Han's memoir of Zhang Qian and Li Guangli and its treatise on the Western Regions, and the Book of the Later Han's own Western Regions chapter for what came after; the Zizhi Tongjian where it collects them. No novel, film or game is a source for a panel, and the phrase Silk Road is a nineteenth-century coinage, which is dealt with at the end.", source: "On our sources", tag: "note" }
    },
    {
      art: "panels/han04/02-the-skull-cup.png", ratio: 0.8, size: "std",
      caption: "It started with a question asked of prisoners. Defectors from the Xiongnu told the young emperor that the Yuezhi's king had been killed and his head made into a drinking cup, and that the people who were left still wanted revenge and had nobody to do it with.",
      sima: { text: "The emperor was asking, the record says, because Han was set on destroying the Hu and this was the intelligence worth having. The memoir's own entry on the Yuezhi says where the cup came from: it was the Laoshang Chanyu, Modu's successor, who killed the Yuezhi king and made his skull into a drinking cup, after which the Yuezhi went far away, past Ferghana, and struck down the people of Daxia and settled on their land — the ones the Han envoy was sent to find. Neither history dates that killing, and the Yuezhi's old pasture between Dunhuang and the Qilian mountains is named only as what they lost. What the court did with such a report is stated flatly in the memoir: any road to the Yuezhi ran through Xiongnu country, so it advertised for a man who could get there. A palace attendant from Hanzhong named Zhang Qian answered the call.", source: "Shiji, juan 123, Memoir of the Peoples of the West; Shiji, juan 110, Memoir of the Xiongnu; Hanshu, juan 61, Memoir of Zhang Qian and Li Guangli", tag: "history" }
    },
    {
      art: "panels/han04/03-the-road-goes-through.png", ratio: 1.75, size: "wide",
      caption: "The whole plan was one sentence long and it had a hole in it. Any road to the enemy of the Xiongnu ran through the Xiongnu. He went out of the Longxi frontier with a Xiongnu-born servant for a guide and a hundred-odd men, and was taken at once.",
      bubbles: [
        { who: "junchen", name: "Junchen Chanyu", side: "right", text: "The Yuezhi lie to my north. How is Han to send an envoy through my land? If I sent one to the Yue in the south, would Han let him pass?" }
      ],
      sima: { text: "The Chanyu's retort is the plainest statement of the geography of the age in either history, and it is in both. Then the sentence that decides the shape of the story: he was held ten-odd years, given a wife, had a son, and never let go of the Han credential. The histories give no year for the departure at all, and date the return only by the length of the absence, thirteen years. The Zizhi Tongjian places the whole story as a background note at the return, in the third year of Yuanshuo, 126 BCE, which is why the start is put at 139 or 138 BCE. Neither the 138 nor the 139 is the source's own dating.", source: "Shiji, juan 123; Hanshu, juan 61; Zizhi Tongjian, scroll 18", tag: "debated" }
    },
    {
      art: "panels/han04/04-ten-years.png", ratio: 0.8, size: "std",
      caption: "Ten-odd years in the steppe, growing familiar. His captors stopped watching him closely, and he went — not back the way he had come, but on, west, for what the record measures as tens of days of riding.",
      sima: { text: "The memoir says he slipped away west towards the Yuezhi with his own followers, and reached Dayuan, Ferghana, after some tens of days of riding. What filled the decade is not described; that he was trusted enough to be given a wife, and that the men of the steppe liked him, is as much as the record says, and it notes separately that Zhang Qian was a strong man, generous and trustworthy, and that the barbarians loved him for it. Tangyi Fu, the servant who had set out with him, is credited with keeping the party alive: a Xiongnu man and an excellent shot who, when there was nothing to eat, shot birds and beasts for the fire.", source: "Shiji, juan 123; Hanshu, juan 61", tag: "history" }
    },
    {
      art: "panels/han04/05-the-guide-chain.png", ratio: 1.75, size: "wide",
      caption: "Ferghana had wanted the Han's goods and had never managed to reach them. It asked one question — where are you trying to get to — and then provided what the Han could not: guides and interpreters, and a hand-off to the next kingdom, and the next.",
      bubbles: [
        { who: "zhangqian", name: "Zhang Qian", side: "left", text: "I am the Han's envoy to the Yuezhi, and the Xiongnu closed the road on me. I have got away. Send a man to conduct me on, and if I reach them and come back to Han, what Han will send you will be more than can be counted." }
      ],
      sima: { text: "The exchange is in both histories: the king of Dayuan had heard of Han's wealth and wanted the contact but could not get it; so he believed the envoy, sent him forward with conductors and interpreters to Kangju, and Kangju passed him on to the Great Yuezhi. This is the first recorded instance in the Chinese sources of the mechanism that would run the road for the next century: a chain of states, each providing the guide and the interpreter for the next stage. It is also the reason his report on Ferghana is so exact — he was its guest, and it wanted the trade.", source: "Shiji, juan 123; Hanshu, juan 61", tag: "history" }
    },
    {
      art: "panels/han04/06-no-grip.png", ratio: 0.8, size: "std",
      caption: "The alliance he had crossed half of Asia for was not available. The Yuezhi had pushed down the people of Bactria and were living on them: fat land, few robbers, settled trade, and a very clear view that the Han was far away and revenge was not on the table.",
      sima: { text: "The record of the refusal is a piece of political analysis rather than a snub: the Yuezhi's own king had been killed by the Hu and his heir set up in his place — the Book of Han says it was the dead king's wife who was made queen, a variant the Shiji does not carry — and having made the people of Daxia serve them and settled on their land, they were content, thought themselves far from Han, and had no wish at all to be avenged on the Xiongnu. Zhang Qian stayed with them over a year and, in the memoir's phrase, never got the handle of the matter. Everything the mission was for was written in that failure.", source: "Shiji, juan 123; Hanshu, juan 61", tag: "debated" }
    },
    {
      art: "panels/han04/07-only-two-returned.png", ratio: 0.571, size: "full",
      caption: "He took the long way home along the edge of the Tibetan plateau, through the Qiang pastures, to avoid the Xiongnu. The Xiongnu were there. A year or so later there was a succession war in the steppe empire, and he rode out of it with his wife and his guide — out of more than a hundred men who had left, and after thirteen years, two came back.",
      sima: { text: "The return is in the same two sentences in both books: going down along the southern range and trying to come out through the Qiang, he was taken by the Xiongnu again; held again for about a year; then the Chanyu died, and the Worthy King of the Left Guyli made war on the heir and took the title for himself — the Book of Han leaves that prince unnamed and says only that the country fell into disorder — and in that disorder Zhang Qian got home — with his Xiongnu wife and Tangyi Fu, and with nothing said about the son born to him there. The court made him Grand Master of the Palace, and gave his companion the title Lord Who Bore the Mission — a title, not a marquisate. Then comes the number that the historian sets down for the whole affair, and it is the only one of its kind in the chapter: when Zhang Qian set out there were a hundred-odd men with him, he was gone thirteen years, and only two of them came back.", source: "Shiji, juan 123; Hanshu, juan 61; Zizhi Tongjian, scroll 18", tag: "history" }
    },
    {
      art: "panels/han04/08-what-he-brought-back.png", ratio: 0.8, size: "std",
      caption: "What he gave the emperor for the thirteen years was a set of answers: which peoples had walls and fields, which had horse-lords and herds, how many cities each held, and how far they were. Ferghana had a wine nobody had heard of, and horses whose sweat ran red.",
      sima: { text: "The report is given as a list of places with their distances and their economies: Dayuan, said to be ten thousand li from Han, settled, ploughing rice and wheat, pressing grape wine, with walled houses, seventy-odd towns great and small and a population of some hundreds of thousands, and good horses which sweat blood, the offspring, the record says, of heavenly horses. He named the neighbours too: Kangju and Wusun and Yutian, the wandering ones and the settled ones, and to the east the salt marsh. He himself had seen four kingdoms — Ferghana, the Yuezhi, Bactria and Kangju — and reported five or six more at second hand. The wine and the alfalfa are the two crops the memoir says came back east out of it.", source: "Shiji, juan 123; Hanshu, juan 96a, Treatise on the Western Regions", tag: "history" }
    },
    {
      art: "panels/han04/09-the-two-rivers.png", ratio: 1.75, size: "wide",
      caption: "He also brought back a theory of the continent: west of Khotan every river runs into the west sea, east of it every river runs into the salt marsh; the marsh has no inlet and no outlet, so it goes underground — and comes up south of it as the Yellow River.",
      sima: { text: "The Han treatise on the Western Regions states the same hydrography and adds the measurements: the marsh, also called the Pool of Puchang, lies three or four hundred li across and a little over three hundred li from the Jade Gate and the Yang Gate, its water standing still, neither rising in summer nor falling in winter; and the common view, the treatise says, was that it travelled beneath the ground and came out again in the south, at the Jishi hills, as the river of China. Han envoys went on to trace the upper course and found jade-bearing mountains at the source, and the emperor checked his old books and named that mountain Kunlun. Sima Qian, who had the envoy's report in front of him, would not have the legend: since Zhang Qian traced the river's source, he writes, where is this Kunlun of the old records that anyone has seen? As for the monsters of the Classic of Mountains and Seas — I do not dare to speak of them.", source: "Hanshu, juan 96a; Shiji, juan 123", tag: "commentary" }
    },
    {
      art: "panels/han04/10-shu-cloth-in-bactria.png", ratio: 0.8, size: "std",
      caption: "The best discovery in Bactria was not on his inventory. In a market on the Oxus he saw a walking-staff of Qiong bamboo and cloth of Shu, and asked where they got them — and the answer, some traders bring it from the south-east, told the emperor something no scout had: there was a way to India out of the empire's own south-west, and nobody had walked it.",
      bubbles: [
        { who: "zhangqian", name: "Zhang Qian", side: "left", text: "I saw Qiong bamboo staves and Shu cloth in Daxia. Their merchants had bought them in Shendu. If Shu cloth gets there, Shu is not far from Shendu — and the road from Shu is short and has no Xiongnu on it." }
      ],
      sima: { text: "The inference and its consequence are in the memoir. Han sent secret missions out of Shu and Jianwei on four routes — by the passes of the Mang, the Ran, the Xi, and of the Qiong and Bo — each pushing a thousand or two thousand li, and the northern ones were closed by the Di and Zuo, the southern by the Xi and Kunming, who had no lords, liked raiding, killed the envoys and took what they carried, so that nothing got through. But they heard that a thousand-odd li further west there was an elephant-riding country called Dianyue, and that Shu traders who had slipped out on their own had reached it; and in that way, the record says, Han came to know the kingdom of Dian while looking for a road to Daxia. The Tongjian, following the same account, keeps the arrival at Dian: the king of Dian asked the Han envoys which was the greater, Han or his own country — and the lord of Yelang asked the same question.", source: "Shiji, juan 123; Hanshu, juan 61; Zizhi Tongjian, scroll 19", tag: "history" }
    },
    {
      art: "panels/han04/11-the-second-mission.png", ratio: 1.75, size: "wide",
      caption: "He lost his marquisate for arriving late with a relief column and was back in the ranks as a common man. What he sold the emperor next was the plan that had always been the point: buy the horse-lords of the Ili valley, settle them on the ground the Xiongnu had just lost, and cut off the steppe empire's right arm.",
      bubbles: [
        { who: "zhangqian", name: "Zhang Qian", side: "right", text: "The Son of Heaven's gifts are presented to you. If you will not kneel to receive them, they go back." }
      ],
      sima: { text: "The second mission is the most extravagantly documented embassy of the age: a colonel of the palace guards with three hundred men, two horses apiece, cattle and sheep beyond counting, gold and silk goods worth tens of millions in cash, and a crowd of subordinate envoys each carrying a credential, to be detached to whatever country they passed. The memoir dates it by sequence and not by year: it follows the Xiongnu loss of the Hexi corridor in 121 and the battle north of the steppe in 119, which is why the mission is put at 119 BCE. The Wusun king received him on the model of the Chanyu's court, which is why the exchange over the gifts quoted above happens. It changed nothing else: the kingdom was divided in three among an old king, a rival prince with ten thousand horse and a grandson with another ten thousand, and the ministers, who had lived under the Xiongnu and feared them, would not hear of moving. He got no decision.", source: "Shiji, juan 123; Hanshu, juan 61; Hanshu, juan 96b", tag: "history" }
    },
    {
      art: "panels/han04/12-deputy-envoys.png", ratio: 0.8, size: "std",
      caption: "The failure was made to work anyway. He sent his deputies out from the Ili valley in every direction at once — Ferghana, Kangju, the Yuezhi, Bactria, Parthia, India, Khotan — and after a year or so they came back with their counterparts, and the west began to answer to Chang'an.",
      sima: { text: "The record of the end is one line — he was made Director of Ceremonies, ranked among the nine ministers, and died a year or so later. Then comes the verdict the episode is named for. Sima Qian's judgement of the man is a single image in two characters, bored a hole through — the sense is of driving a tunnel through rock — and the sentence that follows it says that after Zhang Qian, every envoy going west went under the name of the Marquis of Bowang to get standing among the foreign states, and that it was by that name they were believed. The Wusun's own first return party came with a handful of envoys and some tens of horses to see how big Han was, and went home reporting crowds and wealth; the treatise notes that the country then set more store by Han than before.", source: "Shiji, juan 123; Hanshu, juan 61", tag: "history" }
    },
    {
      art: "panels/han04/13-the-caravans.png", ratio: 1.75, size: "wide",
      caption: "What boring a hole produced was traffic: hundreds of men a party, five or six or a dozen-plus parties in a year, some gone eight or nine years; and on the far end, hosts that were getting tired of the visitors and had worked out that the Han army was not coming.",
      sima: { text: "The statistics are in both histories and are the nearest thing the sources have to a ledger of the road: an embassy of the great days was several hundred men, the smallest still a hundred; in a year the court sent ten-odd dispatches or five or six; the goods each carried were modelled on what Zhang Qian had taken. The memoirs then state the friction without embarrassment: the envoys were poor men's sons who had pocketed their state-issue goods and wanted to sell them cheap abroad; the western countries grew sick of Han envoys whose stories varied from one man to the next, calculated that Han's troops could not arrive, and withheld their food to make the visitors suffer; Han envoys ran short, and quarrelled and came to blows among themselves. Loulan and Gushi, astride the empty stretch, robbed them outright and killed them, until a marquis with seven hundred light horse rode in and took Loulan's king. After that the beacon towers ran from Jiuquan to the Jade Gate.", source: "Shiji, juan 123; Hanshu, juan 61; Hanshu, juan 96a", tag: "history" }
    },
    {
      art: "panels/han04/14-the-headache-mountains.png", ratio: 0.8, size: "std",
      caption: "Half of the road was written off by the men who had to walk it. There is a pass in the Karakoram where the way is a foot and a half or more wide for thirty li over a drop with no bottom in sight, and men and beasts pulled across on ropes.",
      sima: { text: "The description is in the Book of Han's Western Regions treatise, and it is an argument against going: when Chengdi's court wanted to send an envoy back to the kingdom of Jibin beyond the Suspended Crossing, Du Qin, adviser to the Grand General Wang Feng, read out what the road actually cost, and the Grand General reported his advice to the throne and it was taken. Out beyond Pishan lie the Greater and Lesser Headache Mountains, the Red Earth and the Fever Slope, where travellers turn bright red with heat or are sick with headache and the pack animals die of it; then the Three Pools and the Rock Slope, the track one chi six or seven cun wide running thirty li along the edge of a precipice, horsemen and porters clinging to one another and hauling each other with cords, two thousand li to the place called the Suspended Crossing — where a beast that falls is dashed to pieces before it reaches the bottom, and a man who falls cannot be recovered at all. His conclusion: envoys carrying the strong Han's credential sit hungry in mountain valleys with nothing to beg, and after ten or twenty days their men and animals are left in the open country and never come back; the wise king attends to what is inside the nine regions and does not go looking for what is outside. Let the mission turn back at Pishan. Du Qin got his way — and the treatise then adds the reason Jibin kept coming anyway: it wanted the rewards and the market, and its envoys came once every few years.", source: "Hanshu, juan 96a, Treatise on the Western Regions", tag: "history" }
    },
    {
      art: "panels/han04/15-the-right-arm.png", ratio: 1.75, size: "wide",
      caption: "The steppe empire had its own western administration, and the Han's whole design was aimed at it: a Xiongnu prince of the western circuit with his own commandant of bond-servants, resident among the city-states, counting and taxing them. That office is what the horse-buying was for.",
      sima: { text: "The treatise says the city-states of the west, settled and walled and unlike the horse peoples, were all made to serve the Xiongnu, who taxed them and took what they needed, with a Commandant of Bond Servants set up by the Rizhu King of the Xiongnu's western border, the commandant himself lodged among Yanzhi, Weixu and Weili. The Han's counter-price is recorded in the same books and in the same plain words. When the Wusun asked for a Han marriage the court answered that the bride-price came first; the Wusun sent a thousand horses; and in the Yuanfeng years a daughter of the king of Jiangdu went out as a princess to be the Wusun ruler's Right Lady, while a Xiongnu woman was made his Left Lady. She built her own quarters, saw the old king once or twice a year, could not speak with him, and wrote a song: my family has given me away to the edge of the sky, lodged me with the king of the Wusun; felt is my house and the felt is my wall, flesh my food and mare's milk my drink; I ache for my old land and wish I were a yellow swan going home. The emperor pitied her and sent her a present every other year. When the king grew old he meant her to pass to his grandson; she objected, and the emperor's answer was: follow the custom of her new country, since we intend to use the Wusun to destroy the Hu.", source: "Hanshu, juan 96a and 96b; Shiji, juan 123", tag: "history" }
    },
    {
      art: "panels/han04/16-the-golden-horse.png", ratio: 0.8, size: "std",
      caption: "Ferghana did its own arithmetic about the Han and got it nearly right. Its advisers counted the deaths on the road and concluded that an army could not come; so they kept the horses the emperor wanted, and when the envoy in a rage smashed the golden horse he had brought as an offer, a noble of the court let him go — and had him killed on the road out.",
      sima: { text: "The reasoning is quoted in both histories: Han is far from us, and in the salt marsh their parties keep coming to grief; to the north of it are the Hu, to the south no water or grass; the towns give out and there is nothing to eat, and when Han envoys come in parties of several hundred they are always short of food and more than half of them die. How could they bring a large army? They can do us nothing. And the horses of the secondary city are Ferghana's treasure. A Han envoy, angry at the refusal, cursed the place and destroyed the golden horse the court had carried out for the purpose, and left. A Ferghana noble said the envoy had treated them with contempt; and the king of the eastern border town was sent to intercept him, kill him and take what he had. That is what started the war.", source: "Shiji, juan 123; Hanshu, juan 61", tag: "history" }
    },
    {
      art: "panels/han04/17-war-for-horses.png", ratio: 0.8, size: "std",
      caption: "The first expedition came back with scarcely a tenth of its men and was stopped at the Jade Gate with orders to cut down anyone who tried to ride in. The second one, with the empire's convict levies behind it, sat outside Ferghana's city for over forty days until the Ferghanans killed their own king and offered up his head and their best horses.",
      sima: { text: "The emperor's motive is not hidden in the record: among the reasons he made Li Guangli a general was that he wanted to ennoble his favourite concubine's family. The first campaign reached the western town of Yucheng with a few thousand starving men, was beaten there, and got back to Dunhuang with one or two in ten; hence the order at the Jade Gate. The second took sixty thousand men out of the garrison commanderies, with the convicts of seven categories of penalty, oxen by the hundred thousand, horses and donkeys and camels to match, and transport parties reaching in from the east; a further 180,000 garrison troops were posted north of Jiuquan and Zhangye to hold the line. Ferghana's outer town fell, water was diverted from under the walls, and the nobles killed King Wu Ga and sent his head out with the horses — the Han chose some tens of the best and drove off three thousand-odd of the middling stock, and of the army that came back through the Jade Gate there were a little over ten thousand men and a thousand horses. It took four years, and it is what made the western states come in.", source: "Shiji, juan 123; Hanshu, juan 61", tag: "history" }
    },
    {
      art: "panels/han04/18-the-verdict.png", ratio: 1.75, size: "wide",
      caption: "The road was not a road; it was a way of going, held open by an army and a treasury and closed again twice before the dynasty ended. Everything in the histories about it is measured in envoys, grains of tribute and men who did not come back.",
      sima: { text: "The Book of the Later Han states the two facts that the phrase about an open road tends to cover. Usurping Wang Mang made enemies of the western states; they broke with China and went back under the Xiongnu, and when the dynasty came back to the question the treatise dates the gap at sixty-five years. The road was picked up again in 73 CE and a Protector-General was first posted again the next year, but that officer was overwhelmed when Emperor Ming died and the post was left vacant under Emperor Zhang until 91 CE, when Ban Chao had settled the western states and was made Protector-General himself, and fifty-odd countries then sent sons in as hostages; later, after Emperor He died, the region revolted, the court judged the place too far and too dangerous to relieve, abolished the post of Protector-General, and from then the Western Regions were abandoned — with men at court urging the closure of the Jade Gate and the Yang Gate outright. Its other honest note is about the west's own account of itself: the envoys of Daqin, the land beyond the western sea, arrived at the court in 166 CE by way of the southern commandery of Rinan, claiming to come from a king called Andun; and the book adds that the tribute they brought had nothing rare about it, and that the ones who had carried the story had probably exaggerated.", source: "Hou Hanshu, juan 88, Memoir of the Western Regions; Hanshu, juan 96a", tag: "commentary" }
    }
  ],
  myths: [
    {
      myth: "Zhang Qian opened the Silk Road: a trade route in which Chinese silk crossed Asia to be sold in Rome.",
      truth: "The name is not ancient — Seidenstraße was coined by the geographer Ferdinand von Richthofen in 1877. What the histories call it is zao kong — boring a hole through — and the traffic they describe is state traffic: envoys carrying gold and silk goods worth tens of millions in cash as gifts and bribes, to buy alliances against the Xiongnu. Silk did move west — the Han envoys are caught privately selling the state's goods, and the Parthians are recorded buying and re-exporting — but the mission's purpose was encirclement, not commerce, and Rome is not in any of its reports.",
      source: "Shiji, juan 123; Hanshu, juan 61 and 96a; the name is modern"
    },
    {
      myth: "Zhang Qian brought the grape, the walnut, the sesame, garlic and the pomegranate into China.",
      truth: "The memoir names two plants coming back out of the west and does not attach them to Zhang Qian personally: grape and alfalfa, whose seed Han envoys collected, and which were then planted on the good ground around the imperial parks until they covered the view. The walnut, the sesame and the pomegranate are added by later books, which like to give an import a name and a date. Sesame in particular is argued from modern finds to have been grown in China well before the mission.",
      source: "Shiji, juan 123; Hanshu, juan 96a; the wider list is a later accretion"
    },
    {
      myth: "Zhang Qian, or one of his envoys, reached Daqin — the Roman empire — and opened direct relations with it.",
      truth: "The farthest named destinations in the reports are Tiaozhi and the western sea, and they are second-hand: the Book of Han puts Tiaozhi a hundred-odd days beyond the last state the Han reached, and says that going west by water from there you get somewhere near the setting of the sun. The Book of the Later Han states it plainly as a correction: earlier Han envoys all turned back at Wuyi and not one of them reached Tiaozhi. In 97 CE an officer of Ban Chao got to the shore and gave up when Parthian sailors told him the crossing could take three months with a fair wind or two years without, and that men died of longing on it.",
      source: "Hanshu, juan 96a; Hou Hanshu, juan 88, Memoir of the Western Regions"
    },
    {
      myth: "Once Zhang Qian opened it, the Silk Road stayed open for the next thousand years.",
      truth: "The records date the closures as carefully as the openings. Wang Mang's handling of the western states broke the relation, the Xiongnu took the taxing-post back, and the region was severed from China for the sixty-five years before Ban Chao. The post of Protector-General was then abolished a second time under Emperor An, and men at court proposed shutting the Jade Gate and the Yang Gate. What the Han built in the west was a garrison system — four commanderies, two passes, beacon towers, and farmer-soldiers at Luntai and Queli — and it ran only as long as the treasury paid for it.",
      source: "Hanshu, juan 96a; Hou Hanshu, juan 88"
    },
    {
      myth: "Zhang Qian spent thirteen years a prisoner in chains in the Xiongnu camp.",
      truth: "Thirteen years is the length of the absence, not of the captivity, and the record says he was not confined: he was held ten-odd years, given a wife, had a son, and grew familiar enough with his captors to slip away — and was taken a second time, for about a year, on the way home along the southern edge of the plateau. The two details that survive from the decade are the one the historian chose to keep: he never let go of the Han credential, and the staff he carried had an empire's use for it later.",
      source: "Shiji, juan 123; Hanshu, juan 61; Zizhi Tongjian, scroll 18"
    }
  ],
  sources: [
    { title: "Records of the Grand Historian (Shiji)", author: "Sima Qian", date: "c. 91 BCE", detail: "Juan 123, Memoir of the Peoples of the West: the missions, the report on Ferghana, Daxia, Anxi and Shendu, the bored-through judgement, the Dayuan wars; and its own closing refusal of the Kunlun legends. Juan 110 for the Xiongnu background." },
    { title: "Book of Han (Hanshu)", author: "Ban Gu, finished by Ban Zhao", date: "1st c. CE", detail: "Juan 61, Memoir of Zhang Qian and Li Guangli; juan 96a and 96b, Treatise on the Western Regions — the routes out of the Jade Gate and Yang Gate, the registers of households and able-bodied men, the Commandant of Bond Servants, the Suspended Crossing, Tiaozhi and the western sea, and Princess Xijun's song." },
    { title: "Book of the Later Han (Hou Han shu)", author: "Fan Ye", date: "5th c. CE", detail: "Juan 88, Memoir of the Western Regions: the sixty-five years of separation, Ban Chao, Gan Ying at the shore, the description of Daqin and the embassy of 166 CE which the book itself doubts." },
    { title: "Zizhi Tongjian", author: "Sima Guang", date: "1084 CE", detail: "Scrolls 18 and 19: the missions dated into the Wudi annals — the recruitment and capture, the return in 126 BCE, the report to the emperor, the routes out of Shu and the murder of the envoys." },
    { title: "China in Central Asia: The Early Stage, 125 BC–AD 23", author: "A. F. P. Hulsewé and M. A. N. Loewe", date: "1979", detail: "Annotated translation of the Hanshu's Western Regions treatise with the documentary and archaeological evidence from the garrison posts of the corridor." }
  ]
};
