window.HAN06 = {
  id: "han-06",
  dynasty: "Han",
  order: 6,
  title: "The Historian's Price",
  subtitle: "Juyan and the Sima, 99 BCE",
  readMinutes: 7,
  hook: "Five thousand Han foot went into the steppe with no cavalry and no relief, fought and marched a thousand li, and spent their last arrows in a narrow valley. The one officer who said out loud what that was worth lost his standing to the law, and finished a history.",
  heroAlt: "Five thousand Han crossbowmen in a laager of baggage waggons in a bare valley, front rank set with halberds and shields, rear rank loosing, a vast circle of Xiongnu horse closing on the slopes under a low autumn sun, 99 BCE",
  people: [
    { name: "Li Ling", role: "Grandson of the famous shot Li Guang and heir to his posthumous marquisate. Given five thousand foot and no horse: thirty days north, a month of retreat south, a surrender, then twenty-odd years as the Chanyu's son-in-law." },
    { name: "Sima Qian", role: "Grand Astrologer, keeper of the stone chamber and the golden cases. He had never drunk a cup with Li Ling; asked his opinion he gave it, and took the palace punishment rather than leave a hundred and thirty chapters unfinished." },
    { name: "Emperor Wu", role: "Wanted a diversion for his wife's brother's army, took a boast for a promise, then suspected the man who made it. He wished the defeated general dead on the steppe, killed his mother and wife on a misreport, and admitted later that he had been wrong about the relief." },
    { name: "Li Guangli", role: "General of Ershi, named for the Dayuan town his army had been sent to take, and brother of a consort the emperor was burying honours under. Thirty thousand horse out of Jiuquan, and out again with a hundred-odd men after an encirclement." },
    { name: "Lu Bode", role: "Strong-Crossbow Commandant, ordered to meet Li Ling halfway. Ashamed to be another man's rear, he asked to postpone the stroke to spring; the emperor read the plea as treachery and marched the five thousand out." },
    { name: "Ren An", role: "Courtesy Shaoqing: an officer in Wei Qing's household who would not change masters when the younger general rose, later protector of the Northern Army. He wrote to a friend in the inner chambers to reproach him with the duty of recommending men, and got this answer." }
  ],
  panels: [
    {
      art: "panels/han06/00-cover.png", ratio: 1.75, size: "wide",
      caption: "Autumn, 99 BCE. Two armies went out in one season: thirty thousand of horse under a general whose war was arranged to make a marquis of him, and five thousand foot out of Juyan with no horse at all. The histories kept the smaller army better.",
      sima: { text: "Four books and nothing else. The campaign, the surrender and the steppe stand in the Book of Han's memoir of Li Guang and Su Jian. The court, the sentence and the letter that says why its author did not die stand in that book's memoir of Sima Qian, which copies the letter almost whole; an anthology's copy of the same document is a second witness to it. The historian's family and his plan come from the last chapter of his own book, and Sima Guang's universal mirror relays these books in order, adding nothing of its own. Two names before the panels: the general of Ershi is Li Guangli, and the Grand Astrologer is Sima Qian.", source: "On our sources", tag: "note" }
    },
    {
      art: "panels/han06/02-the-house-of-li.png", ratio: 0.8, size: "std",
      caption: "The house of Li had one death in it already. Li Guang had been handed the long road in the great column of 119 BCE, missed the appointed day, and cut his own throat rather than sit before a clerk's board. His grandson grew up in the palaces as the son of a dead man.",
      sima: { text: "Ling was the posthumous heir of Guang's eldest son, the Marquis of Danghu, and was picked to superintend Jianzhang, the palace stables and armories. He was a good rider and a good shot, and the memoir says flatly that he was generous where other men's lives were concerned — which is how a general gets soldiers to die for him. The emperor thought he had Guang's style. Two earlier services are listed: eight hundred horse riding two thousand li past Juyan, seeing nobody and coming back, and five thousand foot drilled at Jiuquan and Zhangye behind the Dayuan expedition — that second body of men is the army of this episode.", source: "Hanshu, juan 54, Memoir of Li Guang and Su Jian", tag: "history" }
    },
    {
      art: "panels/han06/03-the-petition-at-the-martial-terrace.png", ratio: 1.75, size: "wide",
      caption: "The emperor meant to use those five thousand as a shield for the baggage train. Li Ling was summoned to the Martial Terrace, kowtowed, and asked for the opposite: a column of his own, south of the Lan'gan mountains, so that the Chanyu would have to divide his strength rather than fall on one army whole.",
      bubbles: [
        { who: "liling", name: "Li Ling", side: "left", text: "I have no use for horse. Let me strike the many with the few — five thousand foot, straight at the Chanyu's court." }
      ],
      sima: { text: "The order of battle is in the reign annal as well as in the memoir: in the fifth month Li Guangli with thirty thousand of horse out of Jiuquan struck the Right Wise King at the Tianshan and took ten thousand-odd heads, while Gongsun Ao out of the West River and Lu Bode at the Zhuotu got nothing at all. Ling's argument praises his men as warriors of Jing and Chu and sword-guests, strength enough to grip a tiger. The annal gives the same detachment four clauses: five thousand foot out of the north of Juyan, fought the Chanyu, ten thousand-odd heads, the army broken, he surrendered.", source: "Hanshu, juan 54; Hanshu, juan 6, Annals of Emperor Wu", tag: "history" }
    },
    {
      art: "panels/han06/04-no-horse-to-give-you.png", ratio: 0.8, size: "std",
      caption: "The emperor took the boast as a slight on the other generals. He had sent out many armies, he said, and he had no horse to give. Ling said he wanted none. It was thought plucky, and it was granted — with a crossbow colonel ordered to meet the army halfway.",
      sima: { text: "No horse was a budget and not a rebuke: the two great columns of 119 BCE had ridden out with a hundred and forty thousand horse and brought back fewer than thirty thousand, as the Records of the Grand Historian says of those campaigns in plain figures. The officer detailed to meet Ling halfway was Lu Bode, and the memoir keeps his reason for disliking the job: he was ashamed to act as another man's rear. He asked to keep Ling until spring, since in autumn the Xiongnu's horses are fat and the steppe cannot be fought then, and to come out against the east and west Junji with five thousand horse each; he was confident of taking the Chanyu.", source: "Hanshu, juan 54; Shiji, juan 111, Biographies of the General and the Brilliant Rider", tag: "history" }
    },
    {
      art: "panels/han06/05-the-ninth-month-edict.png", ratio: 1.75, size: "wide",
      caption: "The edict is the document to read against every later clause of this story. Ling was to set out in the ninth month from the Shulu screen-fort and patrol to the Longle water south of the eastern Junji mountains; if he saw nothing, he was to come back by the old road of the Marquis of Zhuoye. Bode was sent off to the West River, and one question was appended: what was it you said to Bode? Answer me in full in writing.",
      sima: { text: "The written question is the affair in miniature. The emperor had already decided that the two generals had an understanding and that the younger had coached the older's memorial; Ling marched before he could explain himself. He went north thirty days and came to the Junji, and he drew a map of all the mountains, rivers and ground he had passed and sent his subordinate Chen Bule back with it. Bule was granted audience and told how Ling got the deaths-for-him of his officers and men. The emperor was delighted and made him a Gentleman of the Palace. That was the last news the court had for weeks, and it was news the emperor liked.", source: "Hanshu, juan 54", tag: "history" }
    },
    {
      art: "panels/han06/06-the-waggon-laager.png", ratio: 0.571, size: "full",
      caption: "The Chanyu came at him with thirty thousand of horse. The Han army stood between two hills with its baggage waggons drawn into a camp; Ling led his men out beyond it and set the array — front rank with halberd and shield, rear rank with bows and crossbows, at the drum loose, at the gong halt. The enemy, seeing how few they were, came straight in. A thousand crossbows went off at once.",
      sima: { text: "This is why foot could survive in horse-country, and the memoir keeps the pursuit after it and several thousand killed. The Book of Han and the historian's own account of his family's line are two texts of one battle, and they do not give way alike: his says the column went north a thousand-odd li, fought and marched eight days running, lost more than half its men and killed and wounded ten thousand-odd Xiongnu; hers counts thirty days to the Junji and a month of retiring south. Where they agree is the field's distance from the wall and the arrow bill that follows. The Junji mountains are named and then left alone: readers have put them in the Altai or on the Irtysh, and the record gives nothing to settle it.", source: "Hanshu, juan 54; Shiji, juan 109, Biographies of General Li of Longxi", tag: "debated" }
    },
    {
      art: "panels/han06/07-eighty-thousand-horse.png", ratio: 0.8, size: "std",
      caption: "The Chanyu had walked into something he had not expected, and he sent for the troops of his left and right districts: eighty thousand-odd horse. Ling fought as he withdrew, south for several days, into a valley, fighting continuously. Three wounds rode on a litter, two wounds drove a waggon, one wound still carried a weapon and stood in the rank.",
      sima: { text: "The muster of eighty thousand is the memoir's figure, and the gradation of the wounded reads like an order of the day rather than a flourish: it is the one place in the campaign where the record counts this army's pain by grade instead of by heads taken. Both the emperor's later question about the affair and the speech made for Ling in court turn on the same pair of numbers — under five thousand foot, and a confederation that had to call out every bow-drawing person it had in order to surround them.", source: "Hanshu, juan 54; Hanshu, juan 62, Memoir of Sima Qian", tag: "history" }
    },
    {
      art: "panels/han06/08-the-drum-that-did-not-rise.png", ratio: 0.8, size: "std",
      caption: "The men's spirit was going and the drum calls went unanswered, and Ling asked the question the record keeps: is there a woman in this army? There were. Wives of convicts relocated from the east had followed the column as soldiers' wives and were hidden in numbers in the waggons. He searched them out and had every one killed. Next day he fought again and took three thousand-odd heads.",
      sima: { text: "The Book of Han gives this in four clauses, without comment and without apology, and puts the next day's head-count in the same breath; that is how it arrives — as one more thing a commander does when the drum fails. It is also the clearest evidence that the army had begun to break before its ammunition did. The speech Qian made afterwards keeps the same fact in a kinder form: when Ling called on his men to move, they rose, weeping, wet with blood and swallowing their tears, and went at the enemy.", source: "Hanshu, juan 54; Hanshu, juan 62", tag: "commentary" }
    },
    {
      art: "panels/han06/09-the-fired-marsh.png", ratio: 0.571, size: "full",
      caption: "Along the old Dragon City road the column came into a great marsh of reeds, and the Xiongnu set fire to it from the windward side. Ling had his own men fire the ground in front of them first. South again, to the foot of a hill: the Chanyu sent his son with horse against them, the Han fought on foot among the trees, killed several thousand more, and loosed their repeating crossbows at the Chanyu himself, who gave ground downhill.",
      sima: { text: "The prisoners taken that day brought back the enemy's council, which is why the scene can be printed at all. The Chanyu: these are Han's picked troops; we strike and cannot take them; day and night he draws us south towards the passes — has he not an ambush behind him? The chiefs of the districts answered with the argument that settled the pursuit: a Chanyu at the head of tens of thousands who cannot destroy a few thousand Han will not be able to send men against the border afterwards. They fought on through valley and hill another forty or fifty li, could not break the column, and drew off.", source: "Hanshu, juan 54", tag: "history" }
    },
    {
      art: "panels/han06/10-the-scout-who-went-over.png", ratio: 0.8, size: "std",
      caption: "What ended the army was a quarrel, not a battle. Guan Gai, the watch-officer, had been humiliated by a commandant and went over to the Xiongnu with the answers nobody else had: no relief behind them, the arrows nearly spent, and the front rank is only the general's own staff and the Marquis of Cheng'an's column, eight hundred men each.",
      bubbles: [
        { who: "chanyu", name: "The Chanyu", side: "right", text: "Li Ling, Han Yannian — surrender at once!" }
      ],
      sima: { text: "The Marquis of Cheng'an was Han Yannian, son of Han Qianqiu, the chancellor of Jinan who had ridden at the King of Nanyue with a handful of men and died there; the emperor had enfeoffed the son, and he served under Ling as a commandant. The Chanyu closed the road and attacked from four sides, and the arrows came down like rain. Qian's speech in that court and his letter some eight years later hold on to the same two facts and put them first: arrows spent and the road at an end, and no relief coming. The letter has four words for it, jiu bing bu zhi — the rescue troops did not arrive.", source: "Hanshu, juan 54; Hanshu, juan 62", tag: "history" }
    },
    {
      art: "panels/han06/11-five-hundred-thousand-arrows.png", ratio: 0.8, size: "std",
      caption: "They went south, and before they reached the Dihanshan the ammunition gave out: the memoir's count is five hundred thousand arrows spent in a single day. The waggons were left behind. There were still three thousand-odd men, who cut the spokes off the waggons to hold in their hands, while the clerks fought with a foot-long knife. Driven against the mountain and into a narrow valley, they were stoned from the corners of it.",
      sima: { text: "The figure is a claim and not a census; the same war's other account says only that missiles and arrows were spent and more than half the army lay dead, which is a different sort of number and harder to check. The order of the last hours is given in the plainest style the memoir uses: the banners all cut down, the treasure buried in the ground, and every man told to carry two sheng of dry rice and half a block of ice and to wait at the Zhelu screen-fort. Sima Guang, copying this paragraph centuries later, reads the ice as one piece instead of half a block — one of several small places where a scribe's eye changes a soldier's ration.", source: "Hanshu, juan 54; Zizhi Tongjian, scroll 21", tag: "debated" }
    },
    {
      art: "panels/han06/12-the-drum-that-made-no-sound.png", ratio: 1.75, size: "wide",
      caption: "After dark he walked out of the camp alone in plain clothes and told his officers that none of them was to follow: one man, he said, might still take the Chanyu. A long while later he came back and said that the army was beaten and that here he must die. An officer urged the precedent of the Marquis of Zhuoye, taken by the enemy, escaped, and received again as a guest. Ling said: stop. If I do not die, I am no man of mettle.",
      bubbles: [
        { who: "liling", name: "Li Ling", side: "right", text: "Another few dozen arrows and I could have got clear. Now we have no weapons left. Scatter, every man as birds and beasts scatter — some of you may still get free and report to the Son of Heaven." }
      ],
      sima: { text: "At midnight the drum was struck to rouse the men and it made no sound. Ling and Han Yannian mounted with a dozen-odd desperate men; several thousand Xiongnu horse went after that party, Yannian was killed fighting, and the sentence that ended a general's service to Han is one line: I have no face to report to Your Majesty. Then he surrendered. Of the five thousand, four hundred and odd got in. The memoir adds the measurement the emperor never forgot — the field lay a hundred-odd li from the frontier wall, and the garrison reported it.", source: "Hanshu, juan 54; Zizhi Tongjian, scroll 21", tag: "history" }
    },
    {
      art: "panels/han06/13-what-the-court-said.png", ratio: 0.8, size: "std",
      caption: "The emperor had wanted Li Ling to fight to the death. While the reports were still unclear he sent for Ling's mother and wife and had a physiognomist read their faces for a look of mourning, and found none. When the surrender was confirmed he was furious; he called Chen Bule in and reproached him, and Bule killed himself. The whole company of ministers condemned Li Ling. Then the emperor asked the Grand Astrologer.",
      sima: { text: "The memoir of Sima Qian is the only witness to the question and the answer, and it opens with the disclaimer he always insisted on: he and Ling had never drunk a cup together, they were of no party, and he had nothing to be got. The letter adds what the room was like — that when the defeat was reported the emperor would not eat and could not hear the morning court, that the great officers stood afraid and did not know what to say, and that he himself, lowest of the low, had wanted to make this statement and had no road to make it until the summons came.", source: "Hanshu, juan 62; Shiji, juan 130, the Grand Historian's own preface", tag: "history" }
    },
    {
      art: "panels/han06/14-what-he-said.png", ratio: 1.75, size: "wide",
      caption: "What he said was not that Li Ling was innocent, and it said nothing at all about the surrender. It was that the event ought to be read as the event that happened: under five thousand foot, deep in horse-country, holding down tens of thousands until the enemy was too busy saving its own dead and wounded to do anything else, then besieged by every bow-drawing person the confederation had; a thousand li fought over, and then the arrows and the road at an end together.",
      bubbles: [
        { who: "simaqian", name: "Sima Qian", side: "left", text: "His men stretched empty fists and went at bare blades, facing north and contending to die. He got the death-service of men: no famous general of the past went beyond it." }
      ],
      sima: { text: "The speech stands in the Book of Han's memoir of Qian and is relayed almost word for word in the universal mirror; the letter retells the same interview and is sharper about who was in the room. He had two arguments. A man who served his parents with filial care, was trusted by his officers, and threw himself forward without thinking of his own body in the state's emergency had, he said, the style of a national officer; and it was painful that officers who only keep their own carcases and their wives and children whole should go about brewing his small faults. Then the comparison nobody in the room had thought to make aloud: the great army had been dispatched for the general of Ershi's sake, and Ling had been ordered to be no more than a supporting force — and when Ling met the Chanyu, the general of Ershi's merit was small.", source: "Hanshu, juan 62; Zizhi Tongjian, scroll 21", tag: "history" }
    },
    {
      art: "panels/han06/15-the-price-of-the-speech.png", ratio: 0.8, size: "std",
      caption: "The emperor judged that Qian had deceived him on the throne, that the speech was a slur on his wife's brother and a plea for the surrendered general, and handed him to the officials. A capital sentence could be moved by payment: in the years just after, the annals of the reign show the emperor twice selling a reduction from death for five hundred thousand cash. Qian says he was too poor for that and that not one friend came forward.",
      sima: { text: "So he took the palace punishment, and the records handle it as a legal and biographical fact and nothing more. The memoir gives it in one clause — the emperor sent him down to it — and never describes it; the letter ranks it as the bottom of a list of the ways a man may be shamed, and moves on to what it cost him. What the books give instead are consequences. He was made Master of the Secretariat, honoured and entrusted with duty, an office of the emperor's confidential clerking, and he writes of himself as a minister of the bedchambers and the gate who cannot withdraw and hide in a rock-cave. Years afterwards the emperor came back to the other half of the business: he had been wrong to take Bode into the edict, he had let an old general hatch a fraud, and Ling had been sent out with orders to be met. Then he sent an envoy to comfort and reward those of Ling's remnant who got through.", source: "Hanshu, juan 62; Hanshu, juan 54; Hanshu, juan 6, Annals of Emperor Wu", tag: "history" }
    },
    {
      art: "panels/han06/16-the-right-commandant-king.png", ratio: 1.75, size: "wide",
      caption: "The Chanyu thought a man who had marched five thousand foot to his own court splendid. He gave him a daughter to wife and made him the Right Commandant King, living away from the court and called in when there was a great matter. In the second year of it a Han column went deep into the steppe to fetch him and came home empty-handed with a story about why: Li Ling was drilling troops for the Chanyu, ready against the Han army.",
      bubbles: [
        { who: "liling", name: "Li Ling", side: "left", text: "Master Shao — going back is easy. What I fear is a second humiliation. A husband cannot undergo a second humiliation." }
      ],
      sima: { text: "The story was false and the emperor did not check it: Ling's mother, his younger brother, his wife and children were all put to death, and the memoir says the gentlemen of Longxi were ashamed of the family of Li. When a Han envoy reached the steppe later, Ling was still doing the arithmetic out loud — he had been Han's general with five thousand foot and had gone rampant through the Xiongnu; for want of relief he was beaten; what had he failed Han in, that his house should be killed? The drilling had been done by Li Xu, a former Han commandant who had surrendered under a besieged city and was always seated above Ling; Ling, grieving that his family had been destroyed because of Xu, had him assassinated, and the Chanyu hid him from a consort's anger. After Emperor Wu's death the two men who governed for his successor sent Ling's old acquaintance Ren Lizheng of Longxi with two others to invite him home. At the feast Lizheng could not speak privately, so he stroked his own sword-ring and gripped his foot. Ling came out to the envoys in Xiongnu dress, with his hair in a mallet knot, stared a long while, stroked his own hair, and said only: I am already in Xiongnu dress. When pressed again he named the alternative: the hands of the clerks. The memoir closes the man in one clause — he was among the Xiongnu more than twenty years, and in the first year of Yuanping he died of illness.", source: "Hanshu, juan 54; Zizhi Tongjian, scroll 23", tag: "history" }
    },
    {
      art: "panels/han06/17-the-reply-to-ren-an.png", ratio: 1.75, size: "wide",
      caption: "The letter home is not an apology and it is not a defence. A friend had told him to recommend worthy men, and he answers that he cannot: he ranks the ways a man may be shamed, from not bringing dishonour on his ancestors down to the sentence he had taken, which he calls the bottom; then he says what he is still alive for.",
      bubbles: [
        { who: "simaqian", name: "Sima Qian", side: "right", text: "A man must die once. There are deaths weightier than Mount Tai and deaths lighter than a feather, according to what they are for." }
      ],
      sima: { text: "He is answering a reproach he says he has no standing to receive. Who does it for, and who is there to hear? With Zhong Ziqi dead, Bo Ya never played again; his own great substance is already impaired, and whatever talent he had could now only provoke a laugh and add a blot. His family, he says, was never more than the emperor's amusement, kept as a singing-boy is kept, near to diviners and invokers, and the world sets light by it. Then the list of men who did not die in time and left books instead: the Earl of Xi imprisoned and the Zhouyi rendered; Confucius in straits and the Chunqiu; Qu Yuan banished and the Lament; the elder Zuo blind and the Discourses of the States; Sun Bin's feet cut out and his art of war set down; Lü Buwei exiled to Shu and Han Fei a prisoner in Qin; and the three hundred odes, for the most part what worthies and sages made out of indignation — all of them men with a knot in the heart who could not walk their way, so they set down past doings and thought of those to come. And the sentence that answers the occasion: the draft was not finished when this calamity exactly met it; I prized it for not being finished, and so I took the extreme sentence without a resentful look. With my mouth's words, he writes, I met this calamity, and my intestines turn once a day and come back nine times.", source: "Hanshu, juan 62; Wenxuan, juan 41, Reply to Ren An", tag: "history" }
    },
    {
      art: "panels/han06/18-hidden-in-a-famous-mountain.png", ratio: 0.8, size: "std",
      caption: "If the book is finished and hidden in a famous mountain and handed to the men who can take it, then the cost of the former disgrace is paid, and though I be killed ten thousand times, what could I regret? He says in the next breath that this can be spoken to a wise man and is hard to say to the vulgar, and that right and wrong are settled on the day a man dies.",
      sima: { text: "The book had him before the court did. His father Sima Tan died in 110 BCE, left behind at Zhounan while the emperor went up to Feng to sacrifice, and took his son's hand and wept: his line had kept the records of the Zhou house, and he himself had not set down the enlightened lords, the good rulers and the officers who died for what they were right about — being Grand Astrologer, do not forget what I wished to write. Three years later Qian held the office and drew out the histories and the books in the stone chamber and the golden cases. His own last chapter prints the scheme and the count: twelve basic annals that the threads may be drawn, ten tables, eight treatises, thirty hereditary houses ringed like the twenty-eight mansions about the pole, seventy memoirs; in all a hundred and thirty chapters and five hundred and twenty-six thousand five hundred characters, hidden in a famous mountain with the second copy lodged in the capital, waiting for the sage-men of later generations. His book says seven years of that work ran by before the Li Ling catastrophe; Ban Gu's copy of the same passage says ten. Then the afterlife: after Qian was dead his book gradually came out, and in the time of Emperor Xuan his daughter's son Yang Yun — whose own memoir records that he had read his maternal grandfather's book — handed it down, and it was declared abroad; while Ban Gu notes that ten of the hundred and thirty chapters were already missing, there being the list and no book. No history used here says when or how Sima Qian died.", source: "Shiji, juan 130; Hanshu, juan 62; Hanshu, juan 66, Memoir of Yang Chang", tag: "debated" }
    }
  ],
  myths: [
    {
      myth: "Sima Qian was mutilated, and afterwards put to death, because he wrote history honestly: the emperor read the Records of the Grand Historian, was enraged by its candour, and punished the author for it.",
      truth: "Two books give one narrow cause, and it is a spoken sentence about Li Ling: he says himself that with his mouth's words he met this calamity. The sentence falls in the year after the surrender, years before the book was finished, and no official history has the emperor reading a page of it before punishing the man — the reverse is what the record says happened, since he was afterwards made Master of the Secretariat and trusted with the documents that reached the throne. The stories of a ruler reading and then killing the historian are later than the histories and reach us in anecdote and in notes quoting anecdote.",
      source: "Hanshu, juan 62; Hanshu, juan 54; Shiji, juan 130"
    },
    {
      myth: "Li Ling went over to the enemy of his own accord, became a Xiongnu general and drilled their horse against his own frontier, so his family's execution was deserved.",
      truth: "He gave himself up after the arrows and the road were gone, having buried the treasure, cut down the banners and told his men to scatter so that someone might reach the passes and report. The emperor himself afterwards said the mission had been mismanaged, and sent an envoy to reward the survivors. The report that produced the attainder came from a Han column that had failed to find Ling and lost its own men; the histories say the drilling was being done by Li Xu, a different surrendered officer, and that Ling had him assassinated for it.",
      source: "Hanshu, juan 54; Zizhi Tongjian, scroll 22"
    },
    {
      myth: "The five thousand were annihilated to the last man and the whole business was a disgrace to Han, as the court's verdict assumed.",
      truth: "The surviving count in the memoir is four hundred and odd men in again at the wall, after a month of marching and fighting, with the field a hundred-odd li short of it. The historian's speech — which is a plea and says so — is the only record of how the empire took the news: the plain people were moved by the fate of five thousand foot, while the officers who keep their own carcases went about counting the defeated man's small faults. The Juyan line was not pulled in; the garrisons stayed where they were and the columns went on marching out of it for a decade.",
      source: "Hanshu, juan 54; Hanshu, juan 62"
    },
    {
      myth: "Li Ling's letters from the steppe, above all the reply he wrote to Su Wu, show us how he felt about surrendering.",
      truth: "Neither history contains a line of his writing. What they give is two speeches — one to his own men before the scattering, one to a Han envoy years later — and a song at a farewell in the memoir of Su Wu: ten thousand li crossed, the road cut and the blades broken, his men destroyed and his name wrecked, his old mother dead, and where now to pay the debt. The verse letters between Li Ling and Su Wu stand in the anthology and nowhere else; their attribution has been doubted for centuries, and their homesick loyalist is contradicted by the man who refused to come home.",
      source: "Hanshu, juan 54; Wenxuan, the letters between Li Ling and Su Wu (anthology pieces, named only as the source of the error)"
    },
    {
      myth: "The Shiji came out of the imperial archive complete, exactly as its author left it, and was made in the aftermath of the punishment.",
      truth: "He says the plan and the drafting were older than the calamity: the charge was his father's, the office and the stone chamber came years before it, and the letter's argument for living is that the work was unfinished when the sentence fell. The transmitted text is not the archive's either. The copies he describes are his own — one hidden in a famous mountain, one in the capital — and what was declared abroad came through his daughter's son under Emperor Xuan, a generation after his death, with ten chapters already gone.",
      source: "Shiji, juan 130; Hanshu, juan 62; Hanshu, juan 66, Memoir of Yang Chang"
    }
  ],
  sources: [
    { title: "Book of Han (Hanshu)", author: "Ban Gu, finished by Ban Zhao", date: "1st c. CE", detail: "Juan 54, Memoir of Li Guang and Su Jian: the plan of 99 BCE, the petition at the Martial Terrace, Lu Bode's refusal and the ninth-month edict, the waggon laager and the arrow count, the surrender and the four hundred and odd, the emperor's question and his later regret, the attainder of Ling's house, the Right Commandant King, the refusal to come home and the death in 74 BCE; the memoir of Su Wu inside the same chapter for the farewell song. Juan 6 for the season's other columns and for the price of remission from death; juan 66, memoir of Yang Chang, for Yang Yun's mother." },
    { title: "Book of Han (Hanshu)", author: "Ban Gu", date: "1st c. CE", detail: "Juan 62, Memoir of Sima Qian: the family and the office, the emperor's question, the speech for Li Ling and the emperor's reading of it, the sentence and the appointment as Master of the Secretariat, the letter to Ren An almost entire, the list of the hundred and thirty chapters with Ban Gu's note that ten were missing, and the verdict on Qian's method quoted from Liu Xiang and Yang Xiong." },
    { title: "Records of the Grand Historian (Shiji)", author: "Sima Qian", date: "c. 91 BCE", detail: "Juan 130, the Grand Historian's own last chapter: the line of Grand Astrologers, the father's deathbed charge and the answer to it, the years of drafting, the Li Ling catastrophe, and the scheme of the book in five divisions. Juan 109 for the same battle told by a man who knew the family; juan 111 for the horse bill of 119 BCE; juan 104 for Ren An's career out of a hired cart." },
    { title: "Literary Selections (Wenxuan), juan 41", author: "compiled by the Crown Prince of Liang; commentary by Li Shan", date: "6th c. CE", detail: "The Reply to Ren An as a second, independently transmitted copy of the same document, with a different opening and several variant readings in the famous lines, and the commentary that supplies the vocabulary of the penalty and of the ladder of shames. Used here as a witness to one letter, not as a history of the campaign." },
    { title: "Sima Qian: Grand Historian of China", author: "Burton Watson", date: "1958", detail: "The standard English study of the man and of the biographical material about him, used here for the ordering of Sima Qian's career against the reign-titles, for the rendering of the office names, and for the dating of the letter to Ren An." }
  ]
};
