window.HAN03 = {
  id: "han-03",
  dynasty: "Han",
  order: 3,
  title: "Cut Back the Fiefs",
  subtitle: "Wu, Liang and Chang'an, 154 BCE",
  readMinutes: 7,
  hook: "A minister proposed cutting the great fiefs back and was cut first, still in his court robes, in a marketplace; seven kings rose anyway, and were broken in three months by a commander who would not give battle and would not obey an order to.",
  heroAlt: "A rebel host in dark banners filling the ground before a great rammed-earth city at dusk, siege walls and mantlets pushed against the lower town, smoke rising along the wall-head, and in the far distance across the open plain a second, silent camp with its ramparts unfinished and no smoke at all",
  people: [
    { name: "Liu Pi", role: "King of Wu, sixty-two in 154 BCE, son of the founder's elder brother and therefore the founder's nephew. He had coins cast from his mountains and salt boiled from his sea, had not attended court for a generation, and lost a war that lasted three months." },
    { name: "Chao Cuo", role: "Imperial adviser turned Censor-in-chief, called the bag of wit of the eastern palace while he served the crown prince. He wrote the plan to cut the fiefs back and was delivered to the block in his court robes to buy the rebels' withdrawal." },
    { name: "Yuan Ang", role: "A former chancellor's rival and the one man the emperor had not let Chao Cuo destroy. He proposed the execution that was meant to end the war, carried the pardon to Wu, and was refused audience." },
    { name: "Zhou Yafu", role: "Marquis of Jiang, commander-in-chief. The man whose camp the late emperor had been stopped outside for discipline. He let the rebels beat the empire's richest fief to pieces, cut their grain, and would not fight until they were starving." },
    { name: "Liu Wu", role: "King of Liang, the emperor's full brother and the empire's richest prince. He held Suiyang through the siege, was deliberately abandoned while he held it, and spent the rest of his life getting even." },
    { name: "Emperor Jing", role: "Liu Qi, second emperor of Han, the prince who had killed the heir of Wu with a gaming board. He approved the strategy that won, gave way to the one that did not, and said afterwards that he regretted it." }
  ],
  panels: [
    {
      art: "panels/han03/00-cover.png", ratio: 1.75, size: "wide",
      caption: "The first month of 154 BCE. The host of Wu and Chu stood before Suiyang, capital of the richest fief in the empire, and had been beating on it for weeks. On the same plain another army was dug in and would not move.",
      sima: { text: "This episode is told from the official histories: the memoir of the king of Wu and the hereditary house of the Marquis of Jiang in the Records of the Grand Historian, its memoirs of Yuan Ang and Chao Cuo and of Han Changru, its annals of Emperor Jing; the Book of Han's annals of Emperor Jing and its own biographies of the same men; and the Zizhi Tongjian, which lays the three out in one year. Nothing from a novel or a stage play is a source for a panel; what those traditions add is dealt with at the end, in the Myth Check.", source: "On our sources", tag: "note" }
    },
    {
      art: "panels/han03/02-the-brother-who-ran.png", ratio: 0.8, size: "std",
      caption: "The rebel was sixty-two when he rose, and had been put in his place by the man his father had failed. His father, the founder's elder brother, had been set on the northern frontier, had run from it when the Xiongnu came, and had been made a marquis for his trouble. The son was made a king instead, at twenty, over three commanderies and fifty-three cities.",
      sima: { text: "Liu Zhong, enfeoffed as king of Dai, abandoned his kingdom in 200 BCE and rode off alone to Luoyang to give himself up; the Shiji says the emperor, for the sake of the flesh, would not apply the law and deposed him to a marquisate. His son Liu Pi had served as a cavalry general under the emperor in 196 and been made king of Wu because the men of Wu and Kuaiji were swift and unruly and needed a strong man to hold them. The Records put one more scene in the same creation: the emperor looked at his nephew's face, said he had the look of a rebel, regretted the words after the seal was struck, clapped him on the back and told him not to rise: within fifty years of the Han there will be trouble in the south-east, he said, and is it not you? The war came forty-two years after the enfeoffment, which is one reason to read the prophecy as a story told afterwards.", source: "Shiji, juan 106, Memoir of the King of Wu; Shiji, juan 93; Hanshu, juan 1, Annals of Emperor Gaozu", tag: "commentary" }
    },
    {
      art: "panels/han03/03-copper-and-salt.png", ratio: 1.75, size: "wide",
      caption: "Wu paid for it out of its own ground. Copper hills and seawater: runaways drawn in to mine and coin it, the sea boiled for salt, and no land tax taken from his own people for a generation. Men of note were rewarded year by year and every fugitive from another kingdom was refused back.",
      sima: { text: "The record of Wu's standing is one sentence in the king's own memoir: Wu had the copper hills of Yuzhang commandery, and Pi gathered the empire's runaways to mine them and coin the ore, and boiled the sea for salt, and for that reason took no land tax from his people, so that his expenditure was inexhaustible. When a man owed service he was paid the market rate of the substitute rather than the usual reckoning; the kingdom's talented men and its neighbourhoods were visited and given presents each season; and officials from other kingdoms who came to seize runaways did not get them. The Shiji says this went on for forty-odd years, and draws the conclusion itself: that is why he was able to set their multitude to work.", source: "Shiji, juan 106; Hanshu, juan 35, Memoir of Jing, Yan and the King of Wu", tag: "history" }
    },
    {
      art: "panels/han03/04-the-board.png", ratio: 0.8, size: "std",
      caption: "The quarrel that made the war was a board game. The heir of Wu, lodging at court, played a betting game with the heir of Han; his tutors were Chu men, his manners had never been corrected; the imperial prince picked up the board and threw it, and killed him.",
      sima: { text: "The Wu crown prince was sent back to be buried at home; the king of Wu sent him back to Chang'an — if we are of the same line, when a man dies in Chang'an he is buried in Chang'an. Gaozu's grandson then pleaded illness and stopped attending court. The capital knew the illness was about the boy, tested it, arrested and interrogated several parties of Wu envoys; only then did the king send a substitute to make the autumn court-call, and the envoy's answer is on the record: the king was really not ill, but began by pretending, was caught out, was pressed, and now has nothing left to plan except fear — and he closes on a proverb: to see the fish in the deep pool is not a lucky thing. The emperor pardoned the envoys, sent a staff and a seat — the old man's mark — and excused the attendance. Sima Qian's own verdict on the whole affair puts the origin in that game: the contest for a trick started the trouble, he writes, and in the end it destroyed the root.", source: "Shiji, juan 106; Hanshu, juan 35", tag: "history" }
    },
    {
      art: "panels/han03/05-the-cutting-plan.png", ratio: 1.75, size: "wide",
      caption: "Chao Cuo had told the late emperor for years that Wu could be cut, and had been listened to and not used. Under the new one he was Censor-in-chief, and he put the case in a form nobody could argue with: three of the great fiefs held half the empire.",
      bubbles: [
        { who: "chaocuo", name: "Chao Cuo", side: "left", text: "Cut him and he rises at once, and the wound is small. Do not cut him and he rises later, and it is greater." }
      ],
      sima: { text: "Chao Cuo's memorial is preserved: the empire had enfeoffed the illegitimate branches of the imperial family so generously that the king of Qi held seventy-odd cities, the king of Chu forty-odd and the king of Wu fifty-odd; three such branches of the house, he says, divided half the empire between them. He had also said, of Wu's minting and salt-boiling and its recruiting of the desperate, that the time for indulgence was over. The man himself is characterised in one line in his own biography: severe, upright, and hard on others; as crown prince's household officer he was so persuasive that the eastern palace called him the bag of wit. His own faction's count of what he drafted is thirty chapters of new enactments, and the note on their effect is that the lords went loud about them.", source: "Shiji, juan 106; Hanshu, juan 49, Memoir of Yuan Ang and Chao Cuo", tag: "history" }
    },
    {
      art: "panels/han03/06-thirty-chapters.png", ratio: 0.8, size: "std",
      caption: "The cuts came in pieces, one fief at a time, each with a charge attached: a commandery from Chu for the king's conduct during a mourning period, two commanderies from Wu, a commandery from Zhao, six counties from Jiaoxi for the titles it had been selling. Then an old man arrived from Yingchuan to tell his son what everyone in the empire was saying about him.",
      bubbles: [
        { who: "chaocuo", name: "Chao Cuo", side: "right", text: "It has to be done. If it is not, the Son of Heaven is not revered and the ancestral temples are not at rest." }
      ],
      sima: { text: "Chao Cuo's father came on from Yingchuan to ask why, and the dialogue is recorded in both histories: the house of Liu is safe, but the house of Chao is in danger — I am leaving you and going home. He took poison and said he could not bear to watch the calamity reach his own body. The Shiji and the Hanshu tell the episode in the same order and with the same interval: the father poisoned himself, and a little over ten days later the seven kingdoms rose, nominally to kill him. What the two books agree on is that his own household saw the price before the emperor did.", source: "Shiji, juan 101, Memoir of Yuan Ang and Chao Cuo; Hanshu, juan 49; Zizhi Tongjian, scroll 16", tag: "history" }
    },
    {
      art: "panels/han03/07-licking-the-chaff.png", ratio: 1.75, size: "wide",
      caption: "It was agreed by word of mouth, with no document. A Jiaoxi envoy of the king of Wu brought a proverb out of the streets — lick the chaff and you get to the rice — and an offer: strike west together, and the two lords will divide the empire.",
      sima: { text: "Ying Gao's pitch to the king of Jiaoxi is quoted at length: Wu and Jiaoxi are princes of reputation and will be inspected together; the king of Wu has not dared attend court for twenty years and has to keep his shoulders shrugged and his feet together; and the thing being aimed at is not the cutting of land. The king of Jiaoxi said yes, then went and booked the rest of the eastern kingdoms in a chain. The record of who actually moved is precise. The emperor's annal names the seven: Wu, Chu, Zhao, Jiaoxi, Jinan, Zichuan and Jiaodong. The king of Qi regretted the pact and poisoned himself; the king of Jibei was seized and held by his own senior secretary and could not raise a man; the three Qi kingdoms put their hope in Jiaoxi as their lead and together sat down before Linzi; and the king of Zhao sent north to the Xiongnu to join hands.", source: "Shiji, juan 106; Hanshu, juan 5, Annals of Emperor Jing", tag: "history" }
    },
    {
      art: "panels/han03/08-the-levy.png", ratio: 0.8, size: "std",
      caption: "The old king emptied his kingdom into the field and told them so in the first person: he was sixty-two and would lead it himself, and his youngest son was fourteen and would go in the ranks ahead of them.",
      bubbles: [
        { who: "liupi", name: "Liu Pi", side: "left", text: "I am sixty-two years old and I will lead this in person. My youngest son is fourteen and goes before the men. Anyone between my age and his is called up." }
      ],
      sima: { text: "The Shiji gives the levy as two hundred thousand and odd men, and his letter to the other kings as a claim of five hundred thousand picked troops in Wu plus three hundred thousand more from the south, with a price-list on the front: five thousand catties of gold and a ten-thousand-household marquisate for a general's head, coming down to five hundred catties and five hundred households for an officer of the rank of a thousand shi, and every town or army that came in over counted as so many heads. Wu's own roll of invitations ran to the kings of Huainan, Hengshan and Lujiang and the son of the old king of Changsha — none of whom rose. Every one of these numbers is a claim in a source, not a return.", source: "Shiji, juan 106; Hanshu, juan 35", tag: "history" }
    },
    {
      art: "panels/han03/09-the-council.png", ratio: 1.75, size: "wide",
      caption: "The emperor was in his hall counting grain with his minister when the man he had warned about the king of Wu was fetched in. The answer he got was that Wu had no able men at all, and that the whole business was the work of runaway coiners — and that it would be over shortly.",
      bubbles: [
        { who: "emperorjing", name: "Emperor Jing", side: "right", text: "Let me see how far this can go. I am not so attached to one man that I will refuse the realm an apology." }
      ],
      sima: { text: "Yuan Ang's line was that Wu had the profit of copper and salt, and nothing else: had it really gathered able men they would be helping the king to act properly, not to rise. The emperor then asked what was to be done; Ang asked for the room to be cleared, and when only Chao Cuo was left, said that what he had to say was not for a minister's ears. Cuo went out to the east of the partition, and the record notes that he resented it extremely. The proposal was the rebels' own programme turned against them: kill Cuo, pardon the seven, give back the cut land, and the armies would go home without bloodshed. The emperor was silent a long time before answering.", source: "Shiji, juan 106; Shiji, juan 101; Hanshu, juan 49", tag: "history" }
    },
    {
      art: "panels/han03/10-the-east-market.png", ratio: 0.571, size: "full",
      caption: "Ten-odd days later the Commandant of the Capital sent for the Censor-in-chief with a carriage, on the pretext of a meeting. Chao Cuo did not know. Still dressed in his court robes, he was driven to the East Market and cut in half there.",
      sima: { text: "The indictment is preserved and it is worth reading as a document: the chancellor, the Commandant of the Capital and the Commandant of Justice accuse Cuo of wanting the emperor to lead out in person while he kept the capital himself, of proposing to hand Wu the towns of Xu and Tong that it had not yet taken, and therefore of having no minister's manners — sentence: waist-cutting, and the execution of his parents, wife, children and same-born brothers, old and young, in the market. The emperor's reply is one word: approved. The Han annal of the reign does the whole business in one clause: the Censor-in-chief Chao Cuo was cut down, to apologise to the seven kingdoms. The Shiji's annal of Emperor Jing adds the outcome just as flatly: the envoy was sent to announce the pardon, and it did not stop them; the rebels went on west and invested Liang.", source: "Shiji, juan 101; Hanshu, juan 49; Hanshu, juan 5, Annals of Emperor Jing", tag: "history" }
    },
    {
      art: "panels/han03/11-emperor-of-the-east.png", ratio: 0.8, size: "std",
      caption: "A kinsman of the king of Wu was sent in first, to get him to kneel and take the pardon. Liu Pi laughed and said he was already the Emperor of the East, and kept the envoy in camp under guard, intending to make him serve or die.",
      sima: { text: "The man who got Yuan Ang out was the clerk who had once slept with his maid: Ang had said nothing, let the man run, and given him the girl; the clerk had come back into service and was now a squadron commander in the unit detailed to guard him. He spent his whole kit on two dan jars of strong wine, got the guard at the southwest corner of the perimeter drunk, cut the tent with a knife and walked Ang out between the sleeping men. Ang left his credential and its tufts in his bosom, went on foot seventy li in wooden clogs, saw Liang horse at daylight and rode away to report. What the king of Wu's court had wanted from him is in the same memoir: to make him a general. The Shiji and Hanshu agree on the line he is reported to have given instead.", source: "Shiji, juan 101; Hanshu, juan 49", tag: "history" }
    },
    {
      art: "panels/han03/12-the-old-officer.png", ratio: 1.75, size: "wide",
      caption: "An officer came back from the front with the news that ended the argument. The emperor asked whether the rebels had stopped when they heard that Cuo was dead. He said: no — and then told the emperor what the killing had actually done.",
      bubbles: [
        { who: "denggong", name: "Deng Gong", side: "left", text: "The king of Wu has been ready to rise for decades. The cutting of land is what he was angry about; killing Cuo is the name he gave it. His intent was never Cuo." }
      ],
      sima: { text: "Deng Gong's other sentence is the one that stung: I fear the empire's able men will stop speaking now. Cuo's plan was the ten-thousand-generation benefit of the capital's supremacy; it had begun to be carried out and its author was destroyed — inside, you have closed the mouths of the loyal; outside, you have avenged the lords for them. The emperor let out a long breath and said the sentence the record keeps as his own verdict on his own decision: your words are right, and I regret it too. He made Deng Gong a commandery military commandant, and the war went on.", source: "Shiji, juan 101; Hanshu, juan 49", tag: "history" }
    },
    {
      art: "panels/han03/13-the-marquis-marches.png", ratio: 0.8, size: "std",
      caption: "He went out in a fast courier carriage, changed the road on the way because the enemy was rich and had long kept hirelings, and stopped at Luoyang to look for one famous fighting man. Finding him at home, he said, was half the campaign.",
      bubbles: [
        { who: "zhouyafu", name: "Zhou Yafu", side: "left", text: "The men of Chu are swift and reckless; do not meet their edge. Give them Liang to chew on, cut their grain road, and they can be handled." }
      ],
      sima: { text: "The strategy was agreed in advance, in those words, and the emperor approved it. The detour over the Blue Fields and out of Wu Pass came from a man named Zhao She who stopped the column at Bashang and warned that Wu would have killers laid in the defiles of Yao and Mian; the search found them, and Yafu asked that the man be made a protector of the army. At Luoyang he got hold of Ju Meng, a knight of the capital region, and said what the record preserves: seven kingdoms have risen and I have reached here alive, which I did not expect; I also thought the lords had got Ju Meng, and he has not stirred; I will hold Xingyang and there is nothing to worry about east of here. His father's old retainer at Huaiyang supplied the rest of the plan: deep trenches, high walls, and light troops at the Huai-Si mouth. He had been marked out by the late emperor at Xiliu, where the gate-captain had told the imperial advance party — in this army we hear the general's orders, not the Son of Heaven's edict.", source: "Shiji, juan 57, Hereditary House of the Marquis of Jiang; Hanshu, juan 40; Zizhi Tongjian, scroll 16", tag: "history" }
    },
    {
      art: "panels/han03/14-abandoning-liang.png", ratio: 0.8, size: "std",
      caption: "The fief Yafu had promised to the rebels was the empire's richest, and its king was the emperor's own full brother and the empress dowager's favourite. His appeals arrived every day; then the emperor's order to relieve him arrived too. Yafu did not take the edict, sent light cavalry to seal off the grain road instead, and stayed where he was.",
      sima: { text: "The order of battle in the emperor's annal is four commands: the Grand Marshal Yafu with thirty-six general's titles against Wu and Chu, the Marquis of Quzhou against Zhao, the general Luan Bu against Qi, and the Grand General Dou Ying at Xingyang to watch the east. Wu and Chu's first blow fell on Liang — an army sent out to meet them was defeated, two Liang generals were broken, and the king shut himself in Suiyang. On the first week of the war the three accounts do not agree: the Shiji says the king of Liang sent out six generals and lost two of them, the Hanshu says he sent out generals and lost two armies, and the Tongjian adds a body count of tens of thousands at Jibi that neither earlier book carries. Liang then made its own war useful: Han Anguo and Zhang Yu were made generals, of whom the record says the one fought hard and the one held steady, so that Wu could not get past Liang. Behind the front, Yafu's Marquis of Gongguo and the light horse cut the road the grain came by. The memoir marks the beginning of the quarrel that killed the commander with one flat clause: from this point the king of Liang and the Commandant were at odds.", source: "Hanshu, juan 5; Shiji, juan 57; Shiji, juan 108, Memoir of Han Changru; Zizhi Tongjian, scroll 16", tag: "debated" }
    },
    {
      art: "panels/han03/15-rejected-plans.png", ratio: 1.75, size: "wide",
      caption: "The rebel side had two good plans and refused both. A general asked for fifty thousand to march up the rivers and come at the Wu Pass from behind, and was refused because the king would not put troops under anyone but his own family. Then a junior officer told him to stop taking towns and ride for the armoury and the granary.",
      sima: { text: "Tian Lubo's column was to take Hainan and Changsha and join him at Wu Pass; the crown prince's objection was that a rebellion cannot lend out soldiers, because lent soldiers turn on you. The young commander Huan's argument is the sharpest thing either side said: Wu has infantry, and infantry wants rough ground; Han has chariot and horse, and horse wants open country. If you go slowly and stop to take the cities, the Han cavalry will reach the open ground between Liang and Chu and it is finished. The old generals overruled him: this is what a boy with a sharp point calls strategy. The record then notes that Wu did besiege the cities, and that the king's guests were all made generals, commandants and majors, and the emperor's own edict afterwards tells what that cost the people of the east: they burned the ancestral temples, seized the imperial equipage and dug up graves.", source: "Shiji, juan 106; Hanshu, juan 35", tag: "history" }
    },
    {
      art: "panels/han03/16-xiayi-rampart.png", ratio: 0.8, size: "std",
      caption: "At last the rebels came to the wall of the camp that had let them starve, and challenged for a battle every day. Nothing came out. At night a panic broke inside the Han camp, men ran on each other as far as the commander's own tent; he lay there and did not get up, and it steadied.",
      sima: { text: "Then the move that reads like a formula from a book of war, recorded three times over: the rebels went to the south-east corner of the rampart, Yafu had his men hold the north-west, and the picked troops came at the north-west and could not get in. The host was eating up its own grain by then. Yafu sent his best men out after them and broke them at Xiayi; the emperor's annal gives the result as a hundred thousand and odd heads taken, which is a claim in a source and also a count of men who mostly died of hunger. The edict issued to the generals at the same moment is the plainest statement of what was wanted: strike deep and kill a great deal, and anyone taken who ranks at three hundred shi and above is to be killed; no prisoners; anyone who argues with this edict is to be cut at the waist.", source: "Shiji, juan 57; Shiji, juan 106; Hanshu, juan 5", tag: "history" }
    },
    {
      art: "panels/han03/17-price-of-the-head.png", ratio: 0.8, size: "std",
      caption: "The king of Wu rode out of his camp at night with his strong men and went south over the river to Dantu, and took refuge with the Yue of the east, who had perhaps ten thousand men of their own. The empire announced a price of a thousand catties of gold for the king's head and told those Yue what it would pay.",
      sima: { text: "The end is recorded as a transaction: the Yue lured him out — he came to review their force — and a man struck him down, and his head went off by courier carriage. His sons went to the Minyue, and the grudge there outlived him. The two histories differ slightly on the flight: the Shiji has him cross the Yangzi with several thousand, the Hanshu cross the Huai with a thousand; both have Dantu, and both have the men of Yue cutting off the king of Wu's head. Of the rest of the seven: the king of Chu, defeated, killed himself; the kings of Jiaoxi, Jiaodong, Zichuan and Jinan died and their kingdoms were absorbed; Zhao held Handan for ten months and its king killed himself when Wu and Chu were gone. The emperor's annal names all six of them in one sentence and says of them plainly that they killed themselves.", source: "Shiji, juan 106; Hanshu, juan 35; Hanshu, juan 5", tag: "debated" }
    },
    {
      art: "panels/han03/18-the-settlement.png", ratio: 1.75, size: "wide",
      caption: "The last king gave himself up bare-shouldered, sitting on straw and drinking water, and told the Han commander that Cuo's death had ended it and his army had gone home. The answer came from the son of the man who had handed over Mayi a generation before, and it was about a tally: you had no tiger tally and no order, and by that you show killing the minister was never what you wanted.",
      sima: { text: "The Marquis of Gongguo received the king of Jiaoxi with the gold and drum of his office and asked him, in the record's polite form, to explain why he had mobilised; and then read him the edict and told him to make up his own mind. The sentence that sums up the war's politics is in the same exchange: if Cuo really was a bad minister, why did you not report him — instead you raised troops without tally or order and struck at a loyal kingdom, so on this evidence killing Cuo was never your intention. After the war the map was redrawn, kingdom exchanged for commandery, prince moved from one fief to another, and Liang was left standing until the king's death in 144, when it was split into five kingdoms for his five sons and his daughters were given revenues. What the peace bought is stated in the Shiji's treatise on the balanced standard, which Sima Guang reproduces in his closing survey of the reign: cash piled in the capital's treasury with the strings that held it rotting, and the old grain of the Great Granary overflowing outside and going bad. Sima Qian's own verdict on the cutting of the fiefs is that the lords had grown too strong and that Chao Cuo did not go about it by degrees — and that when the adviser Zhu Fu Yan spoke a generation later, the fiefs weakened and the realm was quiet. The hinge of safety and danger, he writes, is a matter of planning.", source: "Shiji, juan 106; Shiji, juan 11 and 30; Hanshu, juan 5; Zizhi Tongjian, scroll 16", tag: "history" }
    }
  ],
  myths: [
    {
      myth: "Killing Chao Cuo very nearly ended the revolt, and only Zhou Yafu's stubbornness threw away a chance at peace.",
      truth: "The histories say the offer was refused on the spot and the war ran on unchanged. The emperor's own annal records the pardon and the restoration of the land, and then adds that Yuan Ang was sent to announce it and that it did not stop them. The king of Wu would not kneel to receive the edict, and had already declared himself Emperor of the East. Two men in the record say the killing achieved nothing at all: an officer returned from the front, and a Marquis of Gongguo to a king who had surrendered.",
      source: "Shiji, juan 11 and 101; Hanshu, juan 5 and 49"
    },
    {
      myth: "The war of the Seven Kingdoms was a long and exhausting struggle that nearly brought the dynasty down.",
      truth: "It lasted a season. The rising is dated to a specific day, the jiazi day of the first month, and the Shiji's summary is that the armies attacked and held each other for three months and Wu and Chu were broken; the emperor's annal puts the pursuit of the king of Wu at Dantu in the same spring and the deaths of the six other kings before the summer. Zhao alone held out for ten months. The exhaustion in the record is not the war's but the settlement's: the empire's wealth grows in the decades after it.",
      source: "Shiji, juan 106; Hanshu, juan 5; Zizhi Tongjian, scroll 16"
    },
    {
      myth: "The whole eastern half of the empire rose against Chang'an.",
      truth: "The coalition was seven kingdoms out of the many in the east, and two more never moved: the king of Qi regretted the agreement and poisoned himself, and the king of Jibei was held under guard by his own senior secretary and could not raise troops. Wu's own letter invited the kings of Huainan, Hengshan and Lujiang and an heir of old Changsha; none of them came. The Xiongnu, whom Zhao went to for help, sent nothing. The emperor's annal names the seven exactly, and they are the seven.",
      source: "Shiji, juan 106; Hanshu, juan 5, Annals of Emperor Jing"
    },
    {
      myth: "The general who saved the dynasty died honoured, and the emperor he had served never forgot what he had done.",
      truth: "He was dismissed as chancellor, summoned to a banquet where a block of meat was set in front of him with no knife and no chopsticks, and told as he left that such a sulky man would not serve a young master. He was arrested over five hundred sets of store-made armour and shields his son had bought for his tomb and had gone unpaid on; asked why he was arming himself in the world below, he stopped answering, went hungry for five days and died vomiting blood. His king-of-Liang enemy had spent years telling the empress dowager against him, and had men kill the minister who had once been made chancellor in his place.",
      source: "Shiji, juan 57; Hanshu, juan 40; Zizhi Tongjian, scroll 16"
    },
    {
      myth: "Zhou Yafu's end was fate: the physiognomist Xu Fu had read a line in his face that ran into his mouth and told him he would starve in nine years.",
      truth: "Both official histories carry that prediction, and Sima Qian closes the biography with the words Sure enough, the Marquis of Jiang starved to death — a life arranged backwards around an outcome. The same chapters say the plain facts: he was picked out of Zhou Bo's sons as the ablest and given the marquisate, and he died in the hands of jailers who wanted a confession he would not give. Nothing in the accounts of 154 BCE requires the diviner, and the campaign's decisions were his own.",
      source: "Shiji, juan 57; Hanshu, juan 40"
    }
  ],
  sources: [
    { title: "Records of the Grand Historian (Shiji)", author: "Sima Qian", date: "c. 91 BCE", detail: "Juan 106, Memoir of the King of Wu (the origin, the coalition, the levy, the letter, the campaign and the death); juan 57, Hereditary House of the Marquis of Jiang (Xiliu, the command of 154, the prison); juan 101, Memoir of Yuan Ang and Chao Cuo; juan 108, Memoir of Han Changru; juan 11, Annals of Emperor Jing." },
    { title: "Book of Han (Hanshu)", author: "Ban Gu, finished by Ban Zhao", date: "1st c. CE", detail: "Juan 5, Annals of Emperor Jing (the seven kings named, the four commands, the head count, the deaths); juan 35, Memoir of Jing, Yan and the King of Wu; juan 40, Memoir of Zhang, Chen, Wang and Zhou; juan 49, Memoir of Yuan Ang and Chao Cuo." },
    { title: "Zizhi Tongjian", author: "Sima Guang", date: "1084 CE", detail: "Scroll 16: the year 154 BCE assembled in one line — the drunken succession remark, the edicts, the levy, the council, the execution day by day, the march, Xiayi, Dantu, and the deaths of the kings." },
    { title: "The History of the Former Han Dynasty, vol. 2", author: "translated by Homer H. Dubs", date: "1938", detail: "English translation of the Hanshu annals and biographies covering Emperor Jing's reign, the revolt, and Chao Cuo's and Yuan Ang's memorials." },
    { title: "The Cambridge History of China, vol. 1: The Ch'in and Han Empires, 221 BC–AD 220", author: "eds. Denis Twitchett and Michael Loewe", date: "1993", detail: "The structure of the early Han settlement — the commanderies and kingdoms, the non-Liu kings, the revolt of the seven kingdoms and the long work of reducing the fiefs that followed it." }
  ]
};
