window.HAN07 = {
  id: "han-07",
  dynasty: "Han",
  order: 7,
  title: "Ashes in Chang'an",
  subtitle: "The Palace Digging and the Luntai Edict, 91–89 BCE",
  readMinutes: 8,
  hook: "Eight years after five thousand Han foot were left without bread, the city that bled for them began digging up its own palaces for buried figures, and the search ran from a chancellor's cell to the empress's chambers to the eastern palace, until the heir it was all wasted on hanged himself two hundred li south.",
  heroAlt: "Torchlight in a palace courtyard at night, workmen digging between the rows of column bases while officers with tallies stand over a line of carved wooden figures and rolls of silk laid on mats, an opened coffin at the edge of the ground, the rammed walls of Chang'an behind it all, 91 BCE",
  people: [
    { name: "Emperor Wu", role: "In his fifty-first year of fifty-four on the throne when the digging began. He ordered the search, fought his own heir in the streets with a letter about ox-carts, and spent his last four years unbuilding his wars." },
    { name: "Liu Ju", role: "Son of a singing girl who became empress, heir for thirty-one years. He struck off the investigator's head with his own hand, held Chang'an five days, and hanged at Hu." },
    { name: "Jiang Chong", role: "An informer out of Handan who destroyed a crown prince to save himself and was trusted for it. He rode with a shaman to read the ground and heated iron to make men confess." },
    { name: "Shi De", role: "One of the prince's teachers, afraid of dying with his pupil. The only voice the record keeps from inside the eastern palace: proof dug up by an accuser, he says, proves nothing." },
    { name: "Liu Quli", role: "The emperor's nephew and the second chancellor of these eleven months. He won the street war, and was cut in two afterwards on a fresh charge of witchcraft." },
    { name: "Bing Ji", role: "An officer of the Commandant of Justice set to work the witchcraft cases in the prison of the commandery residences. He kept the emperor's great-grandson alive on his own money and never spoke of it." },
    { name: "Tian Qianqiu", role: "An officer of the high tomb, over eight feet tall, who put the dead prince's case in one sentence about a son playing with his father's weapons and was made chancellor for it." }
  ],
  panels: [
    {
      art: "panels/han07/00-cover.png", ratio: 1.75, size: "wide",
      caption: "In the first month of 91 BCE the chancellor of the Han empire died in a prison cell. In the intercalary seventh month two princesses who were the emperor's daughters were executed for figures buried in the ground. In the seventh month the emperor's own seat was lifted off its floor, and the crown prince cut down the officer who had dug in his courtyard and held Chang'an for five days. In the eighth month the prince was found hanged in a storehouse two hundred li east of the walls. He was outlived by four years, which the emperor spent pulling his own reign apart.",
      sima: { text: "Eight chapters of the Book of the Han carry this episode: juan 6 for the dates; juan 63 for the crown prince's house; juan 45 for the man who made the searching an occupation; juan 66 for two chancellors and for the officer who spoke for the prince at the end; juan 55 and juan 97 upper for the empress's family; juan 8 and juan 74 for the child left behind; juan 96 lower for the edict that stopped the war. Ban Gu files the prince under his posthumous name, as the memoir of the Li park. The Zizhi tongjian is used as a relay and not as a witness, and a detail existing only there is marked. The court story-books are used only to be rebutted.", source: "On our sources", tag: "note" }
    },
    {
      art: "panels/han07/02-the-chancellor-and-the-knight.png", ratio: 1.75, size: "wide",
      caption: "In the eleventh month of 92 BCE the emperor called out the knights of the three capital commanderies for a great search of the Shanglin park, then shut the gates of Chang'an and searched the city behind them. Eleven days went by before the gates were opened again, and the year-book enters the business under that winter in three words: the witchcraft began. A year earlier he had forbidden shamans to sacrifice on the roads.",
      sima: { text: "The order of the entries is the argument against the picture of a mob: a levy of knights, a sealed capital, eleven days, a prohibition two years old. The chancellor was Gongsun He, an old cavalry officer of the Wei house's wars, who wept when the seal went into his hands and said he was not equal to it. His son Jing Sheng, the empress's sister's son, had used nineteen million cash of the Northern Army's money; the chancellor caught a great knight of Yangling named Zhu Anshi to buy his son off, and heard back from prison that the bamboo of the southern mountains was not enough for his words. Father and son died in prison in the first month. Ban Gu's summary: the calamity rose from Zhu Anshi, was completed by Jiang Chong, and reached the princesses, the empress and the crown prince.", source: "Hanshu, juan 6, Annals of Emperor Wu; juan 66, Biographies of Gongsun, Liu, Tian, Wang, Yang, Cai, Chen and Zheng", tag: "history" }
    },
    {
      art: "panels/han07/03-the-witch-and-his-princess.png", ratio: 0.8, size: "std",
      caption: "The charge against the chancellor's son was not the money. It was that he had a witch bury carved figures under the imperial carriage-road where the emperor would pass on his way to the summer palace, and curse him with them, and that he lay with a princess who was the emperor's daughter. Two princesses and the empress's nephew died on this business in the intercalary month of 91 BCE. The witch who worked the road is never named and never tried.",
      sima: { text: "The book keeps the buried figures and the adultery in one sentence, which is why the case could not be answered: a man could disprove a figure in the ground and could not disprove a bed. The year-book enters the princesses under the intercalary seventh month, and nothing of theirs under the fifth. Ban Gu's digger is a nameless shaman of the northern peoples; a name appears only in the mirror, and the name this affair carries in modern retelling is in no chapter here. His end is one clause in the prince's biography: when the prince's men held the city, the shaman was roasted alive in the imperial park.", source: "Hanshu, juan 6; juan 63, Biographies of the Five Sons of Emperor Wu", tag: "history" }
    },
    {
      art: "panels/han07/04-the-palace-officer.png", ratio: 0.8, size: "std",
      caption: "Jiang Chong of Handan, born with the name Qi, had denounced the crown prince of Zhao after the prince quarrelled with him; the king of Zhao, the emperor's half-brother, offered to lead the picked brave men of his own state against the Xiongnu to ransom the prince, and the prince was destroyed anyway. Presented in thin unlined gauze and a cap whose tassels swung when he walked, he was admired for his looks and his talk and given a staff to supervise the imperial relatives' extravagance.",
      sima: { text: "Carriages were confiscated and the sons of the great ordered in to serve with the Northern Army until their families bought them off, in sums the book puts at tens of millions of cash. He stopped the emperor's aunt driving on the carriageway reserved for the emperor; when she pleaded an order from the dowager empress, he answered that the princess might ride and her escort might not, and reported the whole train. The emperor's verdict on him is four words: loyal, upright, law-bound, unafraid. The chapter's closing comment quotes Confucius hating the glib mouth that overturns a house, then runs through a list of men who destroyed those closest to them — his pair is the poison wood and the crown prince — and draws the lesson that the small overturned the great and the distant trapped the kin. The emperor, it says elsewhere, learned later that Jiang Chong had been lying, and wiped out three agnate groups of his kindred. His last title matters most because it is no office at all: commissioner of the witchcraft cases, with nothing behind him but the emperor's fear.", source: "Hanshu, juan 45, Biographies of Kuai Tong, Wu Bei, Jiang Chong and Xi Fugong; juan 63", tag: "history" }
    },
    {
      art: "panels/han07/05-what-jiang-chong-reported.png", ratio: 0.8, size: "std",
      caption: "The emperor went up to Ganquan away from the heat of the plain and lay ill there, and the man out of office came to him with a diagnosis: the sickness was a curse, a curse meant figures in the ground, and figures in the ground could be dug out. He was given the cases to try, and went through the palaces with a shaman of the northern peoples reading the ground, arresting anyone who sacrificed in the night, heating iron clamps in the fire and laying them on men until they confessed what they were told.",
      bubbles: [
        { who: "jiangchong", name: "Jiang Chong, commissioner of the cases", side: "right", text: "There is the breath of the poison wood in the palaces. Until it is dug out, Your Majesty will not rise from this illness." }
      ],
      sima: { text: "Ban Gu puts the motive in front of the words: he saw the emperor to be old and feared the crown prince after him, and so made his treachery by reporting that the sickness came from witchcraft. The fuller form of the report, and the shaman's name, are in the mirror. What follows in both books is procedure and not mania: a commission, a specialist, a search, torture licensed to produce what the search had found, and a capital charge that drew a man's family in with him. For numbers keep Ban Gu's own phrase — tens of thousands of persons dead, first and last — and not the larger totals later retelling gives it.", source: "Hanshu, juan 45; Zizhi tongjian, scroll 22", tag: "history" }
    },
    {
      art: "panels/han07/06-the-digging.png", ratio: 1.75, size: "wide",
      caption: "He went first to the ladies of the rear palace who were still hoping to be sent for, and took them in order up to the empress. Then the emperor's own seat in his working chambers was taken down and the floor under it opened. A marquis employed on the imperial clan's business, a censor and an inner attendant of the yellow gate were sent out to help him. The digging reached the eastern palace, and there the paulownia-wood figures came up among the column bases.",
      sima: { text: "The informer's chapter gives the order of the searching and the mirror follows it — first the concubines who hoped for visits, then in order up to the empress, then the crown prince — and that order is the whole case against reading it as a crowd: hope made the first list and rank made the sequence. The prince's chapter supplies the harder detail, that the emperor's seat in his own chambers was taken down to open the floor. The paulownia figures are Ban Gu's; the rolls of silk with a writing that rebelled against the Way, and the line that the trenching left the prince and the empress no place to set a bed, are the mirror's. The year-book, which contains itself entirely, enters the seventh month of 91 BCE with the marquis, the censor and the commissioner digging in the palace of the crown prince, and adds nothing.", source: "Hanshu, juan 63; juan 45; juan 6; Zizhi tongjian, scroll 22", tag: "history" }
    },
    {
      art: "panels/han07/07-the-machine.png", ratio: 0.8, size: "std",
      caption: "The men taken in the searching were tried by the officer who had accused them, on always the same charge, and that charge brought in a man's family with him. Nobody carried anyone else's case up to a court. Years afterwards the emperor wrote to his ministers about the affair he had ordered, and the letter is in the book: he had commanded the chancellor and the censors to drive the officers of two thousand shi into making arrests, and the Commandant of Justice to try the cases — and he had never heard that the Nine Ministers or the Commandant of Justice had held one proper trial.",
      sima: { text: "That letter stands in the chancellor's biography, where the new minister was trying to persuade the emperor to ease his mind, and it damages the proceedings more than anything written against them afterwards: the search began with the women of the Ganquan Palace, moved to the pepper-chambers of the Weiyang, took in the chancellor's son's crowd, and never came before a court. The emperor adds that he ate one meal a day for months and could not bear the sound of music. No chapter gives a list of the accused, or proof that one figure was buried with the intent charged; and the rule often quoted, that a convicted man not killed to the end was thereby disloyal and obscene, is not in these chapters and is not used here.", source: "Hanshu, juan 66; juan 45; juan 63", tag: "history" }
    },
    {
      art: "panels/han07/08-the-house-of-the-general.png", ratio: 0.8, size: "std",
      caption: "At its height the house of Wei held five marquisates: the grand general who took the Ordos, his three sons still in swaddling clothes, his sister's son the Swift Champion, and a fifth in the collateral line. His son Wei Kang, the Marquis of Changping, had lost a marquisate of his own once on a charge and had then inherited his father's; he died in the intercalary month of 91 BCE with the two princesses. Twenty-four years, says the general's own biography, and all five marquisates were gone.",
      sima: { text: "The general's biography, which is where a search of his family's graves would have to appear, says nothing of any digging. It records that he married the emperor's sister the Princess of Pingyang, that he lies with her, and that his mound was raised in the shape of Mount Lu; for the end of his house, one sentence — the Wei were destroyed when the prince failed. The book says the empress bore three daughters before it says she bore a son, and names two princesses executed on this charge; the children killed at one time in the prince's chapter are his sons and daughter, not hers. That the general had been the emperor's servant before he was his brother-in-law is why this fall is a matter of procedure and not of jealousy: the court did not have to open graves to finish a family.", source: "Hanshu, juan 55, Biographies of Wei Qing and Huo Qubing; juan 63; juan 97 upper, Biographies of the Outer Kin", tag: "history" }
    },
    {
      art: "panels/han07/09-thirty-eight-years.png", ratio: 1.75, size: "wide",
      caption: "Wei Zifu came to the emperor out of the household of the Princess of Pingyang, where she had been a singing girl, and after more than a year without a visit she was swept out among the unusable palace women and had to cry in front of him to be taken back. She bore three daughters, then a son, and was made empress in 128 BCE; her son was made heir at seven. Her favour faded, and the women who came after her are named in her entry one after another. She held the seal thirty-eight years. In the eighth month of 91 BCE an officer of the imperial clan and the commandant of the garrison came with a document demanding her seal and ribbon, and she killed herself.",
      sima: { text: "Ban Gu's entry for her is the plainest thing in the book: thirty-eight years as empress, a beginning as a singer, the favour fading, the witchcraft breaking out and Jiang Chong using it, the prince frightened and unable to make himself clear, and so the empress and her son killed Chong and he raised troops and lost. The year-book is flatter: on the renwu day the prince and the empress planned the killing of Chong; on the gengyin day the prince fled and the empress killed herself. She was laid in a small coffin in an empty storeroom of the Public Coach and buried at Tongbai outside the southern wall; her entry names the two inner attendants who carried her out, and one of them is the man who had been sent to help with the digging. The house of Wei was destroyed entire. Her great-grandson, coming out of a gaol to the throne, buried her again with a posthumous name and a park of three hundred households.", source: "Hanshu, juan 97 upper; juan 6; juan 63", tag: "history" }
    },
    {
      art: "panels/han07/10-effigies-in-the-eastern-palace.png", ratio: 0.8, size: "std",
      caption: "Liu Ju had been heir for thirty-one years. He was set the Spring and Autumn in the Gongyang reading and then took the rival Guliang reading from an old teacher, and when he came of age his father built him the Bowang gardens and let him draw guests, at which the book's comment is that most of what came to him came in odd ways. When the digging reached his courtyard, his father lay ill at Ganquan, and neither the empress nor the officers of the eastern palace could get an answer back. His Junior Tutor Shi De was afraid the tutors would be executed with the prince.",
      bubbles: [
        { who: "shide", name: "Shi De, Junior Tutor of the Crown Prince", side: "left", text: "The chancellor's son, the two princesses and the Wei have all died under this charge. Now the shaman and the imperial officer dig, and proofs appear — but no one can say whether the shaman put them there or whether they were truly there. Forge an order, arrest Chong and his people. Have you forgotten Fusu of Qin?" }
      ],
      sima: { text: "The speech, the precedent — Fusu, the First Emperor's eldest son, who took the sword when the order came — and the prince's agreement are all Ban Gu's, and so is the sentence that he was frightened and could not make himself clear. Not in Ban Gu is the other answer: the mirror makes the prince say that he is a man's son and cannot execute a minister on his own authority, that he would rather go in and apologise, and that he started for the summer palace and was pressed too hard to reach it. The relay gives a man trying to surrender; the history gives a man choosing an act. Both give his reason for hurry: the emperor believed everyone at his elbow was cursing him, and no one dared plead for another man.", source: "Hanshu, juan 63; Zizhi tongjian, scroll 22", tag: "debated" }
    },
    {
      art: "panels/han07/11-the-princes-own-hand.png", ratio: 0.571, size: "full",
      caption: "On the renwu day of the seventh month the prince sent men out posing as imperial envoys, with a staff, to arrest the commissioner and his assistants. The marquis who had been sent to help with the digging doubted the staff and would not take the order, and was cut down in the struggle. The censor got out with a wound and reached Ganquan. The prince went to the execution himself and struck off Jiang Chong's head, and the shaman of the northern peoples was roasted alive in the imperial park.",
      bubbles: [
        { who: "liuju", name: "Liu Ju, the Crown Prince, over the body", side: "left", text: "You wretch of Zhao! Was it not enough for you to set a king and his son at odds in Zhao? Must you set my father and me at odds as well?" }
      ],
      sima: { text: "The curse stands in the informer's chapter as well as in the prince's, and in both it is the prince's own definition of the crime: not sorcery but the making of enmity between a father and a son, and the insult is a fact about the man, who was born in Handan. The censor got out with a wound and reached the summer palace, and so did the inner attendant who had been sent to help with the digging; it is the attendant who, in the mirror's account, had informed on the prince to his father years before and who now spoke against him to the emperor, and he was burnt on the Heng bridge when the accounts were settled. Ban Gu gives the killing; the mirror adds the parading of the body. Neither book pretends that any of the three died under sentence.", source: "Hanshu, juan 45; juan 63; juan 6; juan 66", tag: "history" }
    },
    {
      art: "panels/han07/12-five-days.png", ratio: 0.571, size: "full",
      caption: "A retainer of the prince carried a staff through the Changqiu gate of the Weiyang Palace at night and had the empress told by one of her senior women; the middle stable sent out its cars loaded with crossbow men, the arsenal was opened, and the prisons of the capital offices were emptied and their convicts given weapons. A prisoner riding with the prince's staff to call in the cavalry of the northern camps was run down and beheaded, and the horsemen were told the staff was false. The emperor came down from Ganquan, took the Jianzhang Palace west of the city, and wrote to his chancellor: make your ramparts of ox-carts, do not close with short weapons, kill and wound in numbers. Both sides drew men out of the markets, and fought five days under the gate-towers of the Changle Palace. Tens of thousands died, and the blood ran into the drains.",
      sima: { text: "The five days and the tens of thousands are in the chancellor's biography and in the year-book; the prince's chapter gives the other reason the week was lost — the capital was confused and it was given out that the prince had rebelled, so the crowd would not hold with him. The empire's two answers were permanent. The Han staff was plain red, and because a crown prince had carried a red one a yellow yak-tail was added above the red; and the year-book enters that change, beside the first standing garrison of the gates of Chang'an, among the acts of state of the month. The settlement ran by category: the prince's guests were executed, the men who had raised troops with him were exterminated under the law for rebellion, and the soldiers who had plundered were sent to Dunhuang.", source: "Hanshu, juan 66; juan 6; juan 63", tag: "history" }
    },
    {
      art: "panels/han07/13-the-storehouse-at-hu.png", ratio: 0.8, size: "std",
      caption: "The prince went out south by the Fu'ang gate and east, and hid in a ward called Quanjiu in the county of Hu, more than two hundred li from the walls, with two of his grandsons. His host was poor and sold the shoes he wove to keep him fed. The prince heard that an acquaintance of old days was living well in the same county and sent for him, and the man came and gave the place away. Officers surrounded the storehouse. Judging that he could not get out, the prince barred the door of the inner room against them and hanged himself from the beam. The host died fighting in the doorway and the two grandsons died in the room with him.",
      sima: { text: "The year-book puts the flight on the gengyin day of the seventh month and the death on the xinhai day of the eighth, and the chancellor's biography says the prince was taken twenty-odd days after he left the city, which is what those two day-names come to; an earthquake follows in the annal within twelve days. Two men broke in, one kicking the door open and one running to lift the body down, and were made marquises under a decree that states the reason: a reward given where the merit is doubtful is how a government makes its credit good. The biography adds that the officers who had used blades on the prince were afterwards wiped out — and that the emperor, pitying the prince's innocence, built the Palace of Thinking of Him and raised at Hu the Terrace of Returning and Looking. No chapter says the town was renamed.", source: "Hanshu, juan 6; juan 63; juan 66", tag: "history" }
    },
    {
      art: "panels/han07/14-the-child-in-the-gaol.png", ratio: 0.8, size: "std",
      caption: "The imperial great-grandson, born to the crown prince's grandson by his wife of the Wang, was some months old when he was locked up in the prison of the commandery residences at Chang'an under his grandfather's case. The officer ordered to work the witchcraft cases there pitied him and knew in his heart that the prince's business had nothing in it; he chose careful convict women to nurse the child, put him somewhere dry, and paid for his food and clothes out of his own purse. Years later a palace officer came to that gate at night with orders to kill the prisoners of the capital, heavy cases and light alike, and the gate was not opened to him.",
      bubbles: [
        { who: "bingji", name: "Bing Ji, in charge of the residence prison", side: "left", text: "The emperor's own great-grandson is in this building. Men of other families who have not deserved death must not be killed — how much less a king's own great-grandson!" }
      ],
      sima: { text: "The officer was Bing Ji, who had begun as a jail clerk in Lu state reading out the statutes; the annal of the child's own reign writes his surname with a different character, which is the kind of thing two chapters of one book do. He held the gate from midnight until sunrise and was impeached for it, and the sentence that ends the affair is the emperor's: he too came to himself, said that this was the work of a spirit, and amnestied the empire. The boy went back to the household of his great-grandmother the Lady Shi, who had died with the prince. The memorial that brought him to the throne in 74 BCE gives his age as eighteen.", source: "Hanshu, juan 74, Biographies of Wei Xiang and Bing Ji; juan 8, Annals of Emperor Xuan; juan 63", tag: "history" }
    },
    {
      art: "panels/han07/15-the-second-chancellor.png", ratio: 0.8, size: "std",
      caption: "The chancellor who won the five days was Liu Quli, a son of the emperor's half-brother the Prince Jing of Zhongshan, made chancellor in the spring of 91 BCE with twenty-two hundred households, in the year the chancellorship was divided and a second chancellery created. Eleven months later his wife was accused of sacrificing at the soil-altar and cursing the emperor, along with the general commanding the army out in the steppe, for the sake of a rival prince. He was paraded through the town in a provision cart and cut in two in the eastern market, and his wife and children's heads were displayed on the Huayang street. That general heard that his own family had been arrested, and did not come home.",
      sima: { text: "The emperor's letter to Quli during the street war has the Duke of Zhou in it — the business was buzzing all over the empire, what did he mean by calling it a secret, and did not the Duke of Zhou execute his own brothers — which makes being the emperor's nephew no defence. Three officers died over the prince's escape: his aide Tian Ren, who let him through a gate at night; the Imperial Counsellor Bao Shengzhi, driven to suicide for stopping that execution, since an officer of two thousand shi must be reported before he is killed; and the commander of the Northern Army's guard, Ren An, who took the prince's staff, went in, shut his gate, and was executed for meaning to join whichever side won. Li Guangli's offer to the chancellor, at the Wei bridge, had been to make the King of Changyi heir. Ren An is the man the historian's great letter addresses.", source: "Hanshu, juan 66; juan 6; juan 63", tag: "history" }
    },
    {
      art: "panels/han07/16-the-white-haired-man.png", ratio: 1.75, size: "wide",
      caption: "Some while after the prince's death an officer of the tomb-park of the high temple, a man of over eight feet with a good presence, sent up an urgent memorial about the duty that binds a father to a son. He was made Grand Herald on the spot and chancellor within months, the one minister in this book to take the seal out of a sentence. The reversal he asked for is recorded in one clause of the prince's biography, item by item: most of the witchcraft cases were found not to have been real; the emperor knew the prince had acted out of terror; the family of Jiang Chong was wiped out; the inner attendant who had helped him was burnt on the Heng bridge. An elder of a town in Huguan county had written first, and his letter is in the book too.",
      bubbles: [
        { who: "tianqianqiu", name: "Tian Qianqiu, officer of the high tomb", side: "left", text: "A son who plays with his father's weapons deserves a beating. If the Son of Heaven's son has killed a man by mistake, what crime is there worth speaking of? A white-haired old man taught me these words in a dream." }
      ],
      sima: { text: "The emperor's answer is on the record: between a father and a son other men cannot speak, and it is the spirit of the High Ancestor who sent you to teach me. The elder of Huguan had put it plainer — a man of no family was given a command to press the heir, the roads between father and son were blocked, and the young man only stole his father's weapons to get out of a difficulty, and the elder did not believe his heart was wicked. Ban Gu's entry on that letter is that the emperor was moved and woke, and still did not say openly that the prince had been innocent. The man of the dream is written Che in the prince's chapter and Tian in the chancellor's, from the old royal house of Qi; he was called the Carriage Chancellor because his years let him bring a small cart into the palace. The book says he had no other talent, and that it had never happened before that a man took a chancellorship in a month on one sentence.", source: "Hanshu, juan 63; juan 66; Zizhi tongjian, scroll 22", tag: "history" }
    },
    {
      art: "panels/han07/17-what-the-roads-cost.png", ratio: 1.75, size: "wide",
      caption: "The empire had been at war since the year the prince was born, and the book's count is thirty-two years of marching and an exhausted realm; the prince's chapter says thirty. The roads carried the cost. Grain went out to the north-west and did not come back; when a hard-won victory in the far west was followed by the march home, thousands died of hunger on the road, and the emperor said so afterwards. In 90 BCE an army went out three ways and one of its generals, hearing that his wife and children were under arrest at Chang'an, handed his force to the enemy. Then, in 89 BCE, the emperor's Commandant for Grain, with the chancellor and the censor-in-chief, asked him to confirm what the garrisons had begun to assume: colonist-soldiers at old Luntai, where five hundred thousand qing of irrigated field may be had; three commandants to guard the work in sections; and beacon-towers built on westward, to overawe the western states and back the Wusun.",
      sima: { text: "The request is in the western regions memoir, and it is the centre's paperwork rather than a frontier report: it comes from the grain commandant with the two ministers, it asks to extend garrison-land already held at Luntai, Jiezhi and Quli, and it wants volunteers with families and goods behind them, not convicts. The same memoir gives Ban Gu's frame: the first opening of the west, then armies going out continuously, the realm emptied and wasted, a whole command lost to the enemy, and the emperor sorry for the distant wars. The year-book for 89 BCE enters the emperor ploughing at Juding with his own hand and renewing the seal-mound of Mount Tai, and says nothing about Luntai; the mirror does the dating. The officer who signed this request sat eight years later in the minister's chairs defending that frontier against the provincial appeals men, and was executed in 80 BCE in a plot against the regent.", source: "Hanshu, juan 96 lower, Memoir of the Western Regions; juan 6; juan 66; Zizhi tongjian, scroll 22", tag: "debated" }
    },
    {
      art: "panels/han07/18-the-luntai-edict.png", ratio: 1.75, size: "wide",
      caption: "The answer came back as an edict, and it refused. An officer had asked for a levy of thirty cash a head to help the frontier: the emperor said that would press the old, the weak, the fatherless and the widow harder than anyone, and it was dropped. He named the general he had chosen by divination and said the divination had lied, and that the grief for the men who died and were scattered was always in his heart. What was to be done instead was a list an accountant could check: forbid harsh and violent exactions, stop impositions laid on without authority, throw the whole strength into farming, and repair the rule remitting the horse-corvee so that the garrisons may fill up. No army went out again. The chancellor was enfeoffed with a title that stated the policy.",
      bubbles: [
        { who: "emperorwu", name: "Emperor Wu, in the edict of 89 BCE", side: "right", text: "Now you ask to farm Luntai further off and to raise stations and beacon-towers: that is to trouble and fatigue all under Heaven. It is not the way to be generous to the people. I cannot bear to hear of it." }
      ],
      sima: { text: "Ban Gu's phrase for what this document does is that the emperor set out at length his regret for what was past; the edict itself is administrative rather than penitential, and the book gives it no special name. The grander confession — that since his accession everything he had done had been mad, and that there are no immortals — is in the mirror, spoken after a wind drove him back from the sea where he meant to sail for the gods, and is not in the histories. Ban Gu's own summary of these years, closing the prince's chapter, is the darkest sentence written about them: the capital bleeding, corpses in the tens of thousands, prince, son and father all destroyed; and soldiers are like fire, and unless you put them out you are burnt in your own burning. Sima Guang rules that this emperor's faults were the Qin's faults and that he escaped the Qin's end for one reason: he could regret, and at the last he chose trustees who held. He died at the Wuzuo Palace in the second month of 87 BCE, two days after naming his youngest son heir. The great-grandson took the throne in 74 BCE, gave the prince the severe posthumous name li and two hundred households at his park at Hu, gave the prince's consort thirty grave-keepers and the boy's own parents a park of three hundred households, since the ritual forbade an emperor to sacrifice to the father through whom he had not inherited, and eight years later raised that park to a temple and a county of sixteen hundred households.", source: "Hanshu, juan 96 lower; juan 63; juan 6; juan 8; Zizhi tongjian, scrolls 22 and 29", tag: "commentary" }
    }
  ],
  myths: [
    {
      myth: "The witchcraft cases of 91 BCE were a panic: a superstitious old emperor frightened of sorcery, and conjurers and women running wild through the capital.",
      truth: "It was a legal machine and every part of it is named: a commission, a specialist who read the ground, assistants drawn from the imperial staff, torture licensed to produce confessions, and a standing capital charge that brought in a man's family with him. The search ran in a stated order — the concubines who hoped for the emperor's visits, then the empress's chambers, then the eastern palace, with the emperor's own seat lifted off its floor. The emperor admitted afterwards, in a letter kept in a chancellor's biography, that neither the Nine Ministers nor the Commandant of Justice had ever properly tried anyone. Fear supplied the accusations; the procedure supplied the deaths.",
      source: "Hanshu, juan 45; juan 63; juan 6; juan 66"
    },
    {
      myth: "Emperor Wu killed his own son.",
      truth: "The son killed himself: he barred the door of the inner room at the storehouse in Hu and hanged when the officers had the place surrounded. His father wrote the sealed letter that told his chancellor to fight him in the streets with orders to kill and wound in numbers, which is the most damning thing in the episode and not the killing; and he afterwards rewarded the two men who broke in and then destroyed them, wiped out the Jiang kindred, had the eunuch who worked with Jiang Chong burnt on a bridge, and built a palace and a terrace at Hu for thinking of him. The dynasty never treated the prince as a criminal: his grandson came out of a gaol, took the throne, and rebuilt and endowed his tomb.",
      source: "Hanshu, juan 63; juan 6; juan 66; juan 8"
    },
    {
      myth: "The Luntai edict of 89 BCE is where expansion ended: the emperor repented, the west was given up, and the empire turned inward.",
      truth: "The edict refused one proposal — a fresh extension of garrison-farming and beacon-towers further west, on a road the emperor said had starved thousands on the march home even after a victory — and it refused it in fiscal language, with instructions about exactions, farming and the horse-corvee. Nothing already held was given up: Luntai was farmed again within a few years under the officer who had asked for it, and the protectorate over the western regions was established in 60 BCE and held for the rest of the dynasty. Ban Gu's one-line summary, that from that time no army went out again, is about the emperor's remaining years, not about the empire's map.",
      source: "Hanshu, juan 96 lower, Memoir of the Western Regions; juan 70; Discourses on Salt and Iron"
    },
    {
      myth: "The fall of the Wei house is a harem story: a neglected empress, a witch in the women's apartments, and the great general's graves dug up out of spite.",
      truth: "The grave-digging is not in the histories. The general's own biography, which records his marriage to the emperor's sister and the shape of his mound, says only that the five Wei marquisates were stripped within twenty-four years and that the house was destroyed when the crown prince failed; the searching did reach the empress's quarters and her nephew died under the charge, which was enough. Her own entry names no witch at all: thirty-eight years as empress, the rise of rival consorts, the commission, the demand for her seal, her suicide and a small coffin in a storeroom. The spirits and the love that curdled come from the palace story-books, Miscellaneous Records of the Western Capital and Stories of Emperor Wu of Han, which are much later than Ban Gu.",
      source: "Hanshu, juan 55; juan 97 upper. Against the wonders: Xijing zaji and Han wu gushi"
    },
    {
      myth: "The speeches and wonders in the mirror of history — the emperor's dream of wooden men, the prince's wish to go and explain himself, the confession by the sea — are independent traditions filling gaps the Book of the Han left.",
      truth: "They are Sima Guang's workshop, cutting these same chapters into a dated line eleven centuries later and here and there taking in a detail Ban Gu left out or never carried. That is why those three items, and the search that sweeps from the capital commanderies across the whole empire, are marked in the notes as the relay's and are never used as fact. The rule runs the other way too: where the mirror and Ban Gu differ, it is usually Ban Gu's own chapters differing with each other — over whether the years of marching are thirty or thirty-two, and over whether the emperor's death and his heir's appointment fall a day apart or two.",
      source: "Zizhi tongjian, scroll 22; Hanshu, juan 63; juan 6; juan 96 lower; juan 7, Annals of Emperor Zhao"
    }
  ],
  sources: [
    { title: "Book of the Han (Hanshu)", author: "Ban Gu, completed by Ban Zhao and others", date: "1st c. CE", detail: "The biographies, and the reason this episode can be told at all. Juan 63, the five sons of Emperor Wu, for the prince's household, Shi De's speech, the storehouse at Hu and the restoration of the tomb; juan 45 for Jiang Chong's career, the shaman, the iron clamps and the tens of thousands; juan 66 for Gongsun He and Zhu Anshi, the street war, the letter admitting there had been no trial, Liu Quli's fall and Tian Qianqiu; juan 55 and juan 97 upper for the house of Wei; juan 74 and juan 8 for the child in the prison." },
    { title: "Book of the Han (Hanshu), annals and treatises", author: "Ban Gu, completed by Ban Zhao and others", date: "1st c. CE", detail: "The frame the biographies strain against. Juan 6, the year-book of Emperor Wu: the levy of knights and the eleven days in 92 BCE, the chancellor dead in prison, the princesses in the intercalary month, the digging in the seventh month, five days of fighting with tens of thousands dead, the yellow yak-tail added to the credential, the first standing garrison on the gates of Chang'an, and the death at the Wuzuo Palace in 87 BCE. Juan 8 for the restoration under Emperor Xuan, juan 7 for the regency, and juan 24 for the finance that paid for the wars." },
    { title: "Book of the Han (Hanshu), Memoir of the Western Regions", author: "Ban Gu, completed by Ban Zhao and others", date: "1st c. CE", detail: "Juan 96 lower, which carries the Luntai memorial of 89 BCE and the edict refusing it in the emperor's own words, with Ban Gu's frame for both — the first opening of the west, thirty-two years of marching, an exhausted realm, the general who lost a whole command. The same memoir, with juan 70, for what the empire did afterwards: the garrison farmed again at Luntai, and the protectorate established in 60 BCE." },
    { title: "Zizhi Tongjian (Comprehensive Mirror in Aid of Governance)", author: "Sima Guang and his bureau", date: "1084 CE", detail: "Scroll 22, the years 98 to 87 BCE, used throughout as a relay of the chapters above and never as an independent witness. It is where the dated order of these months is worked out, and where four items belonging to it alone are kept: the dream of wooden men, the shaman's named part in the diagnosis, the prince's attempt to go to Ganquan and explain himself, and the emperor's words of self-accusation by the sea. Scroll 29 supplies the later history of the prince's tomb-park." },
    { title: "Discourses on Salt and Iron (Yan tie lun)", author: "The court debate of 81 BCE, traditionally compiled by Huan Kuan", date: "1st c. BCE", detail: "The fiscal half of the aftermath: the wise men and the provincial appeals summoned by the young emperor's edict, arguing with the ministers over salt, iron and liquor, the levied transport of grain, the price stores and the frontier garrisons. Used here for the shape of the case on both sides, and for the man who signed the Luntai request defending that frontier eight years later — never for a number. Juan 66 dates and reports the origin of the debate." }
  ]
};
