window.HAN10 = {
  id: "han-10",
  dynasty: "Han",
  order: 10,
  title: "The Gentle Emperor",
  subtitle: "Luoyang, 25–57 CE",
  readMinutes: 8,
  hook: "A farmer's younger brother, laughed at by his own family for caring about his fields, took the throne at thirty-one and spent three decades un-making the empire on purpose: he merged four hundred counties, sent his generals home rich, refused to march west, and left a restored dynasty whose emperors would never again be able to spend it.",
  heroAlt: "A man in a plain dark robe of the Han court riding a small horse through a half-built city gate at winter dawn, survey stakes and unfinished wall foundations behind him, no captives and no trophies in his train, Luoyang, 25 CE",
  people: [
    { name: "Emperor Guangwu", role: "Liu Xiu of Nanyang, a distant grandson of the first Han emperor who took the throne in 25 CE at thirty-one and died in 57 CE at sixty-two. He spent the thirty-two years between on taking the empire's size down." },
    { name: "Liu Yan", role: "His elder brother, Bo Sheng, who liked retainers and hard drinkers more than ploughing and who actually raised the rising. Killed by the emperor the family had made, in 23 CE; honoured by his brother twenty-odd years later." },
    { name: "Deng Yu", role: "The boy who attached himself to Liu Xiu in the capital's college, rode north to tell him an empire was there for the taking, and was made Grand Minister over the Masses in the field at twenty-four with a fief of ten thousand households. His house was still choosing emperors in 106 CE." },
    { name: "Feng Yi", role: "A surrendered prefect of five walled counties who became the army's model of good order, brought a bowl of hot bean porridge at Raoyang, and was nicknamed the Tree General because he stood aside under a tree while the other officers sat and argued about their credits." },
    { name: "Wu Han", role: "A fugitive horse-dealer from the far north-east who had sold grain on the road; Marshal-in-Chief for twenty years, the man who burned Chengdu after it had surrendered, and the one whose wife was scolded for buying land while the soldiers had none." },
    { name: "Lady Yin Lihua", role: "The beauty of Nanyang he admitted wanting as a poor young man, who refused the empresshood because her rival had the elder son, and whose son became the next emperor. Her own record is the Book of the Later Han's memoir of the empresses." },
    { name: "Ouyang Xi", role: "Grand Minister over the Masses, a teacher of the Documents from Runan, put in chains in 39 CE over the figures in the land-and-household audit and dead in prison within the year." }
  ],
  panels: [
    {
      art: "panels/han10/00-cover.png", ratio: 1.75, size: "wide",
      caption: "The man who put the Han back on its throne spent the rest of his life making the throne smaller. He merged four hundred counties, stood the levies down, sent his marquises off to their estates, refused the army his own officers were begging him to lead into the west, and told his family over the wine that he meant to govern by softness.",
      sima: { text: "This episode is told from the Book of the Later Han: the two halves of the emperor's own annal, then the memoirs of the men and women in it — Deng Yu, Feng Yi and Cen Peng, Wu Han, the officers of the Hebei flight, Song Hong, Huan Tan, Zheng Xing, the empresses, the Western Regions. The ritual decisions and the census come from the treatises, which are Sima Biao's continuation of the dynasty's history, bound into this book; the court history of the day, the Eastern Wing's records, is used only where the commentaries quote it. The Zizhi Tongjian is a relay of these pages and is never a second witness. The later popular novels of the restoration appear only in the myth checks, where they are the thing being checked.", source: "On our sources", tag: "note" }
    },
    {
      art: "panels/han10/02-the-fields.png", ratio: 0.8, size: "std",
      caption: "He was the ninth-generation grandson of the dynasty's founder through a king of Changsha nobody had counted on, and the son of a small county chief; his father died when the boy was nine and an uncle raised him. The annal gives him a tall man's height, fine whiskers, a large mouth, a prominent nose and a forehead like the sun. He minded the ploughs himself.",
      sima: { text: "His elder brother Bo Sheng kept company with brave men and fed retainers, and the annal says he kept mocking Liu Xiu for worrying about farm work, comparing him to Gaozu xiong Zhong — the elder brother of the first emperor of Han, a nobody in the family story. He went to the capital in the Tianfeng years to take the Book of Documents, and when Nanyang starved he was selling grain at Wan, which is where the episode's politics start. One detail belongs to the machinery he later ran: years before the rising he rode to Yan You, a Wang Mang general, to plead a rent-arrears case for the marquis of his own village.", source: "Hou Han shu, juan 1 upper, Annals of Emperor Guangwu", tag: "history" }
    },
    {
      art: "panels/han10/03-the-numerologists-bet.png", ratio: 0.8, size: "std",
      caption: "A man of Wan named Li Tong came to him with a prophecy book and a line made to be believed: the house of Liu will rise again, and the house of Li will be the pole it rises on. Liu Xiu did not dare, then thought about his brother's house full of reckless guests, and bought crossbows. In the tenth month of 22 CE he rose at Wan, aged twenty-eight.",
      sima: { text: "The record of his start is a record of persuasion, not of enthusiasm: the annal says he at first did not accept it, and only weighed that his brother would certainly raise something great and that Wang Mang's ruin was already visible. The young men of the clan hid when they heard the rising had begun, saying Bo Sheng is going to get us killed; then they saw Liu Xiu in the crimson robe and the tall cap of an officer and were startled into settling down — even the careful one is doing it. He began on an ox, and got a horse only by killing the commandant of Xinye. When the loot was shared out unevenly and the crowd turned on the Liu family, he collected what his own kinsmen had taken and gave that away too.", source: "Hou Han shu, juan 1 upper", tag: "history" }
    },
    {
      art: "panels/han10/04-kunyang.png", ratio: 1.75, size: "wide",
      caption: "Wang Mang answered the loss of two armies with the last and largest host the dynasty could raise: a million marchers, forty-two thousand of them armoured, with officers trained by sixty-odd schools of theory, a giant a zhang tall, and tigers, leopards and rhinoceroses for the spectacle. Kunyang held eight or nine thousand men. In the sixth month of 23 CE Liu Xiu rode out at night with thirteen horse and came back with three thousand desperate men straight at the enemy's centre.",
      bubbles: [
        { who: "yanyou", name: "Yan You, Wang Mang's general", side: "right", text: "Is this the fine-bearded one? How has he come to do a thing like this!" }
      ],
      sima: { text: "The storm broke the army, and the book's own figure for the dead is tens of thousands driven into the Zhui river until the water would not run; the survivors crossed over the corpses. The book says no dispatch of troops since Qin had been so grand, and a falling star and a collapsing hill of cloud fell on the camp first. Yan You's admiration is the annal's, and it is worth noting what he had heard: that this young man took no goods, only met soldiers and made plans. The officers had said the same about him in plainer terms before the battle — that he was timid in front of small enemies, so this was strange.", source: "Hou Han shu, juan 1 upper; juan 1 lower, the closing hymn", tag: "history" }
    },
    {
      art: "panels/han10/05-the-brothers-name.png", ratio: 0.8, size: "std",
      caption: "Within three months of Kunyang the emperor he was serving murdered his brother. Liu Xiu rode straight to the capital to apologize for it. He did not boast once about what he had done at Kunyang, he did not dare wear mourning, and he ate, drank and talked as he always had. His opponent was ashamed of it, and gave him a generalship and a marquisate.",
      sima: { text: "The annal keeps all four of those facts in one sentence, which is the closest thing in the book to a portrait of how he thought: never to boast of the rank of Kunyang, never to mourn Bo Sheng, food and laughter as usual. In 39 CE he had the brothers named after death — Bo Sheng as the martial duke of Qi, the other elder brother as the pitiful duke of Lu — and in the spring of 41 CE he built a shrine for four generations of the Chongling line while his own clan women drank in the old house. He also, in the ninth month of 25 CE, issued an edict making it a capital crime to harm the deposed emperor Liu Xuan, whom he had only just enfeoffed as the king of Huaiyang.", source: "Hou Han shu, juan 1 upper; juan 1 lower", tag: "history" }
    },
    {
      art: "panels/han10/06-han-officers-again.png", ratio: 0.8, size: "std",
      caption: "He did not found the restored Han on a battlefield. He founded it in an office. Sent ahead to prepare the eastern capital for the regime he served, he appointed staff, wrote the memoranda, and inspected in the old forms exactly as the old forms required — and men who had laughed at the rising's generals in women's jackets wept at the sight of a correctly filled desk.",
      bubbles: [
        { who: "oldclerk", name: "An old clerk of the previous dynasty", side: "left", text: "I never expected to live to see the officers of Han and their dignity again!" }
      ],
      sima: { text: "The annal's sentence after the weeping is the point: from then on the discerning attached their hearts to him. On the road north in the tenth month of 23 CE he carried the staff of office, heard cases from the second-rank governors down to the subordinate clerks, released prisoners, abolished Wang Mang's pressing ordinances and restored the old names of the Han offices; the people came out with oxen and wine. Note what is not in this paragraph: no mass rising, no army, no claim to the throne. He was a subordinate of another emperor's government, and the restoration he is remembered for began as a change of uniform and paperwork.", source: "Hou Han shu, juan 1 upper", tag: "history" }
    },
    {
      art: "panels/han10/07-the-wanted-man.png", ratio: 0.8, size: "std",
      caption: "A fortune-teller was proclaimed at Handan as the surviving son of a former emperor, and the man he was meant to replace put out a warrant: one hundred thousand households for Liu Xiu's capture. He travelled by night and by day and dared not enter any town, eating at the roadside; at Raoyang he walked into the post-house calling himself the Handan envoy, and got out again by walking slowly.",
      bubbles: [
        { who: "gateofficer", name: "The officer of the Raoyang gate", side: "right", text: "Who can tell what the world will bring forth? Why shut the gate on a man of standing?" }
      ],
      sima: { text: "The annal does not spare this year: he slept by the road, his face split open by frost, and at the Hutuo river there were no boats and the ice took him only until a few carts went through and sank. Feng Yi's memoir adds the meals — bean porridge at the Wu Lou post-house in the cold, then wheat and turnip greens by a roofless shelter in the wind and rain — and says that twenty years later the emperor was still reciting the debt, that the porridge of the urgent days at Wulou and the wheat at the Hutuo had gone long unrepaid. The men who saved him were the minor officers of Xinhe and Shanggu and Yuyang, and the cavalry that arrived from the two northern commanderies under Wu Han and Kou Xun.", source: "Hou Han shu, juan 1 upper; juan 17, Biography of Feng Yi; juan 21", tag: "history" }
    },
    {
      art: "panels/han10/08-the-burning-of-the-letters.png", ratio: 0.8, size: "std",
      caption: "Handan fell in the fifth month of 24 CE, and his clerks pulled out the archive: thousands of letters from his own officials and gentlemen of Hebei, written to the other side, most of them insulting him. He did not open one. He had them all burned in front of the assembled generals.",
      sima: { text: "His word for it is in the annal: let the uneasy ones set themselves at ease. The same year the record gives the other half of his method. He would not fight the Bronze Horse bands when they challenged, cut their grain instead, and after he had surrounded and taken them he let each chief keep his own command, then rode alone through the ranks of men who had not yet been disarmed. They said of it that the Prince of Xiao puts his red heart into a man's belly — how then not to die for it — and he ended with several hundred thousand men, and the west of the pass called him the Bronze Horse emperor. In the same year he was very nearly killed at Shunshui on horseback, and the army believed him dead for days.", source: "Hou Han shu, juan 1 upper", tag: "history" }
    },
    {
      art: "panels/han10/09-the-red-charter.png", ratio: 1.75, size: "wide",
      caption: "At Hao a man who had once shared a college room with him in the capital rode out of the pass with a prophetic book in his hand: Liu Xiu raises troops to arrest the unprincipled, the four barbarians gather like clouds and dragons fight in the fields, at the four-and-seven moment fire is master. On a day marked ji wei in the sixth month of 25 CE he built an altar south of Hao and told Heaven he was taking the empire.",
      bubbles: [
        { who: "gengchun", name: "Geng Chun, of Nanpingji", side: "left", text: "Time cannot be held back; the will of the many cannot be crossed. Once the crowd has scattered it cannot be gathered again." }
      ],
      sima: { text: "The prayer is preserved in full, and it is an argument, not a eulogy: he repeats what his ministers asserted, that Wang Mang seized the throne and he rose in anger, that he broke Wang Xun and Wang Yi at Kunyang and killed Wang Lang and absorbed the Bronze Horse bands, and then it quotes a chart-text, Liu Xiu raises troops to arrest the unprincipled, Mao Jin cultivates virtue and becomes Son of Heaven — Mao Jin being the house name Liu written out in its parts. He refuses three times, as the protocol required, and accepts. The year-name became Jianwu, the first martial, and the town of Hao was renamed Gaoyi, the high town. The same month the Red Eyebrows set up their own puppet; the empire he describes as pacified was, on the day he said it, four-way civil war.", source: "Hou Han shu, juan 1 upper; juan 97, Treatise on Sacrifices, upper", tag: "history" }
    },
    {
      art: "panels/han10/10-luoyang.png", ratio: 1.75, size: "wide",
      caption: "The founding of the eastern capital takes one sentence in the emperor's own annal: in the winter, in the tenth month, his carriage entered Luoyang, he lodged in the Quefei hall of the southern palace, and it was settled as the capital. He was thirty-one by the arithmetic of his own record, and he never went back to Chang'an to live.",
      sima: { text: "Everything the annal says about the choice is a date and a hall. It does not rename the city and it does not call it the eastern capital — that usage is later. The circumstances were the ones he did not advertise: the old capital's palaces had been burned and its graves dug up by the Red Eyebrows, the eleven former emperors' spirit tablets had to be carried east by Deng Yu's staff, and the granary road he now needed ran along the Yellow River valley, where he already held the offices. His ministers in the same month were a twenty-four-year-old as Grand Minister over the Masses with a fief of ten thousand households, a horse-dealer as Marshal-in-Chief, and a district official of Yewang as Grand Minister of Works; the old man made Senior Grand Tutor had once been a county clerk.", source: "Hou Han shu, juan 1 upper; juan 16, Biography of Deng Yu", tag: "history" }
    },
    {
      art: "panels/han10/11-four-counties.png", ratio: 0.8, size: "std",
      caption: "In the first month of 26 CE he made every one of his captains a marquis, and the greatest of them the lords of four counties — four times the size an old schoolman thought lawful. He warned them in the same breath that a man satisfied is a man ruined, and told them to be as one who looks down into an abyss and walks on thin ice.",
      bubbles: [
        { who: "dinggong", name: "Ding Gong, academician", side: "left", text: "Of old the kings gave their enfeoffed lords no more than a hundred li, so that the trunk was strong and the branches weak. Four counties is not a lawful size." }
      ],
      sima: { text: "He answered the academician with the sentence that is the whole settlement: of old, states were lost through a lack of principle, and no one ever heard of a state perishing because its meritorious officials had too much land. The seals were handed over the same day, and the investiture document told the marquises to be haughty without danger and full without overflowing, and to hand the fief down as a barrier for Han. Read against the rest of the reign, though, the bargain was never felt as fair by anyone: Huan Tan's memorial says the rewards and grants were thin and that the empire was not settled in time because of it; the governor of Yuyang rebelled in 26 CE on the ground that he and his colleague had done equal service and been paid equally little; and Ma Yuan, given a whole large county for the south, wrote that Lu Bode had opened seven commanderies and been given only a few hundred households, and asked how so little merit could carry so thick a reward for long.", source: "Hou Han shu, juan 1 upper; juan 28 upper, Biography of Huan Tan; juan 12; juan 24, Biography of Ma Yuan", tag: "debated" }
    },
    {
      art: "panels/han10/12-the-state-shrinks.png", ratio: 1.75, size: "wide",
      caption: "In 30 CE he ordered the empire counted and cut. His own edict said the reason offices exist is to serve the people, and that with the households wasted and gone the county staffs were still too thick; the ministers folded four hundred and odd counties into others and kept one official in ten. That same year the commandery commandants who drilled the annual levies were abolished, and the marquises were told to go and live on their estates.",
      sima: { text: "The list is a policy, and it is in the annal year by year: the demobilisation edict of 31 CE sent the light chariots, the horse, the material officers and the naval men back to the ranks of the common people; the land tax in 30 CE was put back at one part in thirty, which had been the settled Western Han rate and not the wartime tenth; in 37 CE four kings of the blood were demoted to marquises because their rank did not accord with the classics, and with them the whole roll of one hundred and thirty-odd prince's sons and heirless marquises, while three more kings were stepped down to dukes; in 42 CE the provincial governors were struck and the inspectors put back; in 50 CE the emoluments of every post of a thousand shi and above were cut below the Western Han rates, and those below them raised. The treatise of commanderies and kingdoms says of its own list that every county named in the earlier book and missing here was merged away by this emperor.", source: "Hou Han shu, juan 1 lower; juan 109, Treatise on Commanderies and Kingdoms", tag: "history" }
    },
    {
      art: "panels/han10/13-the-unmarked-grave.png", ratio: 0.571, size: "full",
      caption: "In 50 CE he ordered his own burial mound, and the minister of works proposed the usual sacred acres. The emperor refused: the ancient kings buried with clay figures and tiled vessels, a wooden chariot and a thatched horse, so that later ages would not know where they lay. His ground was to be two or three hundred mu, with no hill on it and no more ponds than let the water run off.",
      sima: { text: "He named his model himself, and it was not a founder but Emperor Wen, whose bare grave at Baling was the one that survived the fall of the Western Han intact — the practical reason for a small tomb is the army that digs up the large ones. His dying order of 57 CE is the same thought turned into procedure: he had done the people no good, so let everything follow Emperor Wen's制度 and be reduced and sparing; the inspectors and the second-rank governors were not to leave their cities, and no clerk was to be sent, and no memorial to come up the postal relay. The state funeral of the man who restored the dynasty was to be a piece of correspondence nobody had to answer.", source: "Hou Han shu, juan 1 lower", tag: "history" }
    },
    {
      art: "panels/han10/14-the-soft-way.png", ratio: 0.8, size: "std",
      caption: "He went back to the village where he had grown up in the spring of 41 CE, repaired the garden and the temple, sacrificed at the old house, and sat drinking with his own people. The aunts who had brought him up got merry and said: when Wen Shu was young he was careful and honest, cold to other people, nothing but plain and soft — and now he has come to this. He laughed out loud and said what he meant.",
      bubbles: [
        { who: "emperorguangwu", name: "Emperor Guangwu", side: "right", text: "When I set the empire in order, I too mean to go about it by the soft way." }
      ],
      sima: { text: "The phrase is his own, ruo dao, the soft way, and the annal sets it beside the family shrine he then built for every branch of the Chongling Liu. What the record actually documents, though, is legislation rather than temper. In 26 CE people who had sold a wife or a child to keep alive were declared free to go home to their parents and anyone who held them was to be prosecuted; in 28 CE no clerk under six hundred shi could be imprisoned without a prior report, and no man of eighty or boy of ten or woman implicated by her husband could be put in chains; in 35 CE the edict said that among the natures of heaven and earth man is the precious thing, and that those who killed their slaves and bond-servants should not have their sentences cut for it; in 31 CE he ordered that memorials to him must not call him sage. In the same spring of 41 CE he deposed Empress Guo to be the queen dowager of Zhongshan and made the lady Yin empress, and his historian noticed that this, too, was handled so that later ages could see no gap between the thick and the thin of his treatment.", source: "Hou Han shu, juan 1 upper and lower; juan 10 upper, Annals of the Empresses", tag: "history" }
    },
    {
      art: "panels/han10/15-the-land-audit.png", ratio: 1.75, size: "wide",
      caption: "In the summer of 39 CE he ordered every province and commandery to verify the acres under plough, the households and their ages, and to check up on the second-rank governors who had been crooked and unfair about it. Two of his own Grand Ministers over the Masses died in that business within eighteen months — one dismissed and by his own hand, one in chains — and in the ninth month of 40 CE the governor of the capital commandery and ten-odd more went to prison and died there for the numbers.",
      sima: { text: "The charge against them in the annal is four characters: the audit was not done truthfully. Then the land answered. The great families of the commanderies, the men who held the local soldiers, and the ordinary bandits rose everywhere in the same months, hurting and killing the chiefs of offices, and when the authorities came they scattered and when the authorities left they massed again; the annal names the four provinces of the east and north as the worst. The court did not send an army. It sent a proclamation: five bandits who cut down one of their number went free; officers who had hung back or let them go deliberately were not to be charged; a local chief who simply failed to catch them was not blamed, and only those who hid the fact were punished. The chiefs were then transplanted to another commandery, given fields and a ration, and told to settle down to live.", source: "Hou Han shu, juan 1 lower", tag: "history" }
    },
    {
      art: "panels/han10/16-the-refused-west.png", ratio: 1.75, size: "wide",
      caption: "The oasis kings came back to him in 38 CE and the road opened again; in 41 CE the greatest of them asked to be made Han's protector of the west, and the seal was on its way out before a frontier governor at Dunhuang argued that you cannot lend the barbarians that much power and forced the court to take it back. In the winter of 45 CE sixteen of them sent their sons in hostage and asked for a protector, weeping and bowing their heads to the ground. He sent the boys home with rich presents.",
      bubbles: [
        { who: "emperorguangwu", name: "Emperor Guangwu", side: "left", text: "Just now my envoys cannot bring a great army out beyond the passes. If the strength of your states is not equal to your will, then east, west, south or north — you are free." }
      ],
      sima: { text: "The annal's reason for refusing is six characters: the middle regions had but newly settled, and there was no leisure for affairs outside them. The Western Regions memoir tells the same refusal with the numbers wrong — eighteen kings instead of sixteen — and gives the sequel: the king of Shache went on attacking, killed and carried off over a thousand people at Shanshan, and when the answer came back as above, Shanshan and the Tangut lands of the Turfan oasis went over to the Xiongnu again. The memoir ends the account with its own arithmetic: the Western Regions were severed from us for sixty-five years and then reopened. The reopening is the next life but one, and the man who did it was a copy-clerk with thirty-six companions.", source: "Hou Han shu, juan 1 lower; juan 88, Memoir of the Western Regions", tag: "history" }
    },
    {
      art: "panels/han10/17-the-night-he-read-the-chart.png", ratio: 0.571, size: "full",
      caption: "In 54 CE his ministers said thirty years of reign deserved the sealing and the sacrifice at Tai Shan, and he wrote back that after thirty years on the throne the people's resentment was full in their bellies, and that if any commandery or state sent an official from far away to offer congratulations with inflated praise he would have the man's head shaved and sent to work a garrison farm. Nobody dared raise it again for two years. Then he read a prophecy book one night while he was fasting.",
      sima: { text: "The text was the chart of the meeting at Mount Tai, which promised the fortune of the red Liu's ninth generation on that mountain, and the annal says he was moved by it: he ordered his officers to go back through the river and Luo charts for anything about a ninth-generation封禅, they reported findings, and he agreed. In the second month of 56 CE he burned the sacrifice facing Tai Shan, climbed and sealed it, and made the rite at Liangfu below; the stone inscription cut that spring is preserved and it quotes the chart lines, including the one that had brought him the throne. The same year he built the Bright Hall, the Spirit Terrace and the Round College, and — the annal's sentence, of 56 CE — he promulgated the charts and the apocrypha to the whole realm. When he asked Huan Tan where the Spirit Terrace should go and said he meant to decide it by the apocrypha, Tan said after a long silence that he did not read them, then went on at length that they were not classics; the emperor called that slandering the sages and having no law and was about to have him beheaded, and Tan's forehead bled on the tiles before he was let go, and he died of illness on the road to his post in Lu'an. Zheng Xing, asked the same question about the suburban sacrifice, answered I do not read them and was forgiven; the memoir adds the consequence: he spoke often on public affairs and always out of the classics, and because he was not good at the apocrypha he was never given the highest employments. Chen Yuan said the same thing about a book: the Zuo tradition was taken up by his own judgment, and dropped halfway because its masters did not understand the charts.", source: "Hou Han shu, juan 1 lower; juan 97, Treatise on Sacrifices, upper; juan 28 upper, Biography of Huan Tan; juan 36", tag: "history" }
    },
    {
      art: "panels/han10/18-the-reckoning.png", ratio: 0.8, size: "std",
      caption: "He died in the second month of 57 CE in the front hall of the southern palace, sixty-two by his own annal, and left the empire to the son Lady Yin had borne him. His historian found the man worn out with war and knowing that the world was spent, and having after the pacification of Long and Shu never spoken of military affairs again unless something pressed.",
      sima: { text: "The annal's closing judgment is the settlement itself in five words and five more: the meritorious officials put back, the document officers brought forward, the bows and arrows put away and the horses and oxen turned out — the war that stops war. His son asked him once about formations and got the answer that a duke of Wei once asked Confucius the same and did not get it, and that this was not his son's concern; and asked not to work from dawn until the sun went west every single day on his health, he said he liked it and did not find it tiring. Two records of what that left. The treatise of commanderies and kingdoms gives the count of 57 CE: four million two hundred seventy-one thousand six hundred and thirty-four households, and twenty-one million seven thousand eight hundred and twenty mouths, with its own verdict on the hundred years of Wang Mang and the wars that the people were wasted and of ten only two remained; one printed form of that figure has three where the standard collation reads two. And Zhong Changtong, writing two generations after the collapse: the emperor grieved at the loss of power by several reigns and hated the strong minister's theft of the mandate, so he corrected the crooked past the straight, put no trust in what was below him, and though he appointed the three ministers, the business went to the terrace offices; the ministers were only there to be blamed. Power then moved to the families of empresses and to the attendants near the person — and of the first of those families, the ten-thousand-household marquis of 24 CE had been the ancestor of the men who sat in the palace and chose an emperor in 106 CE.", source: "Hou Han shu, juan 1 lower; juan 109, Treatise on Commanderies and Kingdoms; juan 49, Biography of Zhong Changtong; juan 16", tag: "commentary" }
    }
  ],
  myths: [
    {
      myth: "Guangwu won his empire as a battlefield genius, the sword-throwing emperor of the popular retellings, who personally put a million men to flight at Kunyang.",
      truth: "Kunyang is in the record and so is his personal courage, but the record's own evidence for what he was good at lies elsewhere: he cut the Bronze Horse bands' grain for a month before he fought them, he wrote to his generals telling them to sit still, and when Wu Han disobeyed him at Chengdu in 36 CE he read him out in the same letter style — but I told you a thousand things and here you go throwing yourself into a battle. His ministers say the effect in one line: he consulted Deng Yu about every general he employed, and Deng Yu's picks all fitted the post, so the emperor was known for knowing men. The million and the forty-two thousand are the court's own numbers, repeated in the emperor's accession prayer and in the annal's closing hymn.",
      source: "Hou Han shu, juan 1 upper and lower; juan 16, Biography of Deng Yu; juan 18, Biography of Wu Han"
    },
    {
      myth: "The restoration of the Han was a rising of the people which swept a reluctant landholder onto the throne in 25 CE.",
      truth: "Every step of his ascent in the record is the work of a few men with a stake in the name. A numerologist from Wan brought him a prophecy line to sell him on it; his own kinsmen hid from the rising; a puppet emperor's government made him an inspector, and the annal's most quoted line about that job is an old clerk weeping to see the Han offices' dignity again. He was made emperor by a classmate riding in with a chart-text, a colonel warning him that the crowd would otherwise go home, and a memorial that compared the omen to the white fish of Zhou. The portents of his birth — the red light in the room, the single stalk of grain with nine ears that gave him his name — are collected in the annal by his historian, who ends the list with a question rather than a claim.",
      source: "Hou Han shu, juan 1 upper; juan 1 lower, the historian's essay"
    },
    {
      myth: "His mildness proves the Eastern Han state was soft: a government that could not even count its own land.",
      truth: "The land-and-household audit of 39 CE shows a state sharp enough to kill its own top officials over a return: the governor of the capital commandery and ten-odd governors died in prison in 40 CE, and two Grand Ministers over the Masses died in the same business. What happened next is the real story. When the great families and the men who commanded the local soldiers rose in four provinces at once, the court did not send an army after them; it forgave the officers who had let them through, promised a pardon to any five bandits who killed one of their number, moved the chiefs to another commandery and gave them fields. The state stopped being exact about land and stayed exact about everything else, and the annal's own line about cattle grazing with the town gates open is how it congratulated itself on the compromise.",
      source: "Hou Han shu, juan 1 lower"
    },
    {
      myth: "The prophetic charts and apocrypha were a fringe superstition hovering at the edges of his court, a private oddity of an ageing emperor.",
      truth: "They were the court's constitutional material, and the record dates them precisely. The text that made him emperor was a chart-line, and he read it aloud to Heaven on the altar at Hao in 25 CE; in 56 CE he promulgated the charts and the apocrypha to the whole realm in the same year as he built the Bright Hall and the Spirit Terrace. The Feng and Shan he had refused with a threat in 54 CE he performed in 56 CE because he had read a chart one night during his fast and had his officers go and find more. Two scholars who said flatly that they did not read them nearly died of it and spent the rest of their careers out of the great offices; a whole school tradition of the Zuo commentary was stopped in mid-flight, in a minister's words, because its masters did not understand the charts.",
      source: "Hou Han shu, juan 1 upper and lower; juan 97, Treatise on Sacrifices; juan 28 upper; juan 36"
    },
    {
      myth: "The Eastern Han was the Western Han carried on under the same name, restored by a descendant to the same machinery.",
      truth: "The name was restored; the state was rebuilt smaller and differently run. More than four hundred counties were folded into others in 30 CE with one officer in ten kept; the commandery commandants who drilled the annual levy were abolished in the same year; the light chariots, the horse and the naval levies were stood down in 31 CE and sent back to civilian registration; the land tax went to one in thirty; the provincial governors became inspectors again in 42 CE; four kings of the blood and a hundred and thirty-odd other princes were stepped down in 37 CE; and in 50 CE the pay scale above a thousand shi was cut below the old Western Han rates. His own register counted four million households and some twenty-one million mouths at his death in 57 CE, against the treatise's memory of the fullest Western Han count — of the people, its sentence says, ten parts left two. Zhong Changtong's verdict on the machinery, written late in the dynasty: the three ministers were appointed, and the business went to the terrace offices.",
      source: "Hou Han shu, juan 1 lower; juan 109, Treatise on Commanderies and Kingdoms; juan 49"
    }
  ],
  sources: [
    { title: "Book of the Later Han (Hou Han shu)", author: "Fan Ye, completed 5th c. CE", detail: "Juan 1 upper and lower, the Annals of Emperor Guangwu, which carry this episode's spine: the accession prayer of 25 CE, the marquisate settlement of 26 CE, the county mergers and demobilisation of 30–31 CE, the land audit of 39–40 CE, the refusal of the Western Regions in 45 CE, the sealing of Mount Tai and the promulgation of the charts in 56 CE, the death and the funeral order of 57 CE, and the historian's own two comments. Plus the memoirs: juan 10 upper for the empresses, 12 for Peng Chong, 16 for Deng Yu, 17 for Feng Yi and Cen Peng, 18 for Wu Han, 20 for Ji Zun, 21 for the officers of Hebei, 24 for Ma Yuan, 26 for Song Hong, 28 upper for Huan Tan, 36 for Zheng Xing and Chen Yuan, 49 for Zhong Changtong, 88 for the Western Regions." },
    { title: "Continuation of the Han History (Xu hanshu), the treatises", author: "Sima Biao, 3rd c. CE; bound into the Book of the Later Han", detail: "Juan 97, Treatise on Sacrifices upper: the altar at Hao and the full text of the prayer to Heaven, the suburban sacrifices of Luoyang, and the record of the sealing and sacrifice at Tai Shan in 56 CE including the refusal edict of 54 CE, the reading of the meeting-at-Mount-Tai chart, and the words cut on the stone. Juan 109, Treatise on Commanderies and Kingdoms: the household and mouth counts of 57 CE, the treatise's own summary of a century of depopulation, and the rule that a county missing from its list was one this emperor merged away." },
    { title: "Records of the Eastern Wing (Dongguan han ji)", author: "the court's own compilers, successive hands, 1st–2nd c. CE", detail: "The near-contemporary official history of the dynasty, now in fragments and used here only where the commentaries quote it: the description of a general's funeral carried out on the model of Emperor Xuan's visit to Huo Guang, the emperor's repeated lament for Ji Zun and another officer's embarrassed answer to it, and the family particulars of the Guanglie empress. It is a court record made inside a century of the events, and it flatters." },
    { title: "Comprehensive Mirror to Aid in Government (Zizhi Tongjian)", author: "Sima Guang and colleagues, 1084 CE", detail: "The annals for the years 23 to 57 CE, used strictly as a relay: for these reigns it abridges the Book of the Later Han's annal and memoirs, and where this episode gives a date it is the Hou Han shu's own date. Cited nowhere as an independent witness, and the ordering of the land-audit years follows the annal rather than the mirror." },
    { title: "Imperial Prison: A Study of the Bureaucracy under the Last Emperors of the Hou Han Dynasty", author: "Rafe de Crespigny", date: "1977", detail: "Modern work on the administrative machinery of the later dynasty — the throne and terrace offices, the imperial affinal houses and the eunuch captains — which is what this episode's ending points at: the instrument Guangwu built to keep strong men from stealing mandates, and who ended up holding it." }
  ]
};
