window.HAN13 = {
  id: "han-13",
  dynasty: "Han",
  order: 13,
  title: "The Yellow Turbans",
  subtitle: "Jizhou and Yingchuan, 184 CE",
  readMinutes: 8,
  hook: "A preacher of the Great Peace spent twelve years building an empire inside the empire with nothing but charmed water and a confession, fixed the day of its rising, set two of the emperor's own attendants to open the gates to him — and was betrayed by his own disciple, so that the house of Han grew weak that spring, before the rebels had fairly marched.",
  heroAlt: "A crowd of peasants kneeling in a dirt yard before a plain-robed healer holding a bowl of water and a folded talisman, yellow strips of cloth on their heads, a gate tower behind them, 184 CE",
  people: [
    { name: "Zhang Jue", role: "The healer of Julu who styled himself Great Excellent Teacher, da xianliang shi, and served the way of the Yellow Emperor and Laozi, later called the way of Great Peace. Ten-odd years of charmed water and confession made him head of an enrolled empire inside the empire; he died of sickness before it was broken." },
    { name: "Ma Yuanyi", role: "Zhang Jue's chief of one great battalion, who gathered tens of thousands out of Jing and Yang for a junction at Ye, came and went to the capital and took two Regular Attendants at the emperor's elbow as his men inside it, and was torn apart by teams at Luoyang when a fellow disciple gave the whole arrangement away." },
    { name: "Huangfu Song", role: "Left Commandant of the Guards, sent west into Yingchuan with Zhu Jun. He won that war in one night's fire and the north in a dawn assault, and in the year after, an accusation from two Regular Attendants he had offended took his general's seal and six thousand of his households." },
    { name: "Zhu Jun", role: "Right Commandant of the Guards, fighting his own war at Wan. The one officer who argues that men with no way out must fight to the death — and who refused a surrender for that reason, took the place by storm, and is credited with the killing either way." },
    { name: "Lu Zhi", role: "North Commandant of the Guards, leading the northern army's five campuses, and the age's great teacher of the classics. He would not fee the Yellow Gate envoy sent to his camp, was reported for it by the man himself, and lost his command and very nearly his life." },
    { name: "Zhang Rang", role: "Regular Attendant, the man the emperor said was his lord. When the capital's plot was found out the emperor turned on the Regular Attendants, and Zhang Rang and his fellows went bareheaded and barefoot, paid their private wealth into the war, and were left in office; the officer who pressed for their deaths died in prison on a charge worked up against him." },
    { name: "Liu Yan of Yi", role: "Imperial clansman who in 188 proposed turning the regional inspectors into governors with real power, then asked for such a post himself — a far southern province, to be out of the way — and got Yizhou instead." }
  ],
  panels: [
    {
      art: "panels/han13/00-cover.png", ratio: 1.75, size: "wide",
      caption: "In 184 the house of Han had held the empire near four hundred years, and in one spring it lost the use of it. The blow came neither from a frontier nor from a prince: it came out of the villages of the eastern provinces, from a healer with a talisman and twelve years of work behind him.",
      sima: { text: "The rising stands in the Later Han history in three places: the emperor's annal for the dates, the memoir of the general who broke the main host for the movement's inside story, and the eunuchs' memoir for the capital's half of it. The Tongjian relays all three and is used as a relay, not a witness — with one exception, the name of the movement's way, which is its own and not theirs.", source: "Hou Han shu, juan 8, Annals of Emperor Ling; juan 71, Memoir of Huangfu Song; juan 78, Memoir of the Eunuchs; Zizhi Tongjian, juan 58", tag: "note" }
    },
    {
      art: "panels/han13/02-taiping-way.png", ratio: 0.8, size: "std",
      caption: "Zhang Jue came from Julu, a commandery of Ji province on the plain east of the Taihang mountains. He took up the way called Great Peace and worked among the sick with water given a talisman and a recited formula, and with one rule: the patient must kneel first and put his faults on the record.",
      sima: { text: "The kneeling and the confessing of offences are the Han memoir's own words, which the Tongjian copies, and so are the talisman-water and the recited formula; the memoir adds what mattered more, that the sick were cured often enough for people to talk. What is the Tongjian's, and not in the memoir at all, is the name — it calls the practice the way of Great Peace, where the memoir has him serving the way of the Yellow Emperor and Laozi — and its word for it, a sorcery by which he taught, which is judgment and not a checkable fact.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; Zizhi Tongjian, juan 58", tag: "history" }
    },
    {
      art: "panels/han13/03-thirty-six.png", ratio: 0.571, size: "full",
      caption: "For twelve years he sent disciples out in all directions, and the way spread through eight of the empire's provinces. Then he enrolled what he had gathered: thirty-six battalions, the great ones ten thousand men and above, the lesser six or seven thousand, each with its chief.",
      sima: { text: "The eight provinces are the memoir's list — Qing, Xu, You, Ji, Jing, Yang, Yan and Yu — the populated east and centre, with no frontier province in the west. The thirty-six and its sizes, the great ones over ten thousand men and the lesser six or seven thousand, are Huangfu Song's memoir, which the Tongjian copies; the emperor's annal counts the same thirty-six in men instead of divisions, at thirty-six ten-thousands all wearing yellow head-cloths, and cites a rival history for over thirty-six ten-thousands. So the books differ in what the thirty-six is a number of, and this page follows the memoir, which reads as the organisation. The figure for the proselytising is loose, ten-odd years, and this page rounds it to twelve. The word for a battalion, fang, means a square or a division, and the memoir glosses it as the title of a general: these were commands, not bands.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; juan 8, Annals of Emperor Ling", tag: "debated" }
    },
    {
      art: "panels/han13/04-jiazi-day.png", ratio: 1.75, size: "wide",
      caption: "What made an enrolled religion an army was a date. With white earth they wrote one word on the gates of the capital's temples and on the offices of the provinces — jiazi — and the order with it: on the fifth day of the third month the host outside and the hand inside were to rise together.",
      sima: { text: "The white-earth writing, the day and the slogan are Huangfu Song's memoir's, which the Tongjian copies. The slogan is given here in translation only, and the memoir introduces it as a false report circulating, not a creed the movement was asked to believe: the Blue Heaven is dead, the Yellow Heaven is to stand, this year is jiazi, and there is great luck under the whole sky. The memoir says the yellow head-cloth was their mark, and the annal has the man style himself Yellow Heaven; neither book explains the colour. The reading of yellow as the virtue that succeeds the Han's fire is put elsewhere in the history into another great man's calculations, and is not this movement's.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; juan 8, Annals of Emperor Ling", tag: "history" }
    },
    {
      art: "panels/han13/05-the-capital-hand.png", ratio: 0.8, size: "std",
      caption: "A rising fixed to a day needed a hand inside the walls. One of Zhang Jue's great battalion-chiefs, Ma Yuanyi, came and went to Luoyang more than once and found the two men whose office put them at the emperor's elbow, the Regular Attendants Feng Xu and Xu Feng, who were to be his people inside.",
      sima: { text: "That the arrangement reached Regular Attendants of the inner court is the point, and both sides tell it: Huangfu Song's memoir for the plot, with the men named as his inside men and the day agreed with them; and the memoir of the eunuchs for the wider fact that Zhang Rang and his fellows really had dealings with Zhang Jue, and for what the exposure cost Feng Xu and Xu Feng, who were discovered and put to death for it. That no bargain in money is recorded anywhere is worth noting against the usual telling. The junction at Ye and the gathering out of Jing and Yang are in the same sentence of the Han memoir, which the Tongjian copies rather than adds to.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; juan 78, Memoir of the Eunuchs", tag: "history" }
    },
    {
      art: "panels/han13/06-the-informer.png", ratio: 0.8, size: "std",
      caption: "It was undone by one of his own disciples. In the spring of 184 Tang Zhou, a man of Jinan from inside the movement, went up to the capital and informed on the arrangement: the day, the junction, the names at court. The court could call the story false or act on it; it acted, and the day it had fixed was still some weeks off when the rising came all the same.",
      sima: { text: "Tang Zhou stands in the record as the movement's own man, a disciple of Zhang Jue from Jinan, given no grievance, no price and no later career, so nothing is built around him. The memoir dates his letter to the year and the Tongjian to the season; neither gives it a month, and the arrests that follow are undated too. That the rising came in the second month, before the day that had been agreed, and that riders were sent out night and day to warn the divisions, is the memoir's own account of why it came early.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; Zizhi Tongjian, juan 58", tag: "history" }
    },
    {
      art: "panels/han13/07-burning-in-the-market.png", ratio: 1.75, size: "wide",
      caption: "Ma Yuanyi was torn apart by teams at Luoyang, and the inquiry went out from the letter: the Three Excellencies and the Colonel-Director of the capital district were set on it, and a purge of the Great Peace people among the palace attendants, the guards and the townspeople killed a thousand and more. Ji province was ordered to hunt down Zhang Jue and his brothers. The word reached Julu in time for nothing but haste.",
      sima: { text: "The dismemberment and the thousand-odd dead are in Huangfu Song's memoir, which the Tongjian copies; the emperor's annal does not record them at all, and its first entry for the year is the rising in the second month. What the annal does date is the rest of the court's answer, and it is worth having: the general-in-chief and the eight passes in the third month, and four days later the amnesty for the prohibited partisans, which the annal attributes to the Regular Attendant Lü Qiang's warning that men long under the bolt would join the Turbans and be past remedy — and the annal adds that one man was left out of it, Zhang Jue. That is the lifting this line's last episode ended on, and it is a war measure. The new reign-title and a general amnesty came in the twelfth month, when the main host had already been broken; no recorded clause let enrolled followers home unpunished.", source: "Hou Han shu, juan 8, Annals of Emperor Ling; juan 67, Memoir of the Partisan Prohibitions; juan 71, Memoir of Huangfu Song", tag: "history" }
    },
    {
      art: "panels/han13/08-yellow-turbans.png", ratio: 0.8, size: "std",
      caption: "Eight provinces went off at once. In the kingdoms of Anping and Ganling the people seized their own kings to join the rising; everywhere the rebels burned the government offices and sacked the walled towns, the provinces and commanderies lost their footing, and the chief officers over them mostly ran. The record's measure of it is one clause: within ten days the whole empire answered them, and the capital was shaken.",
      sima: { text: "The burning of the offices, the provinces losing their footing and the flight of the chief officers are Huangfu Song's memoir's own words, which the Tongjian copies with the same sense; the annal supplies the two kingdoms that seized their kings and says they all rebelled on one day. Where the memoir says within ten days the Tongjian says within a month, and the memoir adds what no date shows, that they killed men to sacrifice to Heaven and were also called Ant Men, from the ant-hill. The two books do not say that the people feared the bandits and despised their own officials; that sentence is not in either, and a page should not lean on it.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; juan 8, Annals of Emperor Ling", tag: "history" }
    },
    {
      art: "panels/han13/09-four-generals.png", ratio: 1.75, size: "wide",
      caption: "The court answered with the only thing it had left, its own men. It made the emperor's brother-in-law He Jin general-in-chief, put him over the palace guards and the northern camps at the capital's posting ground, and set commandants at the eight passes about it. Three central commanders went out at once: Lu Zhi north against Julu with the northern army's five campuses, Huangfu Song and Zhu Jun west into Yingchuan with those camps, the horse of the three rivers and volunteers, forty thousand and more between the two. The fourth appointment, Dong Zhuo as central commander of the east, came only in the sixth month, and came as Lu Zhi's substitute.",
      sima: { text: "The annal puts three of the four commands into a single sentence of the third month, immediately after the general-in-chief and the eight passes, and the Tongjian has the whole business in the same order. The titles of the fourth, Dong Zhuo, are in his biography, which also says he went out to supersede Lu Zhi. How two of them got their commands is recorded too: the four offices of the court recommended Lu Zhi, and the ministers of state recommended Zhu Jun for having a strategist's gifts. Huangfu Song had the title in his memoir while already a governor of Beidi, and was not, as this line's first draft had it, called back from being out of work.", source: "Hou Han shu, juan 8, Annals of Emperor Ling; juan 64, Memoir of Lu Zhi; juan 71, Memoirs of Huangfu Song and Zhu Jun; juan 72, Memoir of Dong Zhuo", tag: "history" }
    },
    {
      art: "panels/han13/10-yingchuan-broken.png", ratio: 0.571, size: "full",
      caption: "The first campaign went badly. In Yingchuan the host under Bo Cai met Zhu Jun in the field and beat him, and Huangfu Song moved up to hold the town of Changshe, where Bo Cai brought his whole host and invested him with a garrison too small for the work and an army afraid. In the north the two commanders sent against Zhang Jue made no head and came back, and Dong Zhuo, sent to supersede Lu Zhi, was defeated and had to answer for it.",
      sima: { text: "The defeat in Yingchuan and the holding of Changshe stand in Huangfu Song's memoir, which needs them to make its general's victory, and Zhu Jun's memoir in the same volume tells the same business from his side; the annal dates the defeat to the fourth month and the battle that relieved Changshe to the fifth. That Lu Zhi and Dong Zhuo campaigned against Zhang Jue without result and came back is stated in Huangfu Song's memoir, and that is why the court ordered Song north. Dong Zhuo's own biography gives the place of his defeat as Xiaquyang and says he was sent as Lu Zhi's substitute, and the annal says he did not prevail. Neither his biography nor Lu Zhi's says that Lu Zhi brought him out, and this page should not say it.", source: "Hou Han shu, juan 71, Memoirs of Huangfu Song and Zhu Jun; juan 8, Annals of Emperor Ling; juan 72, Memoir of Dong Zhuo", tag: "history" }
    },
    {
      art: "panels/han13/11-changshe-fire.png", ratio: 1.75, size: "wide",
      caption: "Huangfu Song was shut up in Changshe with fewer men than the enemy and would not fight until he had seen the ground. He watched the camp outside until he saw that it was made of brush and stood with the wind at its back; then, on a night when the wind rose, he had his men bind torches of reed and mount the wall, and picked hands slipped out beyond the investment and set the camp alight with a great cry, and the torches on the wall were held up in answer. He came out at the drums and fell on their formation, a relief column came up at that hour, and the host broke, in the fifth month.",
      bubbles: [
        { who: "huangfusong", name: "Huangfu Song", side: "left", text: "War turns on the unexpected, not on numbers. The enemy's camp is built among grass, which is apt for wind and fire; if we burn them out in the night they must be terrified and confused. We issue and strike them, closing on all four sides, and the work of Tian Dan may be done." }
      ],
      sima: { text: "The fire at Changshe is in Huangfu Song's memoir with its particulars: the enemy's camp in grass, the wind that rose that night, the reed torches, the picked hands slipped out beyond the lines, the torches held up from the wall, the sally at the drums, and tens of thousands killed. The memoir says plainly that his troops were few, gives the speech in which he argues from the unexpected change rather than from numbers, and has him name Tian Dan, the general who saved Qi by fire from inside a besieged town — the annotation to the memoir spells the story out and sends it to the Shiji. The relief is named in the Han book itself, not first in the Tongjian: the emperor sent the Cavalry Commandant Cao Cao with troops, and Song, Cao Cao and Zhu Jun joined and fought again. The Tongjian adds Cao Cao's native state, and the month.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; Zizhi Tongjian, juan 58", tag: "history" }
    },
    {
      art: "panels/han13/12-the-emperors-guilt.png", ratio: 0.8, size: "std",
      caption: "The court could now afford to ask why it had almost died. Huangfu Song's recorded cure was to lift the prohibitions on the party men and to open the palace treasury and the imperial stables to the soldiers, and going north he had a Regular Attendant's mansion at Ye confiscated for breaking the rules of size and refused another's private demand for fifty million cash. The memoir of the eunuchs prices the rest: no governor and no recommended man went out to his province until he had haggled at the emperor's private gardens. The emperor's own words go the other way.",
      bubbles: [
        { who: "lingdi", name: "Emperor Ling", side: "right", text: "Zhang Changshi is my lord; Zhao Changshi is my mother." }
      ],
      sima: { text: "The advice, the mansion at Ye and the fifty million are in Huangfu Song's memoir; the prices and the haggling in the Western Garden are in the memoir of the eunuchs, and belong to the year after the rising, not to the rising, and the annal dates the same squeeze to a levy of ten cash per mu for the repair of the palaces. The emperor's sentence is given in the eunuchs' memoir as a habit of the reign, and the first term in it is a title of honour, not a father. When the capital's plot was found out the emperor called the Regular Attendants to account for their dealings with Zhang Jue and asked whether they were not ripe for beheading; they went bareheaded and barefoot, begged to be put in the emperor's own prison, offered their private wealth for the war, and were told by edict to put their caps back and attend as before. The officer who pressed for the heads of the Ten Regular Attendants had his letter handed to them to read, and died under interrogation in prison on a charge of studying the Yellow Turban way, worked up on their orders.", source: "Hou Han shu, juan 78, Memoir of the Eunuchs; juan 71, Memoir of Huangfu Song; juan 8, Annals of Emperor Ling", tag: "history" }
    },
    {
      art: "panels/han13/13-wan-and-massacre.png", ratio: 0.8, size: "std",
      caption: "The other war was Zhu Jun's, in the south, round the commandery seat of Wan. He carried the walls and the enemy fell back into the inner town, begging to surrender; he refused, and could not take the place. Then he opened the ring and fell on them as they came out. The record credits him with more than ten thousand heads twice over, and the annal dates the final taking of Wan to the winter.",
      bubbles: [
        { who: "zhujun", name: "Zhu Jun", side: "left", text: "Their ring outside is tight and their camp inside is pressed; refused a surrender and unable to get out, they must fight to the death. Ten thousand men of one mind are hard to withstand, and these are a hundred thousand. Lift the siege, and fall on them where they are not at their stand." }
      ],
      sima: { text: "The whole of it is Zhu Jun's memoir: the refusal of the surrender because taking men in who fought when it suited them and craved terms when it did not would open the door to both, the two failed assaults, the mound he climbed to see the position, and the words he turns and says to his staff officer Zhang Chao, which are the words above, shortened here as they are shortened everywhere on this page. The memoir also reports what the stratagem did not settle — the surrendered Han Zhong was killed anyway by the commandery governor of Nanyang, who had long resented him, the rest were afraid, chose a new leader and came back into Wan, and had to be destroyed again — and that at the first of the two sieges the court came within one memorial of recalling Zhu Jun in disgrace, and was argued out of changing a general in the field by the Minister of Works. The counts are the memoir's own, written as credit and not as scandal.", source: "Hou Han shu, juan 71, Memoir of Zhu Jun; Zizhi Tongjian, juan 58", tag: "history" }
    },
    {
      art: "panels/han13/14-guangzong.png", ratio: 1.75, size: "wide",
      caption: "In the north Lu Zhi had thrown an encirclement round Guangzong, dug its lines and built his scaling ladders, and was within taking it — Zhang Jue's people had retreated into that town after a run of beaten battles — which was going well enough to be complained of. The emperor sent a Yellow Gate eunuch, Zuo Feng, to look at the enemy; a colleague urged Lu Zhi to send him off with a fee, and Lu Zhi would not. The man came back and reported against him, and the court took his command away and sent for him in a prison-cart.",
      bubbles: [
        { who: "zuofeng", name: "Zuo Feng", side: "right", text: "Guangzong's bandits are easy enough to break. Only, the Central Commandant Lu keeps his walls shut and his troops at rest, waiting for Heaven to punish them." }
      ],
      sima: { text: "The fee refused, the report made by the man who was sent for it, the emperor's anger and the prison-cart are in Lu Zhi's memoir, and the annal tells the same business with its own two sentences: the eunuchs slandered him and he took his punishment, and it names the Yellow Gate man. Lu Zhi is given no speech anywhere in this episode — the words quoted above are the envoy's, and the memoir reports them as what he told the emperor. The memoir's sequel is the part usually left out: Huangfu Song, called north after Lu Zhi and Dong Zhuo had both come back without result, took Guangzong, and then praised Lu Zhi's methods of command to the court and said that whatever he had himself achieved he had drawn on Zhi's planning. Lu Zhi was made a Master of Documents again in that same year.", source: "Hou Han shu, juan 64, Memoir of Lu Zhi; juan 8, Annals of Emperor Ling", tag: "history" }
    },
    {
      art: "panels/han13/15-dug-up.png", ratio: 1.75, size: "wide",
      caption: "The movement's house came down in two battles and a grave. Zhang Liang was cut down in the fighting at Guangzong in the tenth month; Zhang Bao fell at Xiaquyang in the eleventh, and the memoir credits that place with more than a hundred thousand heads and captives, raising a mound of the dead sealed over with earth, south of the town. Zhang Jue had already died of sickness: they opened his coffin and sent the head to the capital.",
      sima: { text: "The two brothers' deaths, the opened coffin and the mound stand in Huangfu Song's memoir, which gives the mound and its count as its general's credit, sets it south of the town, and glosses such a mound as corpses piled and sealed over with earth; the annal dates the coffin to the tenth month and adds the place the head was sent on to, the horse-market, where such things were shown. Nothing in either book says that men who surrendered at Xiaquyang were killed; a surrender killed after terms is recorded, but further south, at Wan, and by a commandery governor serving in the same siege. Where these books give tens of thousands for one battle, or a hundred thousand for a place, the figures are the source's claim and are stated here as that.", source: "Hou Han shu, juan 71, Memoir of Huangfu Song; juan 8, Annals of Emperor Ling", tag: "history" }
    },
    {
      art: "panels/han13/16-what-the-victory-bought.png", ratio: 0.8, size: "std",
      caption: "Victory came, and the men who won it were punished for it. Lu Zhi, brought out of his camp in a prison-cart, was condemned and got off with his sentence reduced one degree, and was a Master of Documents again that year; Huangfu Song, the year after winning the war, had his general's seal seized and six thousand households struck off his marquisate on an accusation from two Regular Attendants he had offended; and Zhu Jun at Wan was within one minister's memorial of being recalled in disgrace. And the provinces were not quiet: the annals go on entering the same name for years after — the Black Mountains, Runan, the White Wave valley, Qing and Xu, Yi province.",
      sima: { text: "Two of the three, and not the third. Lu Zhi's memoir has the envoy make the report and the annal say the eunuchs slandered him; Huangfu Song's memoir names the accusers, the confiscated mansion at Ye and the money he would not hand over, and gives the charge as fighting without result and spending much — a claim to distrust about a courtier, though the two tell it alike and state the spite. Zhu Jun is the odd one out: nothing was alleged against him but slowness, no eunuch is named, and the man who saved his command was the Minister of Works on the plain argument that changing a general in the field is what war fears. All three memoirs also record the honours that came first, and the annal keeps entering Yellow Turban bands in province after province down to the last year of the reign.", source: "Hou Han shu, juan 64, Memoir of Lu Zhi; juan 71, Memoirs of Huangfu Song and Zhu Jun; juan 8, Annals of Emperor Ling", tag: "history" }
    },
    {
      art: "panels/han13/17-lords-of-the-provinces.png", ratio: 1.75, size: "wide",
      caption: "What the war had really created was a second government. Every officer who raised a force against the rebellion kept it; every province left to feed its own armies learned to hold its grain. In 188 the imperial clansman Liu Yan went to the throne with a proposal that reads like reform and is not: the inspectors have too little weight to restrain anyone and the wrong men are put in the posts anyway — replace them with governors who carry the centre's authority, and pick the court's heavy men for them.",
      bubbles: [
        { who: "liuyanofyi", name: "Liu Yan", side: "left", text: "The inspectors' authority is too light to restrain them, and the men used are not the right ones, so violence and disorder only grow. Change the posts to governors, to overawe the regions and settle them, and choose the court's weighty men for the places." }
      ],
      sima: { text: "The two opening sentences of the panel are ours and not the record's; the record supplies the fact underneath them. Liu Yan's proposal is in his memoir, and so is why it took effect when it did: the inspector of Yizhou was complained of far away, and two other inspectors had been killed by rebels. The memoir gives his next move too — he had asked for a province in the far south to be out of the way, and went out instead as an envoy overseeing the armies with the governorship of Yizhou, along with a governor of Yu and a governor of You, each kept at his old rank. The book's verdict on the change is eight characters, zhou ren zhi zhong, zi ci er shi: the weight of provincial command dates from here. The annal's verdict on the year of the rising is four, han sui wei ruo, the house of Han thereupon grew weak — and it lifts that out of a treatise, not out of its own narrative.", source: "Hou Han shu, juan 75, Memoir of Liu Yan; juan 8, Annals of Emperor Ling", tag: "history" }
    },
    {
      art: "panels/han13/18-the-hinge.png", ratio: 0.8, size: "std",
      caption: "The amnesty bought with the gentry's help, the offices sold to pay for the armies, the governors given troops to keep the peace, the officers punished for winning: the empire had paid for one year's survival with its own authority, and the bill was due in the spring of 189. What happened then is not told here: the emperor's death, the quarrel of the general-in-chief with the Regular Attendants and the fire in the palace, and the frontier general who was called to the capital in the confusion, belong to the next line of this series and get no scene in this one.",
      sima: { text: "This is where the line stops, and the stopping is deliberate: 189 and everything in it belong to another telling, and this page has quoted nothing from them. What our four histories leave standing at the end of 188 is the ledger above — provinces with governors who could raise men and hold grain, an inner court that had survived being blamed for the war, a gentry that had been let back in on condition of fighting, and three officers whom the court they saved had arrested, disgraced, or within an ace of recalling.", source: "Hou Han shu, juan 8, Annals of Emperor Ling; juan 64, Memoir of Lu Zhi; juan 71, Memoirs of Huangfu Song and Zhu Jun", tag: "commentary" }
    }
  ],
  myths: [
    {
      myth: "The Yellow Turbans were the opening enemy of the Three Kingdoms heroes, who made their names fighting them.",
      truth: "The war of 184 was fought and won by the dynasty's own career officers — Lu Zhi, Huangfu Song, Zhu Jun, and twice a defeated Dong Zhuo. The future founders are on the record only as junior men: Cao Cao arrives with the relief at Changshe as a cavalry commandant, and Sun Jian carries the wall at Wan as a subordinate commander in Sima Guang's copy of Zhu Jun's account. Liu Bei, Guan Yu and Zhang Fei are nowhere in the record of 184; the peach-garden oath and the brothers' first battles against the Turbans belong to the fourteenth-century Romance of the Three Kingdoms, a novel and not a source.",
      source: "Hou Han shu, juan 71, Memoirs of Huangfu Song and Zhu Jun; Zizhi Tongjian, juan 58; Sanguo yanyi, a 14th-century novel, against them"
    },
    {
      myth: "The rising was a spontaneous explosion of desperate peasants in a bad year.",
      truth: "It was an enrolled organisation with a start of ten-odd years, a head-count, thirty-six divisional chiefs, an appointed day and men at court, and the histories explain the business as a bureaucracy leaking rather than a hunger boiling over. Nothing in the record makes 184 a year of famine; the year before it, and not the year of the rising, is the one the annal enters as having a great drought in the summer and an abundant harvest at its end.",
      source: "Hou Han shu, juan 71, Memoir of Huangfu Song; juan 8, Annals of Emperor Ling; Zizhi Tongjian, juan 58"
    },
    {
      myth: "The rebellion was crushed in 184 and the dynasty was rescued by the victory.",
      truth: "The leadership was destroyed in one autumn and the movement was not: the annals keep entering Yellow Turban bands in province after province for the rest of the reign. What the victory bought was a precedent — the province that feeds its own army and the governor with real troops — and on the reform that made the governorships permanent the Later Han history's own sentence is that the weight of provincial command dates from there.",
      source: "Hou Han shu, juan 8, Annals of Emperor Ling; juan 75, Memoir of Liu Yan"
    },
    {
      myth: "The Taiping way was a scripted religion, and the Classic of Great Peace was the rebels' book.",
      truth: "The histories name no book of the movement's own — a way, a talisman, water, a recited formula, a confession, a day and a colour. But they do not leave it bookless: the memoir of Xiang Kai records how Gong Chong presented, under Emperor Shun, the divine book his master had got at a spring, a hundred and seventy juan called the Register of Great Peace in the Clean Series, how the offices refused it as demon-spoken and irregular and had it put away, and then adds that Zhang Jue came to have a good deal of that book. What is modern and contested is the next step: that the surviving Classic of Great Peace is that book, and so the rebels' scripture.",
      source: "Hou Han shu, juan 30 lower, Memoirs of Lang Yi and Xiang Kai; juan 71, Memoir of Huangfu Song; modern scholarship, contested"
    },
    {
      myth: "The empire rewarded the generals who put the rising down.",
      truth: "Two of the three men this page names as its saviours were struck afterward and the third very nearly was. Lu Zhi lost his command in a prison-cart for refusing to fee an envoy and was condemned, off by one degree. Huangfu Song, in the year after he broke the main host, had his general's seal seized and six thousand households struck off his marquisate on a charge his own memoir says two Regular Attendants made up out of spite. Zhu Jun was saved from recall at Wan only by a colleague's memorial. All three had been enfeoffed and raised first; the years after 184 read as a court settling accounts with its officers, not thanking them.",
      source: "Hou Han shu, juan 64, Memoir of Lu Zhi; juan 71, Memoirs of Huangfu Song and Zhu Jun"
    }
  ],
  sources: [
    { title: "Book of the Later Han (Hou Han shu)", author: "Fan Ye", date: "5th c. CE", detail: "Annals of Emperor Ling, juan 8: the chronology, and the only one of our four books that works by month — the rising in the second, the general-in-chief, the eight passes and the three central commands in the third, the amnesty for the prohibited partisans in the same month with Zhang Jue alone excluded, Zhu Jun's defeat in the fourth, Changshe in the fifth, Runan, Lu Zhi's arrest and the order to Dong Zhuo in the sixth, Cangting in the eighth, Guangzong, the opened coffin and Huangfu Song's chariot-and-cavalry generalship in the tenth, Xiaquyang and the taking of Wan in the eleventh and the winter following, the amnesty and the new reign-title in the twelfth, and the inspectorates turned into governorships in 188." },
    { title: "Book of the Later Han (Hou Han shu)", author: "Fan Ye", date: "5th c. CE", detail: "Memoir of Huangfu Song and memoir of Zhu Jun, juan 71: the movement's origin and organisation — the way of the Yellow Emperor and Laozi, talisman-water and recital, kneeling and confessing offences, the eight provinces, the thirty-six divisions and their sizes, the slogan and the white-earth writing, the day agreed and the Regular Attendants as inside men, Ma Yuanyi's dismemberment and Tang Zhou's letter — and the war: Changshe and the fire and the named relief, Guangzong, Xiaquyang, the opened coffin and the mound; and in Zhu Jun's half, the two sieges of Wan, the surrender refused and the ring deliberately opened." },
    { title: "Book of the Later Han (Hou Han shu)", author: "Fan Ye", date: "5th c. CE", detail: "Memoir of Lu Zhi, juan 64; Memoir of the Eunuchs, juan 78; Memoir of Liu Yan, juan 75; and juan 30 lower, the Memoirs of Lang Yi and Xiang Kai: the northern command, the fee refused, the report made by the man reported, and Huangfu Song's public credit to a rival's planning; the emperor's lord-and-mother sentence, the dealings with Zhang Jue, the bareheaded kowtow and the death of the officer who pressed for the eunuchs' heads; the prices set on appointments and the haggling in the Western Garden; the proposal of 188 with the book's verdict on it; and the one sentence in all our sources that links the movement to a book." },
    { title: "Comprehensive Mirror to Aid in Government (Zizhi Tongjian)", author: "Sima Guang", date: "11th c. CE", detail: "The Later Han chronicles for 181 to 187: the relay that puts the annal and the memoirs into one stream and is relied on here as a relay, and the source of three things the Han books do not give in the same way — the name of the way of Great Peace, the season of Tang Zhou's letter and the month of the relief at Changshe, and the officer storming Wan at the head of Zhu Jun's men." },
    { title: "Emperor Huan and Emperor Ling", author: "Rafe de Crespigny", date: "1996", detail: "Annotated translation of the Tongjian's Later Han chronicles for 157 to 189: the year-by-year frame this episode's dates are checked against, and the notes behind its cast — the four commanders, the eunuchs in the plot, the governors of 188." }
  ]
};
